#!/usr/bin/env perl
# runner: perl @FILE@ @REPO@
# phase: compile
# expectstdout: compiler addressing-mode policy ok: 0 forced ordinary mnemonic suffixes
# expectexit: 0

use strict;
use warnings;
use File::Spec;

my $repo = shift @ARGV;
die "usage: $0 REPO\n" unless defined $repo && -d $repo;

my $compiler = File::Spec->catdir($repo, 'compiler');
opendir(my $dh, $compiler) or die "cannot open $compiler: $!\n";
my @files = sort grep { /\.(?:c|h)\z/ } readdir($dh);
closedir($dh);

# Addressing-mode suffixes are a source-assembly timing/encoding control.  The
# compiler emits semantic memory references without them and lets vcsc-as use
# .zpimport/.segmentaddrsize plus normal relaxation to select the shortest legal
# direct mode.  Raw opcode spelling is not generated by the compiler and is
# intentionally outside this policy.
my $mnemonic = qr/(?:lda|ldx|ldy|sta|stx|sty|adc|sbc|and|ora|eor|cmp|cpx|cpy|inc|dec|asl|lsr|rol|ror|bit)/i;
my $suffix = qr/(?:z|zx|zy|a|ax|ay|i|ix|iy)/i;
my @bad;

for my $file (@files) {
    my $path = File::Spec->catfile($compiler, $file);
    open(my $fh, '<', $path) or die "cannot read $path: $!\n";
    my $line_no = 0;
    while (my $line = <$fh>) {
        ++$line_no;
        push @bad, "compiler/$file:$line_no:$line"
            if $line =~ /\b$mnemonic\.$suffix\b/;
    }
    close($fh);
}

if (@bad) {
    die "compiler-generated ordinary addressing-mode suffixes remain:\n@bad";
}

print "compiler addressing-mode policy ok: 0 forced ordinary mnemonic suffixes\n";
