#!/usr/bin/env perl
# runner: perl @FILE@ @REPO@ @TMP@

use strict;
use warnings;
use Cwd qw(abs_path);
use File::Path qw(make_path);
use File::Spec;
use IPC::Open3;
use Symbol qw(gensym);

sub write_file { my ($p,$d)=@_; open(my $f,'>:raw',$p) or die "write $p: $!\n"; print {$f} $d; close($f) or die "close $p: $!\n"; }
sub slurp { my ($p)=@_; open(my $f,'<:raw',$p) or die "read $p: $!\n"; local $/; my $d=<$f>; close($f); return defined($d)?$d:''; }
sub run_capture { my (@c)=@_; my $e=gensym; my $pid=open3(my $in,my $out,$e,@c); close($in); local $/; my $o=<$out>//''; my $x=<$e>//''; waitpid($pid,0); return ($?>>8,$?&127,$o,$x); }
sub require_ok { my ($n,@c)=@_; my ($x,$s,$o,$e)=run_capture(@c); $x==0&&!$s or die "$n failed\n@c\n$o$e"; $e eq '' or die "$n stderr: $e"; }

my $repo=abs_path(shift @ARGV // die "usage: $0 REPO TMP\n");
my $tmp=shift @ARGV // die "usage: $0 REPO TMP\n"; @ARGV and die "usage: $0 REPO TMP\n";
make_path($tmp); $tmp=abs_path($tmp);
my $as=File::Spec->catfile($repo,'assembler','vcsc-as');
my $ld=File::Spec->catfile($repo,'linker','vcsc-ld');
my $driver=File::Spec->catfile($repo,'driver','vcsc');
my $vcs=File::Spec->catdir($repo,'libraries','vcs');

# Maintained S26 source must survive into the final linked listing.
my $s26=File::Spec->catfile($tmp,'human.s26');
my $o26=File::Spec->catfile($tmp,'human.o26');
my $cfg=File::Spec->catfile($tmp,'human.cfg');
my $bin=File::Spec->catfile($tmp,'human.bin');
write_file($s26, <<'ASM');
.segment "CODE"
.export __reset, __nmi, __irqbrk, main
__reset:
main:
  lda #$42
  sta $0280
  rts
__nmi:
  rti
__irqbrk:
  rti
ASM
write_file($cfg, <<'CFG');
MEMORY {
 RAM: start=$0080,size=$0080,type=rw;
 ROM: start=$F000,size=$0FFA,type=ro;
 VECTORS: start=$FFFA,size=$0006,type=ro;
}
SEGMENTS {
 ZEROPAGE: load=RAM,type=zp;
 DATA: load=ROM,run=RAM,type=data;
 BSS: load=RAM,type=bss;
 CODE: load=ROM,type=ro;
 RODATA: load=ROM,type=ro;
 VECTORS: load=VECTORS,type=ro;
}
CFG
require_ok('assemble S26',$as,'-o',$o26,$s26);
require_ok('link S26',$ld,'-T',$cfg,'-o',$bin,$o26);
my $lst=slurp(File::Spec->catfile($tmp,'human.lst'));
$lst =~ /Human source listing; addresses and bytes are final after relocation/ or die "human-list header missing\n$lst";
$lst =~ /\Q$s26\E:5[^\n]*\| lda #\$42\n\s*\d+\s+f000\s+a9\s+42\s+[^\n]*;\s+LDA #66/i
   or die "S26 source/bytes/assembly correlation missing\n$lst";
$lst =~ /\Q$s26\E:6[^\n]*\| sta \$0280\n\s*\d+\s+f002\s+8d\s+80\s+02\s+[^\n]*;\s+STA 640\s+=>\s+\$0280/i
   or die "S26 final absolute operand missing\n$lst";

# C26 provenance must survive compiler -> assembler -> object -> linker, and
# split-address Superchip symbols must show the actual final write/read aliases.
my $c26=File::Spec->catfile($tmp,'human_sc.c26');
my $scbin=File::Spec->catfile($tmp,'human_sc.bin');
write_file($c26, <<'C26');
include "vcs_8k_f8sc.c26"
cartram uint8_t sc[6];
uint8_t sink;
void main(void) {
   sc[4] := 0x55;
   sink := sc[4];
   while (1) { }
}
C26
require_ok('compile/link C26',$driver,'-I',$vcs,'-T',File::Spec->catfile($vcs,'vcs.cfg'),'-o',$scbin,$c26);
my $sclst=slurp(File::Spec->catfile($tmp,'human_sc.lst'));
$sclst =~ /\Q$c26\E:5[^\n]*\| sc\[4\] := 0x55;/ or die "C26 store source provenance missing\n$sclst";
$sclst =~ /\Q$c26\E:6[^\n]*\| sink := sc\[4\];/ or die "C26 load source provenance missing\n$sclst";
my ($write_addr)=$sclst =~ /;\s+STA \(\(sc - 128\) \+ 4\)\s+=>\s+\$([0-9A-Fa-f]{4})/;
my ($read_addr) =$sclst =~ /;\s+LDA \(sc \+ 4\)\s+=>\s+\$([0-9A-Fa-f]{4})/;
defined($write_addr) && defined($read_addr) or die "Superchip resolved read/write aliases not visible\n$sclst";
hex($read_addr)-hex($write_addr) == 0x80 or die "Superchip aliases do not differ by 0x80: write=$write_addr read=$read_addr\n";
$sclst =~ /; <compiler-generated>/ or die "compiler-generated bytes are not marked honestly\n$sclst";
$sclst !~ /\/tmp\/vcsc\.[^\n]*\.s26:[0-9]+[^\n]*\| sc\[4\]/ or die "C26 statement fell back to temporary S26 provenance\n$sclst";

print "human linked listing ok\n";
