#!/usr/bin/perl
# runner: perl @FILE@ @REPO@ @TMP@
# phase: e2e
# expectstdout: vcs_define_reserved_register_name ok
# expectexit: 0
#
# -D names that collide with an assembler register must be rejected by name.
#
# The driver forwards every -D to the assembler as well as to the compiler, and
# the assembler lexer hardcodes A, X and Y as register tokens. A define named A
# therefore became the source line "A = 5", which lexed as REG_A '=' 5 and failed
# to parse. The only diagnostic was a bare "<command-line>:1: parse error" that
# mentioned neither the define nor the reason.
#
# That is a nasty shape of bug: it looks like a parser failure, so the natural
# reaction is to blame the preprocessor or the grammar rather than the define.
# It also silently constrains test-vector naming, since the obvious short names
# are exactly the reserved ones.
use strict;
use warnings;
use Cwd qw(abs_path);
use File::Spec;
use IPC::Open3;
use Symbol qw(gensym);

sub usage { die "usage: $0 REPO TMP\n" }
sub slurp_fh { my($fh)=@_; local $/; my $d=<$fh>; return defined($d)?$d:'' }
sub capture {
   my(@cmd)=@_;
   my $err=gensym;
   my $pid=open3(my $in,my $out,$err,@cmd); close($in);
   my $so=slurp_fh($out); my $se=slurp_fh($err); waitpid($pid,0);
   return ($?>>8,$?&127,$so,$se);
}

my $repo=shift @ARGV // usage();
my $tmp=shift @ARGV // usage();
usage() if @ARGV;
$repo=abs_path($repo) // die "resolve repository\n";
$tmp=abs_path($tmp) // die "resolve temporary directory\n";

my $driver=$ENV{VCSC_DRIVER} || File::Spec->catfile($repo,qw(driver vcsc));
my $vcs=File::Spec->catdir($repo,qw(libraries vcs));

# The program deliberately never mentions any define: a -D that cannot even be
# delivered must be diagnosed on its own, not as a side effect of use.
sub slurp_file { my($p)=@_; open(my $f,'<:raw',$p) or return undef; local $/; my $d=<$f>; close($f); return $d }
my $as=$ENV{VCSC_AS} || File::Spec->catfile($repo,qw(assembler vcsc-as));
my $s26=File::Spec->catfile($tmp,"defsuffix.s26");
my $src=File::Spec->catfile($tmp,'defreserve.c26');
my $bin=File::Spec->catfile($tmp,'defreserve.bin');
open(my $fh,'>',$src) or die "write $src: $!\n";
print $fh <<'EOT';
// Generated by vcs_define_reserved_register_name.pl
include "vcs.c26"
void main(void) {
   VBLANK := 2;
   while (1) { }
}
EOT
close($fh);

# Reserved: the three register tokens the assembler lexer hardcodes.
for my $name (qw(A X Y a x y)) {
   for my $spec ("-D${name}=5", "-D${name}") {
      my($rc,$sig,$o,$e)=capture($driver,'-I',$vcs,$spec,$src,'-o',$bin);
      $rc!=0 || $sig
         or die "-D${name}= value was accepted; a reserved register name must be rejected\n$o$e";
      ($o.$e) =~ /is an assembler register and cannot be redefined/
         or die "-D${name}= was rejected without naming the register collision\n$o$e";
      ($o.$e) !~ /parse error/
         or die "-D${name}= still surfaces the old bare parser error\n$o$e";
   }
}

# Not reserved: ordinary define names must keep working, including the ones that
# merely start with a register letter. This is the half that would regress if the
# check were written as a prefix test instead of an exact-name test.
for my $spec ('-DAB=5','-DAVX=5','-DFOO=5','-DALPHA=5','-DXRAY=9','-DYOURS=1','-DB=5','-DZ=5','-DSP=1',
              '-Dsame=1','-Dcross=1','-Dflex=1','-Dzx=1','-Diy=1') {
   my($rc,$sig,$o,$e)=capture($driver,'-I',$vcs,$spec,$src,'-o',$bin);
   $rc==0 && !$sig
      or die "$spec was rejected but is a perfectly good define name\n$o$e";
}

# Addressing-mode suffixes and branch specifiers are NOT reserved on their own.
# The lexer only matches them as dot-suffixed forms, and a define name cannot
# contain a dot, so there is no collision to prevent. Rejecting them would forbid
# ordinary symbol names: `same`, `cross`, `flex` and the bare mode letters are all
# legal assembly symbols today, so the check above must keep accepting them.
{
   my $s26=File::Spec->catfile($tmp,'defsuffix.s26');
   my $o26=File::Spec->catfile($tmp,'defsuffix.o26');
   open(my $fh,'>',$s26) or die "write $s26: $!\n";
   print $fh "\t.segment \"CODE\"\n\t.export go\ngo:\n\tsame = 3\n\tcross = 4\n\tflex = 5\n\tz = 6\n\tzx = 7\n\tiy = 8\n\trts\n";
   close($fh);
   my($rc,$sig,$o,$e)=capture($as,$s26,'-o',$o26);
   $rc==0 && !$sig
      or die "symbols named same/cross/flex/z/zx/iy are legal and must stay legal\n$o$e";
}

# A dot in a define name is refused outright, so a dot-suffixed mnemonic such as
# jsr.abs can never reach the opcode check in the first place.
{
   my($rc,$sig,$o,$e)=capture($driver,'-I',$vcs,'-Djsr.abs=1',$src,'-o',$bin);
   $rc!=0 || $sig or die "-Djsr.abs=1 was accepted; a define name may not contain a dot";
   ($o.$e) =~ /invalid -D name/
      or die "-Djsr.abs=1 was rejected for the wrong reason\n$o$e";
}

# Opcode mnemonics must be rejected, in any case. The generic opXX form is
# included, and the check is driven by the loaded opcode table so a user-supplied
# -f config's mnemonics are covered too rather than only the built-in set.
for my $name (qw(sta lda clc jsr rts jmp), qw(STA LDA CLC), qw(opFF opff OPFF op8B op00), qw(opAb)) {
   for my $spec ("-D${name}=1") {
      my($rc,$sig,$o,$e)=capture($driver,'-I',$vcs,$spec,$src,'-o',$bin);
      $rc!=0 || $sig
         or die "$spec was accepted; an opcode mnemonic must not be redefinable\n$o$e";
      ($o.$e) =~ /is an opcode mnemonic and cannot be redefined/
         or die "$spec was rejected without naming the mnemonic collision\n$o$e";
      ($o.$e) !~ /parse error/
         or die "$spec still surfaces the old bare parser error\n$o$e";
   }
}

# A mnemonic contributed by a user config must be rejected as well. This is the
# case a hand-written opcode list would miss, and it is why the check consults the
# loaded table instead of a pattern.
{
   my $cfg=File::Spec->catfile($tmp,'defuser.cfg');
   my $o26=File::Spec->catfile($tmp,'defuser.o26');
   open(my $fh,'>',$cfg) or die "write $cfg: $!\n";
   print $fh "userop12  imp  \$12\n";
   close($fh);
   my($rc,$sig,$o,$e)=capture($as,'--opcode-cfg',$cfg,'-Duserop12=1',$s26,'-o',$o26);
   $rc!=0 || $sig
      or die "a mnemonic from a user config was accepted as a define name\n$o$e";
   ($o.$e) =~ /is an opcode mnemonic and cannot be redefined/
      or die "user-config mnemonic rejected for the wrong reason\n$o$e";
}


# A -D must never rewrite a dot-suffixed addressing mode or branch specifier.
#
# This is the sharp edge of allowing same/cross/flex/abs as define names. They are
# legal symbol names, so they can be defined; the hazard is an implementation that
# treats -D as a textual macro rather than a symbol assignment and rewrites the
# `.abs` in `jsr.abs` into `jsr.foo`. Today the assembler prepends a
# "name = value" line and does no substitution, so the dotted forms are
# unaffected. If that ever changes, a source full of `.same`/`.cross` would either
# stop assembling or, worse, assemble to different bytes.
{
   my $mod=File::Spec->catfile($tmp,'defmode.s26');
   open(my $fh,'>',$mod) or die "write $mod: $!\n";
   print $fh "\t.segment \"CODE\"\n\t.export go\ngo:\n\tlda #<label\n\tbeq.same go\n\tbne.same go\n\tbne.cross go\nlabel:\n\trts\n";
   close($fh);

   # Compare the HEX code image, not the o26 container. Defining a symbol really
   # does allocate it, so the o26 legitimately gains a __default__ segment and its
   # bytes differ for reasons unrelated to substitution. The hex image is the
   # assembled instruction stream, which is precisely what must not change.
   my $hex=File::Spec->catfile($tmp,'defmode.hex');
   my $o26=File::Spec->catfile($tmp,'defmode.o26');

   my($rc,$sig,$o,$e)=capture($as,$mod,'-o',$o26,"--hex=$hex");
   $rc==0 && !$sig && $o eq '' && $e eq ''
      or die "baseline dot-suffix source does not assemble cleanly\n$o$e";
   my $base_hex=slurp_file($hex);

   for my $spec ('-Dabs=1','-Dsame=1','-Dcross=1','-Dflex=1') {
      my($rc2,$sig2,$o2,$e2)=capture($as,$spec,$mod,'-o',$o26,"--hex=$hex");
      $rc2==0 && !$sig2 && $o2 eq '' && $e2 eq ''
         or die "$spec broke a dot-suffixed addressing mode or branch specifier\n$o2$e2";
   }

   my($rc3,$sig3,$o3,$e3)=capture($as,'-Dabs=1','-Dsame=1','-Dcross=1','-Dflex=1',$mod,'-o',$o26,"--hex=$hex");
   $rc3==0 && !$sig3 && $o3 eq '' && $e3 eq ''
      or die "combined mode defines broke a dot-suffixed form\n$o3$e3";
   my $with_hex=slurp_file($hex);

   (defined($base_hex) && defined($with_hex) && length($base_hex) && $base_hex eq $with_hex)
      or die "defining abs/same/cross/flex changed the assembled instruction stream: a -D is being applied as a textual macro to the dot-suffixed forms\n";

   # Belt and braces on the exact hazard named in review: with a define value that
   # could never be a valid operand, a textual macro would rewrite the `.abs` in
   # `jsr.abs` into `.foo` and the assembler would name the source file. Today the
   # only diagnostic is the define line itself, on <command-line>.
   my $jsr=File::Spec->catfile($tmp,'defmode_jsr.s26');
   open(my $fhj,'>',$jsr) or die "write $jsr: $!\n";
   print $fhj "\t.segment \"CODE\"\n\t.export go\ngo:\tbeq.same go\n\tlda abs\n\trts\n";
   close($fhj);
   my($rc4,$sig4,$o4,$e4)=capture($as,'-Dabs=foo','-Dsame=foo',$jsr,'-o',$o26);
   my $text=$o4.$e4;
   $text !~ /\bfoo\b.*\Q$jsr\E|\Q$jsr\E.*\bfoo\b/s
      or die "a dot-suffixed form in the source was rewritten to the define value:\n$text";
   # The define must still be live, so that the check above is not vacuous: a bare
   # symbol reference really does take the defined value.
   my $use=File::Spec->catfile($tmp,'defmode_use.s26');
   my $uo=File::Spec->catfile($tmp,'defmode_use.o26');
   open(my $fh2,'>',$use) or die "write $use: $!\n";
   print $fh2 "\t.segment \"CODE\"\n\t.export go\ngo:\tlda abs\n\tldx #7\n\trts\n";
   close($fh2);
   my($urc,$usig,$uo2,$ue)=capture($as,'-Dabs=0',$use,'-o',$uo);
   $urc==0 && !$usig
      or die "a bare abs symbol reference did not pick up -Dabs=0, so the define path is not being exercised\n$uo2$ue";
}

print "vcs_define_reserved_register_name ok: -D names A, X and Y (either case, with or without a value) are rejected as assembler registers, and every opcode mnemonic is rejected including the generic opXX form in any case and mnemonics contributed by a user --opcode-cfg; names merely beginning with those letters, and the bare mode/branch words same, cross, flex, abs, z, zx, iy, stay valid because they are reserved only in dot-suffixed form; and defining abs/same/cross/flex provably does not rewrite a dot-suffixed form such as jsr.abs, asserted by an unchanged hex code image plus a bare symbol reference still taking the defined value; vcsc-as enforces all of this directly\n";