#!/usr/bin/perl
# runner: perl @FILE@ @REPO@ @TMP@
# phase: e2e
# expectstdout: vcs_all_five_stripe_geometry_compile ok
# expectexit: 0
#
# Compile-time geometry contract for the generic positive-stripe renderer.
#
# stripe_generic_geometry_bound.pl is the executable geometry authority.  This
# regression proves the renderer source enforces the same rules rather than
# merely describing them, by building one fixture per accepted (lines, stripes)
# pair and one per rejected configuration.  Because the VCSC preprocessor
# compares a bare TEMPLATE_x against an integer literal and supports no
# arithmetic, these rules are necessarily spelled out per case; this test is
# what keeps that table honest.
use strict;
use warnings;
use Cwd qw(abs_path);
use File::Spec;
use IPC::Open3;
use Symbol qw(gensym);

sub usage { die "usage: $0 REPO TMP\n" }
sub slurp_fh { my($fh)=@_; local $/; my $d=<$fh>; return defined($d)?$d:''; }
sub capture {
   my(@cmd)=@_;
   my $err=gensym;
   my $pid=open3(my $in,my $out,$err,@cmd); close($in);
   my $so=slurp_fh($out); my $se=slurp_fh($err); waitpid($pid,0);
   return ($?>>8,$?&127,$so,$se);
}

my $colors;   # ABI colour-array size for the fixture under construction
my $data;     # ABI playfield-data size for the fixture under construction

my $repo=shift @ARGV // usage();
my $tmp=shift @ARGV // usage();
usage() if @ARGV;
$repo=abs_path($repo) // die "resolve repository\n";
$tmp=abs_path($tmp) // die "resolve temporary directory\n";

my $driver=$ENV{VCSC_DRIVER} || File::Spec->catfile($repo,qw(driver vcsc));
my $vcs=File::Spec->catdir($repo,qw(libraries vcs));

# Write a fixture that instantiates the requested (lines, stripes) and supplies
# the N*2 colour plus N*6 data arrays the ABI requires.
sub build {
   my($tag,$lines,$stripes)=@_;
   my $src=File::Spec->catfile($tmp,"geom_$tag.c26");
   my $bin=File::Spec->catfile($tmp,"geom_$tag.bin");
   my $map=File::Spec->catfile($tmp,"geom_$tag.map");
   $colors=2*$stripes;
   $data=6*$stripes;
   my $c=join(',',map { sprintf('0x%02x',0x10+$_) } 1..$colors);
   my $d=join(',',map { sprintf('0x%02x',0xf0-($_%4)*0x10) } 1..$data);
   # The renderer still declares a plain playfield array sized by line mode.
   my %pfbytes=(170=>40,181=>44,192=>48,228=>60);
   my $pfbytes=$pfbytes{$lines}
      or die "no playfield size known for lines=$lines\n";
   my $pfdata=join(',',map { sprintf('0x%02x',($_%2)?0xf0:0xaa) } 1..$pfbytes);
   open(my $fh,'>',$src) or die "write $src: $!\n";
   # The fixture supplies every array the renderer declares for this
   # configuration: the generic stripe ABI, the zero-stripe playfield pair the
   # renderer still requires as a symbol, and the sprite graphics/position state
   # the object pipeline needs.  Only the stripe counts and line count vary.
   print $fh <<"EOT";
// Generated by vcs_all_five_stripe_geometry_compile.pl --lines=$lines --stripes=$stripes
include "vcs.c26"
const uint8_t game_playfield_colors[$colors] := { $c };
const uint8_t game_playfield_data[$data] := { $d };
const uint8_t game_playfield[$pfbytes] := { $pfdata };
instantiate "renderers/all_five/all_five.c26" as game (lines:=$lines, stripes:=$stripes)
page const uint8_t p0_graphics[8] := {
   game_SPRITE_GLYPH(0x3c,0x66,0x66,0x7e,0x66,0x66,0x66,0x00)
};
page const uint8_t p1_graphics[8] := {
   game_SPRITE_GLYPH(0x7c,0x66,0x66,0x7c,0x66,0x66,0x7c,0x00)
};
void main(void) {
   VBLANK := 2;
   COLUBK := 0x84;
   COLUPF := 0x2e;
   COLUP0 := 0x0e;
   COLUP1 := 0xc8;
   CTRLPF := 0x21;
   game_PLAYER0_NUSIZ := 0x20;
   game_PLAYER1_NUSIZ := 0x20;
   game_player0_color := 0x0e;
   game_player1_color := 0xc8;
   game_PLAYER0_X := 20;
   game_PLAYER1_X := 130;
   game_MISSILE0_X := 50;
   game_MISSILE1_X := 110;
   game_BALL_X := 80;
   game_player0_y := 18;
   game_player1_y := 78;
   game_missile0_y := 34;
   game_missile1_y := 62;
   game_ball_y := 48;
   game_player0_graphics := p0_graphics;
   game_player1_graphics := p1_graphics;
   game_player0_height := 7;
   game_player1_height := 7;
   game_missile0_height := 5;
   game_missile1_height := 7;
   game_ball_height := 3;
   game_playfield_position := 8;
   game_init();
   while (1) {
      game_vblank();
      game_draw();
      game_overscan();
   }
}
EOT
   close($fh);
   my($rc,$sig,$o,$e)=capture($driver,'-I',$vcs,'-Map',$map,$src,'-o',$bin);
   return ($rc,$sig,$o,$e,$map);
}

# ------------------------------------------------------------------ accepted
# The line modes whose stripe raster body is actually emitted.  Each of these
# must both build AND demonstrably emit stripe state, because "it linked" is not
# evidence that stripes happen: an unimplemented line mode links cleanly and
# draws an un-striped frame.
my @accept=(
   [ 'a192_1', 192, 1 ],
   [ 'a192_2', 192, 2 ],
   [ 'a228_1', 228, 1 ],
   [ 'a228_2', 228, 2 ],
);
for my $a (@accept) {
   my($tag,$lines,$stripes)=@$a;
   my($rc,$sig,$o,$e,$map)=build($tag,$lines,$stripes);
   $rc==0 && !$sig
      or die "legal (lines=$lines, stripes=$stripes) failed to build\n$o$e";
   die "(lines=$lines, stripes=$stripes) is legal but a guard fired\n$o$e"
      if $o =~ /raster_not_yet_emitted|vcsc_stripes_currently_require_solid_all_five_object_profile|vcsc_stripes_generic_machine/;
   open(my $fh,'<:raw',$map) or die "read $map: $!\n";
   local $/; my $body=<$fh>; close($fh);
   # The ABI arrays must be linked at their full generic sizes, which is what
   # proves the table is driven by TEMPLATE_stripes rather than a fixed count.
   for my $spec ([ 'playfield_colors',2*$stripes ], [ 'playfield_data',6*$stripes ]) {
      my($sym,$want)=@$spec;
      # The map prints `RODATA.__vcsc_object$<symbol>` inside the owning
      # object's block, so match on the symbol without a leading word boundary:
      # the character before it is '$', and the object prefix ends in '_'.
      $body =~ /RODATA[^\n]*\Q$sym\E[^\n]*size=\$([0-9A-Fa-f]{4})/
         or die "($lines,$stripes) has no RODATA entry for $sym\n$body";
      hex($1)==$want
         or die "($lines,$stripes) $sym linked at ".hex($1)." bytes, expected $want\n";
   }
   # Positive evidence that the stripe raster was emitted.  A build that links
   # without these symbols draws no stripes at all, which is exactly the failure
   # this check exists to catch.
   for my $sym ('game_stripe_cache') {
      $body =~ /\Q$sym\E/
         or die "($lines,$stripes) built but emitted no $sym: the stripe raster is absent\n$body";
   }
}

# ------------------------------------------------------------------ rejected
# Each entry differs from an accepted configuration in exactly the guarded
# dimension, so acceptance of the baseline plus refusal here is what proves the
# guard fires.  A negative array size produces a diagnostic with no symbol
# name, so the test discriminates by behaviour rather than by error text.
my($brc,$bsig,$bo,$be)=build("base_192_2",192,2);
$brc==0 && !$bsig or die "baseline (192,2) does not build, so refusal proves nothing\n$bo$be";
for my $r ([ "line mode 170",170,2 ], [ "line mode 181",181,2 ],
              [ "stripes above two",192,3 ], [ "stripes 32 stress point",192,32 ]) {
   my($what,$lines,$stripes)=@$r;
   my($rc,$sig,$o,$e)=build("rej_${lines}_${stripes}",$lines,$stripes);
   $rc!=0 || $sig or die "$what was accepted; its guard does not fire\n$o$e";
   ($o.$e) =~ /all_five\.c26/ or die "$what failed for an unrelated reason\n$o$e";
}

# The object-profile guard discriminates on its own dimension as well: the
# same (192,2) geometry with missiles:=0 must be refused.
{
   my $src=File::Spec->catfile($tmp,"geom_profile.c26");
   my $bin=File::Spec->catfile($tmp,"geom_profile.bin");
   open(my $fh,">",$src) or die "write $src: $!\n";
   print $fh <<"EOT";
include "vcs.c26"
const uint8_t game_playfield_colors[4] := { 0x2e,0x84,0x4e,0x24 };
const uint8_t game_playfield_data[12] := { 0xf0,0xff,0xff,0xf0,0xff,0xff, 0x50,0x81,0x42,0xa0,0x24,0x18 };
const uint8_t game_playfield[48] := { 0xaa };
instantiate "renderers/all_five/all_five.c26" as game (lines:=192, stripes:=2, missiles:=0)
page const uint8_t p0_graphics[8] := { game_SPRITE_GLYPH(0x3c,0x66,0x66,0x7e,0x66,0x66,0x66,0x00) };
page const uint8_t p1_graphics[8] := { game_SPRITE_GLYPH(0x7c,0x66,0x66,0x7c,0x66,0x66,0x7c,0x00) };
void main(void) {
   VBLANK := 2;
   game_init(); game_vblank(); game_draw(); game_overscan();
   while (1) { }
}
EOT
   close($fh);
   my($rc,$sig,$o,$e)=capture($driver,"-I",$vcs,$src,"-o",$bin);
   $rc!=0 || $sig or die "positive stripes accepted missiles:=0 while (192,2) solid builds";
   ($o.$e) =~ /all_five\.c26/ or die "non-solid profile failed for an unrelated reason\n$o$e";
}

print "vcs_all_five_stripe_geometry_compile ok\n";
