#!/usr/bin/perl
# This file is covered under CC0-1.0. See examples/LICENSE.txt.
use strict;
use warnings;

@ARGV == 1 or die "usage: $0 diagnostic_collision_objects.font\n";
my $path = $ARGV[0];
open my $fh, '<', $path or die "read $path: $!\n";
my @object_rows;
my @pass_rows;
my $pass = 0;
while (my $line = <$fh>) {
   chomp $line;
   $line =~ s/\r$//;
   next if $line =~ /^\s*(?:#|$)/;
   if ($line eq 'PASS') { $pass = 1; next; }
   if (!$pass) { push @object_rows, $line; }
   else { push @pass_rows, $line; }
}
close $fh;

@object_rows == 6 or die "$path: expected six object-font rows\n";
@pass_rows == 6 or die "$path: expected six PASS rows\n";
my @names = qw(M0 M1 P0 P1 BL PF);
my %glyph;
for my $r (0..5) {
   my @parts = split /_/, $object_rows[$r], -1;
   @parts == 6 or die "$path: row ".($r+1)." must contain six underscore-separated glyphs\n";
   for my $i (0..5) {
      $parts[$i] =~ /^[X.]{3}$/ or die "$path: $names[$i] row ".($r+1)." is not 3 pixels\n";
      $glyph{$names[$i]}[$r] = $parts[$i];
   }
}
for my $r (0..5) {
   $pass_rows[$r] =~ /^[X.]{6}$/ or die "$path: PASS row ".($r+1)." is not 6 pixels\n";
}
for my $name (@names) {
   $glyph{$name}[3] eq '...' or die "$path: $name middle row must remain blank for collision bar\n";
}

my @top = (
   ['M0','P1'], ['M0','P0'], ['M1','P0'], ['M1','P1'],
   ['P0','PF'], ['P0','BL'], ['P1','PF'], ['P1','BL'],
);
my @bottom = (
   ['M0','PF'], ['M0','BL'], ['M1','PF'], ['M1','BL'],
   ['BL','PF'], ['P0','P1'], ['M0','M1'], ['PASS'],
);

sub icon_rows {
   my ($spec, $active) = @_;
   if (@$spec == 1 && $spec->[0] eq 'PASS') {
      return $active ? @pass_rows : (('......') x 6);
   }
   my ($a,$b) = @$spec;
   my @rows;
   for my $r (0..5) {
      my $bits = $glyph{$a}[$r] . $glyph{$b}[$r];
      $bits = 'XXXXXX' if $active && $r == 3;
      push @rows, $bits;
   }
   return @rows;
}

sub emit_font {
   my ($symbol, $icons, $label) = @_;
   print "bank3 page const uint8_t $symbol\[144\] := {\n";
   for my $chunk (0..5) {
      my ($left_icon,$right_icon) = $chunk < 3
         ? ($chunk, $chunk+1)
         : ($chunk+1, $chunk+2);
      for my $state (0..3) {
         my @icon_bits;
         for my $i (0..7) {
            my $active = 0;
            $active = ($state >> 1) & 1 if $i == $left_icon;
            $active = $state & 1 if $i == $right_icon;
            push @icon_bits, [ icon_rows($icons->[$i], $active) ];
         }
         my @bytes;
         for my $r (0..5) {
            my $line = join('', map { $_->[$r] } @icon_bits);
            my $byte = substr($line, $chunk*8, 8);
            push @bytes, $byte;
         }
         my $offset = $chunk*24 + $state*6;
         print "   // $label chunk $chunk state $state, offset $offset\n";
         # six_glyph_component draws row index 5 first, so store bottom-to-top.
         for my $r (reverse 0..5) {
            print "   0b$bytes[$r]";
            print "," unless $chunk == 5 && $state == 3 && $r == 0;
            print "\n";
         }
      }
   }
   print "};\n\n";
}

print <<'HDR';
// This file is covered under CC0-1.0. See examples/LICENSE.txt.
// Generated by make_collision_font.pl from diagnostic_collision_objects.font.
// Do not hand-edit this generated file; edit the .font source instead.
//
// Each logical collision icon is six pixels wide: two three-pixel object
// microglyphs.  Inactive icons retain the blank middle row; active icons fill
// that row with six pixels.  Six 8-bit chunks therefore render eight icons
// across the existing 48-pixel six-glyph display width.
//
// Icon order follows the TIA collision-register bit order:
// top:    M0-P1 M0-P0 M1-P0 M1-P1 P0-PF P0-BL P1-PF P1-BL
// bottom: M0-PF M0-BL M1-PF M1-BL BL-PF P0-P1 M0-M1 PASS

HDR

emit_font('diagnostic_collision_top_font', \@top, 'top');
emit_font('diagnostic_collision_bottom_font', \@bottom, 'bottom');
print "bank3 const uint8_t diagnostic_collision_window_a[16] := {\n   " . join(',', map { ((($_ >> 2) & 3) * 6) } 0..15) . "\n};\n";
print "bank3 const uint8_t diagnostic_collision_window_b[16] := {\n   " . join(',', map { ((($_ >> 1) & 3) * 6) } 0..15) . "\n};\n";
print "bank3 const uint8_t diagnostic_collision_window_c[16] := {\n   " . join(',', map { (($_ & 3) * 6) } 0..15) . "\n};\n";
