#!/usr/bin/env perl
# This file is covered under CC0-1.0. See examples/LICENSE.txt.
use strict;
use warnings;
use FindBin qw($Bin);

my $lower_banks = 255;
my $banks_per_object = 32; # O26 CODE offsets are 16-bit; 32 x 2K fits exactly.
my (@wait_font_bytes, @status_font_bytes);

sub generated_header {
   my ($fh, $detail) = @_;
   print {$fh} "; Generated by make_torture.pl; do not edit.\n";
   print {$fh} "; This file is covered under CC0-1.0. See examples/LICENSE.txt.\n";
   print {$fh} ";\n";
   print {$fh} "; Maximum-size Tigervision 3F torture payload. $detail\n";
   print {$fh} "; Cross-bank calls execute a tiny inline descriptor stub from RIOT RAM so\n";
   print {$fh} "; the full 255 x 255 ordered matrix fits in one 512K cartridge.\n\n";
}

sub emit_bank {
   my ($fh, $bank, $link_root) = @_;
   printf {$fh} ".segmentalign \"CODE.bank%d\", 2048\n", $bank;
   printf {$fh} ".segment \"CODE.bank%d\"\n", $bank;
   printf {$fh} "bank%d_source:\n", $bank;
   print  {$fh} "    tsx\n";
   print  {$fh} "    stx source_sp\n";
   printf {$fh} "bank%d_dest_loop:\n", $bank;
   print  {$fh} "    lda expected_dest\n";
   printf {$fh} "    cmp #\$%02X\n", $bank;
   printf {$fh} "    beq.same bank%d_same\n", $bank;
   print  {$fh} "    sta lower_stub+5\n";
   print  {$fh} "    jsr lower_stub\n";
   printf {$fh} "    jmp bank%d_after\n", $bank;
   printf {$fh} "bank%d_same:\n", $bank;
   printf {$fh} "    jsr bank%d_target\n", $bank;
   printf {$fh} "bank%d_after:\n", $bank;

   # The immediate differs in every physical source bank. If bankreturn restores
   # the wrong bank, execution resumes at the same CPU PC but loads the wrong
   # immediate and this comparison fails.
   printf {$fh} "    lda #\$%02X\n", $bank;
   print  {$fh} "    cmp expected_source\n";
   printf {$fh} "    beq.same bank%d_restored\n", $bank;
   print  {$fh} "    lda #\$02\n";
   print  {$fh} "    sta failure\n";
   printf {$fh} "bank%d_restored:\n", $bank;

   print  {$fh} "    inc expected_dest\n";
   print  {$fh} "    lda expected_dest\n";
   print  {$fh} "    cmp #\$FF\n";
   printf {$fh} "    beq.same bank%d_source_done\n", $bank;
   print  {$fh} "    dec step_remaining\n";
   printf {$fh} "    bne.same bank%d_dest_loop\n", $bank;
   printf {$fh} "    jmp bank%d_step_done\n", $bank;

   printf {$fh} "bank%d_source_done:\n", $bank;
   print  {$fh} "    jsr lower_fixed_stub\n";
   printf {$fh} "    lda #\$%02X\n", $bank;
   print  {$fh} "    cmp expected_source\n";
   printf {$fh} "    beq.same bank%d_fixed_restored\n", $bank;
   print  {$fh} "    lda #\$03\n";
   print  {$fh} "    sta failure\n";
   printf {$fh} "bank%d_fixed_restored:\n", $bank;

   printf {$fh} "bank%d_step_done:\n", $bank;
   print  {$fh} "    tsx\n";
   print  {$fh} "    cpx source_sp\n";
   printf {$fh} "    beq.same bank%d_source_stack_ok\n", $bank;
   print  {$fh} "    lda #\$04\n";
   print  {$fh} "    sta failure\n";
   printf {$fh} "bank%d_source_stack_ok:\n", $bank;
   print  {$fh} "    rts\n";

   # Every target is at the same CPU address. The segment starts at $1000 and
   # this alignment pins the target to $1100 in every lower physical bank.
   print  {$fh} "    .align 256\n";
   printf {$fh} "bank%d_target:\n", $bank;
   print  {$fh} "    lda expected_dest\n";
   printf {$fh} "    cmp #\$%02X\n", $bank;
   printf {$fh} "    beq.same bank%d_target_ok\n", $bank;
   print  {$fh} "    lda #\$01\n";
   print  {$fh} "    sta failure\n";
   printf {$fh} "bank%d_target_ok:\n", $bank;
   print  {$fh} "    inc torture_count\n";
   printf {$fh} "    bne.same bank%d_target_count_ok\n", $bank;
   print  {$fh} "    inc torture_count+1\n";
   printf {$fh} "bank%d_target_count_ok:\n", $bank;
   print  {$fh} "    rts\n";

   if ($link_root) {
      printf {$fh} "bank%d_link_root:\n", $bank;
      print {$fh} "    rts\n";
   }

   if ($bank == 253) {
      print {$fh} "    .align 256\nwait_glyphs:\n";
      emit_bytes($fh, \@wait_font_bytes);
      print {$fh} <<'WAIT_LOADER';
load_wait:
    lda #<{wait_glyphs + 16}
    sta status_result_pointers+0
    lda #>{wait_glyphs + 16}
    sta status_result_pointers+1
    lda #<{wait_glyphs + 32}
    sta status_result_pointers+2
    lda #>{wait_glyphs + 32}
    sta status_result_pointers+3
    lda #<{wait_glyphs + 48}
    sta status_result_pointers+4
    lda #>{wait_glyphs + 48}
    sta status_result_pointers+5
    lda #<{wait_glyphs + 64}
    sta status_result_pointers+6
    lda #>{wait_glyphs + 64}
    sta status_result_pointers+7
    lda #<wait_glyphs
    sta status_result_pointers+8
    lda #>wait_glyphs
    sta status_result_pointers+9
    lda spinner_index
    asl
    asl
    asl
    asl
    clc
    adc #<{wait_glyphs + 80}
    sta status_result_pointers+10
    lda #>{wait_glyphs + 80}
    adc #0
    sta status_result_pointers+11
    rts
WAIT_LOADER
   } elsif ($bank == 254) {
      print {$fh} "    .align 256\nstatus_glyphs:\n";
      emit_bytes($fh, \@status_font_bytes);
      print {$fh} <<'STATUS_LOADERS';
load_pass:
    lda #<status_glyphs
    sta status_result_pointers+0
    lda #>status_glyphs
    sta status_result_pointers+1
    lda #<{status_glyphs + 16}
    sta status_result_pointers+2
    lda #>{status_glyphs + 16}
    sta status_result_pointers+3
    lda #<{status_glyphs + 32}
    sta status_result_pointers+4
    lda #>{status_glyphs + 32}
    sta status_result_pointers+5
    lda #<{status_glyphs + 48}
    sta status_result_pointers+6
    lda #>{status_glyphs + 48}
    sta status_result_pointers+7
    lda #<{status_glyphs + 48}
    sta status_result_pointers+8
    lda #>{status_glyphs + 48}
    sta status_result_pointers+9
    lda #<status_glyphs
    sta status_result_pointers+10
    lda #>status_glyphs
    sta status_result_pointers+11
    rts

load_fail:
    lda #<status_glyphs
    sta status_result_pointers+0
    lda #>status_glyphs
    sta status_result_pointers+1
    lda #<{status_glyphs + 64}
    sta status_result_pointers+2
    lda #>{status_glyphs + 64}
    sta status_result_pointers+3
    lda #<{status_glyphs + 80}
    sta status_result_pointers+4
    lda #>{status_glyphs + 80}
    sta status_result_pointers+5
    lda #<{status_glyphs + 96}
    sta status_result_pointers+6
    lda #>{status_glyphs + 96}
    sta status_result_pointers+7
    lda #<{status_glyphs + 112}
    sta status_result_pointers+8
    lda #>{status_glyphs + 112}
    sta status_result_pointers+9
    lda #<status_glyphs
    sta status_result_pointers+10
    lda #>status_glyphs
    sta status_result_pointers+11
    rts
STATUS_LOADERS
   }
   print {$fh} "\n";
}

sub read_subset_bytes {
   my ($path, $expected_bytes) = @_;
   open my $fh, '<', $path or die "$0: cannot read $path: $!\n";
   my @rows;
   while (my $line = <$fh>) {
      push @rows, $1 if $line =~ /0b([.X01]{8})/;
   }
   close $fh;
   @rows % 16 == 0 or die "$0: $path does not contain 16-row glyphs\n";
   my @bytes;
   while (@rows) {
      my @glyph = splice @rows, 0, 16;
      for my $row (reverse @glyph) {
         $row =~ tr/.X/01/;
         push @bytes, oct("0b$row");
      }
   }
   @bytes == $expected_bytes
      or die "$0: $path contains " . scalar(@bytes) . " bytes; expected $expected_bytes\n";
   return @bytes;
}

sub emit_bytes {
   my ($fh, $bytes) = @_;
   for (my $i = 0; $i < @$bytes; $i += 16) {
      my $last = $i + 15;
      $last = $#$bytes if $last > $#$bytes;
      print {$fh} "    .byte ", join(', ', map { sprintf '$%02X', $_ } @$bytes[$i .. $last]), "\n";
   }
}

@wait_font_bytes = read_subset_bytes("$Bin/wait_font.c26", 144);
@status_font_bytes = read_subset_bytes("$Bin/status_font.c26", 128);

# Split lower banks into independent assembler objects because an O26 object's
# packed CODE namespace uses 16-bit offsets. This is an object-format concern,
# not a cartridge/layout restriction.
my $chunk = 0;
for (my $first = 0; $first < $lower_banks; $first += $banks_per_object) {
   my $last = $first + $banks_per_object - 1;
   $last = $lower_banks - 1 if $last >= $lower_banks;
   my $path = sprintf "%s/3f_max_torture_%02d.s26", $Bin, $chunk++;
   open my $fh, '>', $path or die "$0: cannot write $path: $!\n";
   generated_header($fh, "This object contains lower banks $first through $last.");
   print {$fh} ".import failure, torture_count, expected_source, expected_dest, source_sp, step_remaining\n";
   print {$fh} ".import lower_stub, lower_fixed_stub\n";
   if ($first <= 254 && $last >= 253) {
      print {$fh} ".import status_result_pointers, spinner_index\n";
      print {$fh} ".export load_wait, load_pass, load_fail\n";
   }
   if ($first == 0) {
      print {$fh} ".export bank0_link_root\n";
   } else {
      printf {$fh} ".export bank%d_link_root\n", $first;
   }
   print {$fh} "\n";
   for my $bank ($first .. $last) { emit_bank($fh, $bank, $bank == $first); }
   close $fh or die "$0: close $path: $!\n";
}

my $fixed_path = "$Bin/3f_max_torture_fixed.s26";
open my $fixed, '>', $fixed_path or die "$0: cannot write $fixed_path: $!\n";
generated_header($fixed, "This object contains the fixed-bank scheduler.");
print {$fixed} ".import failure, torture_count, expected_source, expected_dest, fixed_sp\n";
print {$fixed} ".import torture_done, torture_batch, step_remaining\n";
print {$fixed} ".import lower_stub, lower_fixed_stub, fixed_stub\n";
for (my $first = 0; $first < $lower_banks; $first += $banks_per_object) {
   printf {$fixed} ".import bank%d_link_root\n", $first;
}
print {$fixed} ".importzp _vcsc_ptr0\n";
print {$fixed} ".export init_3f_max_torture, step_3f_max_torture, run_3f_max_torture\n\n.segment \"CODE.bank255\"\n\n";

print {$fixed} <<'FIXED';

fixed_probe:
    inc torture_count
    bne.same fixed_probe_count_ok
    inc torture_count+1
fixed_probe_count_ok:
    rts

init_3f_max_torture:
    lda #0
    sta failure
    sta torture_count
    sta torture_count+1
    sta expected_source
    sta expected_dest
    sta torture_done

    ; Force the generic bankcall scratch object into the link so every replicated
    ; trampoline is patched to the actual _vcsc_ptr0 address.
    lda _vcsc_ptr0

    ; lower_stub = JSR $1780 / .word $1100 / .byte destination / RTS
    lda #$20
    sta lower_stub
    lda #<$1780
    sta lower_stub+1
    lda #>$1780
    sta lower_stub+2
    lda #<$1100
    sta lower_stub+3
    lda #>$1100
    sta lower_stub+4
    lda #0
    sta lower_stub+5
    lda #$60
    sta lower_stub+6

    ; lower_fixed_stub uses the lower bank's trampoline but targets fixed ROM.
    lda #$20
    sta lower_fixed_stub
    lda #<$1780
    sta lower_fixed_stub+1
    lda #>$1780
    sta lower_fixed_stub+2
    lda #<fixed_probe
    sta lower_fixed_stub+3
    lda #>fixed_probe
    sta lower_fixed_stub+4
    lda #$ff
    sta lower_fixed_stub+5
    lda #$60
    sta lower_fixed_stub+6

    ; fixed_stub uses the fixed bank's trampoline and targets common lower $1100.
    lda #$20
    sta fixed_stub
    lda #<$1f80
    sta fixed_stub+1
    lda #>$1f80
    sta fixed_stub+2
    lda #<$1100
    sta fixed_stub+3
    lda #>$1100
    sta fixed_stub+4
    lda #0
    sta fixed_stub+5
    lda #$60
    sta fixed_stub+6
    rts

; Execute at most torture_batch target calls, then return to the frame loop.
; Lower-bank state lives in expected_source/expected_dest.  $ff source means
; the lower-bank matrix is complete and the fixed->lower sweep is in progress.
step_3f_max_torture:
    lda torture_done
    bne.same step_return

    lda expected_source
    cmp #$ff
    beq.same fixed_phase

    lda torture_batch
    sta step_remaining
    lda expected_source
    sta $3f
    jsr $1000
    lda expected_dest
    cmp #$ff
    bne.same step_return
    lda #0
    sta expected_dest
    inc expected_source
step_return:
    rts

fixed_phase:
    tsx
    stx fixed_sp
    lda torture_batch
    sta step_remaining
fixed_dest_loop:
    lda expected_dest
    cmp #$ff
    beq.same fixed_done
    sta fixed_stub+5
    jsr fixed_stub
    inc expected_dest
    lda expected_dest
    cmp #$ff
    beq.same fixed_done
    dec step_remaining
    bne.same fixed_dest_loop

fixed_step_return:
    tsx
    cpx fixed_sp
    beq.same step_return
    lda #$05
    sta failure
    rts

fixed_done:
    tsx
    cpx fixed_sp
    beq.same fixed_stack_ok
    lda #$05
    sta failure
fixed_stack_ok:

    ; 255*255 lower calls + 255 lower->fixed + 255 fixed->lower = 65535.
    lda torture_count
    cmp #$ff
    beq.same count_lo_ok
    lda #$06
    sta failure
count_lo_ok:
    lda torture_count+1
    cmp #$ff
    beq.same count_hi_ok
    lda #$07
    sta failure
count_hi_ok:
    lda #1
    sta torture_done
    rts

; Fast path used by the simulator regression: same state machine, maximum batch.
run_3f_max_torture:
    jsr init_3f_max_torture
    lda #$ff
    sta torture_batch
run_torture_loop:
    jsr step_3f_max_torture
    lda torture_done
    beq.same run_torture_loop
    rts
FIXED

# Keep every generated lower-bank object live.  The linker roots assembly
# objects through relocations; these calls are intentionally unreachable at
# runtime but make the fixed scheduler object depend on one exported symbol
# from each 32-bank chunk.
print {$fixed} "\ntorture_object_roots:\n";
for (my $first = 0; $first < $lower_banks; $first += $banks_per_object) {
   printf {$fixed} "    jsr bank%d_link_root\n", $first;
   printf {$fixed} "    .banktarget bank%d_link_root\n", $first;
}
print {$fixed} "    rts\n";

close $fixed or die "$0: close $fixed_path: $!\n";

# Remove obsolete chunk files if the grouping shrinks in the future.
for my $path (glob "$Bin/3f_max_torture_*.s26") {
   next if $path eq $fixed_path;
   next if $path =~ /_\d\d\.s26\z/ && substr($path, -6, 2) < $chunk;
   unlink $path or die "$0: cannot remove stale $path: $!\n";
}
