#!/usr/bin/env perl
# This file is covered under CC0-1.0. See examples/LICENSE.txt.
use strict;
use warnings;
use FindBin qw($Bin);

my $lower_banks = 255;
my $banks_per_object = 32; # O26 CODE offsets are 16-bit; 32 x 2K fits exactly.
my $ram_banks = 32;          # Stella 3E limit: 32 x 1K = 32K.
my $lfsr_seed = 0xACE1;
my $lfsr_tap_mask = 0xB400; # x^16 + x^14 + x^13 + x^11 + 1, Galois/right shift.
my (@wait_font_bytes, @status_font_bytes, @cart_font_bytes);

# Refuse to generate the diagnostic if the chosen 16-bit recurrence is not
# actually maximal.  This also documents the exact stream the cartridge uses.
my $lfsr = $lfsr_seed;
my $period = 0;
do {
   $lfsr = (($lfsr >> 1) ^ (($lfsr & 1) ? $lfsr_tap_mask : 0)) & 0xffff;
   ++$period;
   die "$0: LFSR failed to return to its seed within 65535 steps\n" if $period > 65535;
} while ($lfsr != $lfsr_seed);
die "$0: LFSR period is $period, expected 65535\n" unless $period == 65535;

sub generated_header {
   my ($fh, $detail) = @_;
   print {$fh} "; Generated by make_torture.pl; do not edit.\n";
   print {$fh} "; This file is covered under CC0-1.0. See examples/LICENSE.txt.\n";
   print {$fh} ";\n";
   print {$fh} "; Maximum-size Tigervision 3E torture payload. $detail\n";
   print {$fh} "; Cross-bank calls execute a tiny inline descriptor stub from RIOT RAM so\n";
   print {$fh} "; the full 255 x 255 ordered matrix fits in one 512K cartridge.\n\n";
}

sub emit_bank {
   my ($fh, $bank, $link_root) = @_;
   printf {$fh} ".segmentalign \"CODE.bank%d\", %d\n", $bank, ($bank < $ram_banks) ? 256 : 2048;
   printf {$fh} ".segment \"CODE.bank%d\"\n", $bank;
   printf {$fh} ".export bank%d_source, bank%d_target\n", $bank, $bank if $bank < $ram_banks;
   printf {$fh} "bank%d_source:\n", $bank;
   print  {$fh} "    tsx\n";
   print  {$fh} "    stx source_sp\n";
   printf {$fh} "bank%d_dest_loop:\n", $bank;
   print  {$fh} "    lda expected_dest\n";
   printf {$fh} "    cmp #\$%02X\n", $bank;
   printf {$fh} "    beq.same bank%d_same\n", $bank;
   print  {$fh} "    sta bankcall_stub+5\n";
   print  {$fh} "    jsr bankcall_stub\n";
   printf {$fh} "    jmp bank%d_after\n", $bank;
   printf {$fh} "bank%d_same:\n", $bank;
   printf {$fh} "    jsr bank%d_target\n", $bank;
   printf {$fh} "bank%d_after:\n", $bank;

   # The immediate differs in every physical source bank. If bankreturn restores
   # the wrong bank, execution resumes at the same CPU PC but loads the wrong
   # immediate and this comparison fails.
   printf {$fh} "    lda #\$%02X\n", $bank;
   print  {$fh} "    cmp expected_source\n";
   printf {$fh} "    beq.same bank%d_restored\n", $bank;
   print  {$fh} "    lda #\$02\n";
   print  {$fh} "    sta failure\n";
   printf {$fh} "bank%d_restored:\n", $bank;

   print  {$fh} "    inc expected_dest\n";
   print  {$fh} "    lda expected_dest\n";
   print  {$fh} "    cmp #\$FF\n";
   printf {$fh} "    beq.same bank%d_source_done\n", $bank;
   print  {$fh} "    dec step_remaining\n";
   printf {$fh} "    bne.same bank%d_dest_loop\n", $bank;
   printf {$fh} "    jmp bank%d_step_done\n", $bank;

   printf {$fh} "bank%d_source_done:\n", $bank;
   print  {$fh} "    lda ram_lfsr\n";
   print  {$fh} "    sta bankcall_stub+3\n";
   print  {$fh} "    lda ram_lfsr+1\n";
   print  {$fh} "    sta bankcall_stub+4\n";
   print  {$fh} "    lda #\$ff\n";
   print  {$fh} "    sta bankcall_stub+5\n";
   print  {$fh} "    jsr bankcall_stub\n";
   print  {$fh} "    lda #<\$1100\n";
   print  {$fh} "    sta bankcall_stub+3\n";
   print  {$fh} "    lda #>\$1100\n";
   print  {$fh} "    sta bankcall_stub+4\n";
   printf {$fh} "    lda #\$%02X\n", $bank;
   print  {$fh} "    cmp expected_source\n";
   printf {$fh} "    beq.same bank%d_fixed_restored\n", $bank;
   print  {$fh} "    lda #\$03\n";
   print  {$fh} "    sta failure\n";
   printf {$fh} "bank%d_fixed_restored:\n", $bank;

   printf {$fh} "bank%d_step_done:\n", $bank;
   print  {$fh} "    tsx\n";
   print  {$fh} "    cpx source_sp\n";
   printf {$fh} "    beq.same bank%d_source_stack_ok\n", $bank;
   print  {$fh} "    lda #\$04\n";
   print  {$fh} "    sta failure\n";
   printf {$fh} "bank%d_source_stack_ok:\n", $bank;
   print  {$fh} "    rts\n";

   # Every target is at the same CPU address. The segment starts at $1000 and
   # this alignment pins the target to $1100 in every lower physical bank.
   print  {$fh} "    .align 256\n";
   printf {$fh} "bank%d_target:\n", $bank;
   print  {$fh} "    lda expected_dest\n";
   printf {$fh} "    cmp #\$%02X\n", $bank;
   printf {$fh} "    beq.same bank%d_target_ok\n", $bank;
   print  {$fh} "    lda #\$01\n";
   print  {$fh} "    sta failure\n";
   printf {$fh} "bank%d_target_ok:\n", $bank;
   print  {$fh} "    inc torture_count\n";
   printf {$fh} "    bne.same bank%d_target_count_ok\n", $bank;
   print  {$fh} "    inc torture_count+1\n";
   printf {$fh} "bank%d_target_count_ok:\n", $bank;
   print  {$fh} "    rts\n";

   if ($link_root) {
      printf {$fh} "bank%d_link_root:\n", $bank;
      print {$fh} "    rts\n";
   }

   if ($bank < $ram_banks) {
      print {$fh} "    .align 256\n";
      printf {$fh} ".export bank%d_ram_entry\n", $bank;
      printf {$fh} "bank%d_ram_entry:\n", $bank;
      printf {$fh} "    jsr ram_access_%02d\n", $bank;
      print {$fh} "    rts\n";
   }

   if ($bank == 31) {
      print {$fh} <<'RAM_SCHEDULER';

; Run bounded compiler-managed swapram work from lower ROM bank 31.  Each byte
; calls the fixed ram_compiler_access dispatcher through the normal 3E bankcall
; ABI; that dispatcher in turn enters the selected bank's $1200 C26 wrapper.
step_3e_max_ram:
    lda ram_phase
    cmp #1
    beq.same ram_write_phase
    jmp ram_verify_phase

ram_write_phase:
    lda ram_bank
    cmp #32
    beq.same ram_write_done
    lda torture_batch
    sta step_remaining
ram_write_loop:
    lda ram_lfsr
    sta ram_value
    jsr ram_compiler_access
    .banktarget ram_compiler_access
    jsr lfsr_next
    jsr ram_walk_advance
    bcs.same ram_step_return
    dec step_remaining
    bne.same ram_write_loop
ram_step_return:
    rts

ram_write_done:
    lda #2
    sta ram_phase
    jsr ram_walk_reset
    rts

ram_verify_phase:
    lda ram_bank
    cmp #32
    beq.same ram_verify_done
    lda torture_batch
    sta step_remaining
ram_verify_loop:
    jsr ram_compiler_access
    .banktarget ram_compiler_access
    lda ram_value
    cmp ram_lfsr
    beq.same ram_verify_ok
    lda failure
    bne.same ram_verify_ok
    lda ram_bank
    ora #$80
    sta failure
ram_verify_ok:
    jsr lfsr_next
    jsr ram_walk_advance
    bcs.same ram_step_return
    dec step_remaining
    bne.same ram_verify_loop
    rts

ram_verify_done:
    lda #3
    sta ram_phase
    lda #1
    sta torture_done
    rts

ram_walk_reset:
    lda #0
    sta ram_bank
    sta ram_page
    sta ram_offset
    lda #$e1
    sta ram_lfsr
    lda #$ac
    sta ram_lfsr+1
    rts

; Advance one byte in a 1K compiler-managed swapram object. Carry set means an
; object/bank boundary was reached; the next frame slice starts the next object.
ram_walk_advance:
    inc ram_offset
    bne.same ram_walk_same_bank
    inc ram_page
    lda ram_page
    cmp #4
    bne.same ram_walk_same_bank
    lda #0
    sta ram_page
    inc ram_bank
    sec
    rts
ram_walk_same_bank:
    clc
    rts

; 16-bit maximal Galois LFSR, right shift, polynomial
; x^16 + x^14 + x^13 + x^11 + 1 (tap mask $B400), seed $ACE1.
lfsr_next:
    lda ram_lfsr+1
    lsr
    sta ram_lfsr+1
    lda ram_lfsr
    ror
    sta ram_lfsr
    bcc.same lfsr_done
    lda ram_lfsr+1
    eor #$b4
    sta ram_lfsr+1
lfsr_done:
    rts
RAM_SCHEDULER
   }

   if ($bank == 251) {
      print {$fh} "    .align 256\ncart_type_glyphs:\n";
      emit_bytes($fh, \@cart_font_bytes);
      print {$fh} <<'CART_LOADER';
load_mapper_type:
    lda #<{cart_type_glyphs + 0}
    sta cart_type_pointers+0
    lda #>{cart_type_glyphs + 0}
    sta cart_type_pointers+1
    lda #<{cart_type_glyphs + 8}
    sta cart_type_pointers+2
    lda #>{cart_type_glyphs + 8}
    sta cart_type_pointers+3
    lda #<{cart_type_glyphs + 16}
    sta cart_type_pointers+4
    lda #>{cart_type_glyphs + 16}
    sta cart_type_pointers+5
    lda #<{cart_type_glyphs + 24}
    sta cart_type_pointers+6
    lda #>{cart_type_glyphs + 24}
    sta cart_type_pointers+7
    lda #<{cart_type_glyphs + 32}
    sta cart_type_pointers+8
    lda #>{cart_type_glyphs + 32}
    sta cart_type_pointers+9
    lda #<{cart_type_glyphs + 40}
    sta cart_type_pointers+10
    lda #>{cart_type_glyphs + 40}
    sta cart_type_pointers+11
    rts
CART_LOADER
   }

   # Keep one-time stub setup out of the crowded fixed bank.  It is safe to
   # execute from lower bank 252 because no RAM is selected until much later.
   if ($bank == 252) {
      print {$fh} <<'INIT_LOADER';
init_3e_max_torture:
    lda #0
    sta failure
    sta torture_count
    sta torture_count+1
    sta expected_source
    sta expected_dest
    sta torture_done
    sta ram_phase

    ; Force the generic bankcall scratch object into the link so every replicated
    ; trampoline is patched to the actual _vcsc_ptr0 address.
    lda _vcsc_ptr0

    ; One shared runtime stub serves lower->lower, lower->fixed, and later
    ; fixed->lower calls.  Source-bank code temporarily patches target/dest for
    ; its fixed probe and restores $1100 before returning.
    lda #$20
    sta bankcall_stub
    lda #<$1780
    sta bankcall_stub+1
    lda #>$1780
    sta bankcall_stub+2
    lda #<$1100
    sta bankcall_stub+3
    lda #>$1100
    sta bankcall_stub+4
    lda #0
    sta bankcall_stub+5
    lda #$60
    sta bankcall_stub+6
    rts

; Unreachable link roots keep the first seven generated lower-bank objects live.
torture_object_roots:
    jsr bank0_link_root
    .banktarget bank0_link_root
    jsr bank32_link_root
    .banktarget bank32_link_root
    jsr bank64_link_root
    .banktarget bank64_link_root
    jsr bank96_link_root
    .banktarget bank96_link_root
    jsr bank128_link_root
    .banktarget bank128_link_root
    jsr bank160_link_root
    .banktarget bank160_link_root
    jsr bank192_link_root
    .banktarget bank192_link_root
    rts
INIT_LOADER
   }

   if ($bank == 253) {
      print {$fh} "    .align 256\nwait_glyphs:\n";
      emit_bytes($fh, \@wait_font_bytes);
      print {$fh} <<'WAIT_LOADER';
load_wait:
    lda #<{wait_glyphs + 16}
    sta status_result_pointers+0
    lda #>{wait_glyphs + 16}
    sta status_result_pointers+1
    lda #<{wait_glyphs + 32}
    sta status_result_pointers+2
    lda #>{wait_glyphs + 32}
    sta status_result_pointers+3
    lda #<{wait_glyphs + 48}
    sta status_result_pointers+4
    lda #>{wait_glyphs + 48}
    sta status_result_pointers+5
    lda #<{wait_glyphs + 64}
    sta status_result_pointers+6
    lda #>{wait_glyphs + 64}
    sta status_result_pointers+7
    lda #<wait_glyphs
    sta status_result_pointers+8
    lda #>wait_glyphs
    sta status_result_pointers+9
    lda spinner_index
    asl
    asl
    asl
    asl
    clc
    adc #<{wait_glyphs + 80}
    sta status_result_pointers+10
    lda #>{wait_glyphs + 80}
    adc #0
    sta status_result_pointers+11
    rts
WAIT_LOADER
   } elsif ($bank == 254) {
      print {$fh} "    .align 256\nstatus_glyphs:\n";
      emit_bytes($fh, \@status_font_bytes);
      print {$fh} <<'STATUS_LOADERS';
load_pass:
    lda #<status_glyphs
    sta status_result_pointers+0
    lda #>status_glyphs
    sta status_result_pointers+1
    lda #<{status_glyphs + 16}
    sta status_result_pointers+2
    lda #>{status_glyphs + 16}
    sta status_result_pointers+3
    lda #<{status_glyphs + 32}
    sta status_result_pointers+4
    lda #>{status_glyphs + 32}
    sta status_result_pointers+5
    lda #<{status_glyphs + 48}
    sta status_result_pointers+6
    lda #>{status_glyphs + 48}
    sta status_result_pointers+7
    lda #<{status_glyphs + 48}
    sta status_result_pointers+8
    lda #>{status_glyphs + 48}
    sta status_result_pointers+9
    lda #<status_glyphs
    sta status_result_pointers+10
    lda #>status_glyphs
    sta status_result_pointers+11
    rts

load_fail:
    lda #<status_glyphs
    sta status_result_pointers+0
    lda #>status_glyphs
    sta status_result_pointers+1
    lda #<{status_glyphs + 64}
    sta status_result_pointers+2
    lda #>{status_glyphs + 64}
    sta status_result_pointers+3
    lda #<{status_glyphs + 80}
    sta status_result_pointers+4
    lda #>{status_glyphs + 80}
    sta status_result_pointers+5
    lda #<{status_glyphs + 96}
    sta status_result_pointers+6
    lda #>{status_glyphs + 96}
    sta status_result_pointers+7
    lda #<{status_glyphs + 112}
    sta status_result_pointers+8
    lda #>{status_glyphs + 112}
    sta status_result_pointers+9
    lda #<status_glyphs
    sta status_result_pointers+10
    lda #>status_glyphs
    sta status_result_pointers+11
    rts
STATUS_LOADERS
   }
   print {$fh} "\n";
}

sub read_subset_bytes {
   my ($path, $expected_bytes, $rows_per_glyph) = @_;
   $rows_per_glyph //= 16;
   open my $fh, '<', $path or die "$0: cannot read $path: $!\n";
   my @rows;
   while (my $line = <$fh>) {
      push @rows, $1 if $line =~ /0b([.X01]{8})/;
   }
   close $fh;
   @rows % $rows_per_glyph == 0 or die "$0: $path does not contain complete $rows_per_glyph-row glyphs\n";
   my @bytes;
   while (@rows) {
      my @glyph = splice @rows, 0, $rows_per_glyph;
      for my $row (reverse @glyph) {
         $row =~ tr/.X/01/;
         push @bytes, oct("0b$row");
      }
   }
   @bytes == $expected_bytes
      or die "$0: $path contains " . scalar(@bytes) . " bytes; expected $expected_bytes\n";
   return @bytes;
}

sub emit_bytes {
   my ($fh, $bytes) = @_;
   for (my $i = 0; $i < @$bytes; $i += 16) {
      my $last = $i + 15;
      $last = $#$bytes if $last > $#$bytes;
      print {$fh} "    .byte ", join(', ', map { sprintf '$%02X', $_ } @$bytes[$i .. $last]), "\n";
   }
}

@wait_font_bytes = read_subset_bytes("$Bin/wait_font.c26", 144, 16);
@status_font_bytes = read_subset_bytes("$Bin/status_font.c26", 128, 16);
@cart_font_bytes = read_subset_bytes("$Bin/cart_type_font.c26", 48, 8);

# Split lower banks into independent assembler objects because an O26 object's
# packed CODE namespace uses 16-bit offsets. This is an object-format concern,
# not a cartridge/layout restriction.
my $chunk = 0;
for (my $first = 0; $first < $lower_banks; $first += $banks_per_object) {
   my $last = $first + $banks_per_object - 1;
   $last = $lower_banks - 1 if $last >= $lower_banks;
   my $path = sprintf "%s/3e_max_torture_%02d.s26", $Bin, $chunk++;
   open my $fh, '>', $path or die "$0: cannot write $path: $!\n";
   generated_header($fh, "This object contains lower banks $first through $last.");
   print {$fh} ".import failure, torture_count, expected_source, expected_dest, source_sp, step_remaining\n";
   print {$fh} ".import torture_done, torture_batch, ram_phase, ram_bank, ram_page, ram_offset, ram_value\n";
   print {$fh} ".import bankcall_stub, ram_lfsr\n";
   if ($first == 0) {
      for my $bank (0 .. $ram_banks - 1) {
         printf {$fh} ".import ram_access_%02d\n", $bank;
      }
   }
   if ($first <= 254 && $last >= 253) {
      print {$fh} ".import status_result_pointers, spinner_index\n";
      print {$fh} ".export load_wait, load_pass, load_fail\n";
   }
   if ($first <= 251 && $last >= 251) {
      print {$fh} ".import cart_type_pointers\n";
      print {$fh} ".export load_mapper_type\n";
   }
   if ($first <= 252 && $last >= 252) {
      print {$fh} ".import ram_phase, torture_done\n";
      for (my $root = 0; $root < 224; $root += $banks_per_object) {
         printf {$fh} ".import bank%d_link_root\n", $root;
      }
      print {$fh} ".importzp _vcsc_ptr0\n";
      print {$fh} ".export init_3e_max_torture\n";
   }
   if ($first == 0) {
      print {$fh} ".import ram_compiler_access\n";
      print {$fh} ".export bank0_link_root, step_3e_max_ram, ram_walk_reset\n";
   } else {
      printf {$fh} ".export bank%d_link_root\n", $first;
   }
   print {$fh} "\n";
   for my $bank ($first .. $last) { emit_bank($fh, $bank, $bank == $first); }
   close $fh or die "$0: close $path: $!\n";
}

my $fixed_path = "$Bin/3e_max_torture_fixed.s26";
open my $fixed, '>', $fixed_path or die "$0: cannot write $fixed_path: $!\n";
generated_header($fixed, "This object contains the fixed-bank ROM scheduler and compiler-swapram driver.");
print {$fixed} ".import failure, torture_count, expected_source, expected_dest, fixed_sp\n";
print {$fixed} ".import torture_done, torture_batch, step_remaining\n";
print {$fixed} ".import ram_phase, ram_bank, ram_page, ram_offset, ram_value, ram_lfsr\n";
print {$fixed} ".import bankcall_stub\n";
print {$fixed} ".import step_3e_max_ram, ram_walk_reset\n";
print {$fixed} ".export fixed_probe, finish_3e_max_init, step_3e_max_torture, ram_compiler_access\n\n.segment \"CODE.bank255\"\n\n";

print {$fixed} <<'FIXED';

.segment "CODE.bank255.fixed_probe"
fixed_probe:
    inc torture_count
    bne.same fixed_probe_count_ok
    inc torture_count+1
fixed_probe_count_ok:
    rts

; The lower banks cannot directly relocate against a fixed-bank symbol without
; coupling their placement.  Cache the fixed probe address in ram_lfsr while
; the ROM phase runs; ram_walk_reset replaces it with $ACE1 before RAM testing.
.segment "CODE.bank255.finish_init"
finish_3e_max_init:
    lda #<fixed_probe
    sta ram_lfsr
    lda #>fixed_probe
    sta ram_lfsr+1
    rts

; Execute bounded work, then return to the frame loop.  The complete ROM
; matrix stays in fixed ROM.  RAM work lives in lower bank31 so the fixed 2K
; retains room for the compiler-selected 3E swapram helper.
.segment "CODE.bank255.rom_scheduler"
step_3e_max_torture:
    lda torture_done
    bne.same step_return
    lda ram_phase
    beq.same rom_phase
    jsr step_3e_max_ram
    .banktarget step_3e_max_ram
step_return:
    rts

rom_phase:
    lda expected_source
    cmp #$ff
    beq.same fixed_phase

    lda torture_batch
    sta step_remaining
    lda expected_source
    sta $3f
    jsr $1000
    lda expected_dest
    cmp #$ff
    bne.same step_return
    lda #0
    sta expected_dest
    inc expected_source
    rts

fixed_phase:
    ; The lower-bank matrix is complete. Reuse the one RAM stub from fixed ROM.
    lda #<$1f80
    sta bankcall_stub+1
    lda #>$1f80
    sta bankcall_stub+2
    lda #<$1100
    sta bankcall_stub+3
    lda #>$1100
    sta bankcall_stub+4
    tsx
    stx fixed_sp
    lda torture_batch
    sta step_remaining
fixed_dest_loop:
    lda expected_dest
    cmp #$ff
    beq.same fixed_done
    sta bankcall_stub+5
    jsr bankcall_stub
    inc expected_dest
    lda expected_dest
    cmp #$ff
    beq.same fixed_done
    dec step_remaining
    bne.same fixed_dest_loop

fixed_step_return:
    tsx
    cpx fixed_sp
    beq.same step_return
    lda #$05
    sta failure
    rts

fixed_done:
    tsx
    cpx fixed_sp
    beq.same fixed_stack_ok
    lda #$05
    sta failure
fixed_stack_ok:

    ; 255*255 lower calls + 255 lower->fixed + 255 fixed->lower = 65535.
    lda torture_count
    cmp #$ff
    beq.same count_lo_ok
    lda #$06
    sta failure
count_lo_ok:
    lda torture_count+1
    cmp #$ff
    beq.same count_hi_ok
    lda #$07
    sta failure
count_hi_ok:
    lda #1
    sta ram_phase
    jsr ram_walk_reset
    .banktarget ram_walk_reset
    rts

; Fixed-ROM bridge used by bank31's RAM scheduler.  This dynamic call starts
; from the fixed trampoline copy, selects the RAM object's matching lower ROM
; bank, and enters its $1200 wrapper.  That wrapper calls C26 ram_access_N(),
; whose ordinary swapram lvalue is compiler-lowered through swapram_read1 or
; swapram_write1 in this same fixed bank.
.segment "CODE.bank255.ram_dispatch"
ram_compiler_access:
    lda #<$1200
    sta bankcall_stub+3
    lda #>$1200
    sta bankcall_stub+4
    lda ram_bank
    sta bankcall_stub+5
    lda #<$1f80
    sta bankcall_stub+1
    lda #>$1f80
    sta bankcall_stub+2
    jsr bankcall_stub
    rts

FIXED

close $fixed or die "$0: close $fixed_path: $!\n";

# Remove obsolete chunk files if the grouping shrinks in the future.
for my $path (glob "$Bin/3e_max_torture_*.s26") {
   next if $path eq $fixed_path;
   next if $path =~ /_\d\d\.s26\z/ && substr($path, -6, 2) < $chunk;
   unlink $path or die "$0: cannot remove stale $path: $!\n";
}
