#!/usr/bin/perl
# This file is covered under CC0-1.0. See examples/LICENSE.txt.
use strict;
use warnings;

@ARGV == 1 or die "usage: $0 half_ascii.c26\n";
my $path = $ARGV[0];
open my $fh, '<', $path or die "read $path: $!\n";

my %glyph;
my $code;
while (my $line = <$fh>) {
   if ($line =~ m{//\s*0x([0-9A-Fa-f]{2})\b}) {
      $code = hex($1);
      next;
   }
   next unless defined $code && $code >= ord('A') && $code <= ord('O');
   next unless $line =~ /\bVCS_FONT_GLYPH\s*\(/;

   my @rows;
   while (my $row = <$fh>) {
      last if $row =~ /^\s*\)/;
      push @rows, $1 if $row =~ /0b([.X]+)/;
   }
   @rows == 6 or die sprintf("%s: glyph %c must have six rows\n", $path, $code);
   for my $row (@rows) {
      length($row) == 4 or die sprintf("%s: glyph %c must be four pixels wide\n", $path, $code);
   }
   $rows[5] eq '....' or die sprintf("%s: glyph %c bottom row must be blank for collision underline\n", $path, $code);
   $glyph{chr($code)} = [ map { ".${_}." } @rows ];
   undef $code;
}
close $fh;

for my $letter ('A'..'O') {
   exists $glyph{$letter} or die "$path: missing glyph $letter\n";
}

my @top = ('A'..'H');
my @bottom = ('I'..'O', 'PASS');
my @pass_rows = (
   '......',
   '.....X',
   '....X.',
   'X..X..',
   '.XX...',
   '......',
);

sub icon_rows {
   my ($name, $active) = @_;
   if ($name eq 'PASS') {
      return $active ? @pass_rows : (('......') x 6);
   }
   my @rows = @{$glyph{$name}};
   $rows[5] = 'XXXXXX' if $active;
   return @rows;
}

sub emit_font {
   my ($symbol, $icons, $label) = @_;
   print "bank3 page const uint8_t $symbol\[144\] := {\n";
   for my $chunk (0..5) {
      my ($left_icon,$right_icon) = $chunk < 3
         ? ($chunk, $chunk+1)
         : ($chunk+1, $chunk+2);
      for my $state (0..3) {
         my @icon_bits;
         for my $i (0..7) {
            my $active = 0;
            $active = ($state >> 1) & 1 if $i == $left_icon;
            $active = $state & 1 if $i == $right_icon;
            push @icon_bits, [ icon_rows($icons->[$i], $active) ];
         }
         my @bytes;
         for my $r (0..5) {
            my $line = join('', map { $_->[$r] } @icon_bits);
            my $byte = substr($line, $chunk*8, 8);
            push @bytes, $byte;
         }
         my $offset = $chunk*24 + $state*6;
         print "   // $label chunk $chunk state $state, offset $offset\n";
         # six_glyph_component draws row index 5 first, so store bottom-to-top.
         for my $r (reverse 0..5) {
            print "   0b$bytes[$r]";
            print "," unless $chunk == 5 && $state == 3 && $r == 0;
            print "\n";
         }
      }
   }
   print "};\n\n";
}

print <<'HDR';
// This file is covered under CC0-1.0. See examples/LICENSE.txt.
// Generated by make_collision_font.pl from libraries/vcs/fonts/half_ascii.c26.
// Do not hand-edit this generated file; edit half_ascii.c26 instead.
//
// Fifteen collision latches are labeled A through O.  Each label occupies a
// six-pixel cell containing a centered four-pixel Half-font letter.  A latched
// collision adds a six-pixel underline without obscuring the letter.
//
// Legend / TIA collision-register bit order:
// top:    A=M0-P1 B=M0-P0 C=M1-P0 D=M1-P1 E=P0-PF F=P0-BL G=P1-PF H=P1-BL
// bottom: I=M0-PF J=M0-BL K=M1-PF L=M1-BL M=BL-PF N=P0-P1 O=M0-M1 CHECK

HDR

emit_font('diagnostic_collision_top_font', \@top, 'top');
emit_font('diagnostic_collision_bottom_font', \@bottom, 'bottom');
print "bank3 const uint8_t diagnostic_collision_window_a[16] := {\n   " . join(',', map { ((($_ >> 2) & 3) * 6) } 0..15) . "\n};\n";
print "bank3 const uint8_t diagnostic_collision_window_b[16] := {\n   " . join(',', map { ((($_ >> 1) & 3) * 6) } 0..15) . "\n};\n";
print "bank3 const uint8_t diagnostic_collision_window_c[16] := {\n   " . join(',', map { (($_ & 3) * 6) } 0..15) . "\n};\n";
