#!/usr/bin/perl

use strict;
use warnings;
use Cwd qw(abs_path);
use Digest::SHA qw(sha256_hex);
use File::Basename qw(dirname);
use File::Path qw(make_path);
use File::Spec;
use Getopt::Long qw(GetOptions);

sub usage {
   die "usage: $0 [--check] [--output-dir DIR]\n";
}

my $check = 0;
my $output_dir;
GetOptions(
   'check'        => \$check,
   'output-dir=s' => \$output_dir,
) or usage();
usage() if @ARGV;

my $script = abs_path($0) // die "could not resolve $0\n";
my $profile = dirname($script);
my $vcs = abs_path(File::Spec->catdir($profile, '..', '..'))
   // die "could not resolve VCS library directory\n";
my $legacy = File::Spec->catdir($vcs, 'legacy-basic-kernels');
$output_dir = defined($output_dir) ? $output_dir : $profile;
make_path($output_dir) if !$check && !-d $output_dir;

my %input = (
   macro    => File::Spec->catfile($legacy, 'common', 'macro.h'),
   header   => File::Spec->catfile($legacy, 'common', '2600basic.h'),
   score    => File::Spec->catfile($legacy, 'common', 'score_graphics.asm'),
   overscan => File::Spec->catfile($legacy, 'standard', 'std_overscan.asm'),
   kernel   => File::Spec->catfile($legacy, 'standard', 'std_kernel.asm'),
);

sub slurp {
   my ($path) = @_;
   open(my $fh, '<:raw', $path) or die "could not open $path: $!\n";
   local $/;
   my $text = <$fh>;
   close($fh) or die "could not close $path: $!\n";
   $text = '' if !defined($text);
   $text =~ s/\r\n?/\n/g;
   return $text;
}

my %text = map { $_ => slurp($input{$_}) } keys %input;

sub require_source {
   my ($which, $re, $why) = @_;
   $text{$which} =~ $re or die "$input{$which}: retained source no longer matches $why\n";
}

# Fail loudly if the selected retained-source relationships change.  This is a
# deliberately narrow normalizer, not a general DASM compatibility layer.
for my $name (qw(SLEEP VERTICAL_SYNC CLEAN_START SET_POINTER)) {
   require_source('macro', qr/^\s*MAC\s+\Q$name\E\b/im, "the $name macro");
}
require_source('header', qr/^\s*MAC\s+RETURN\b/im, 'the RETURN macro');
require_source('header', qr/^pfwidth\s*=\s*4\b/im, 'the default pfwidth=4 relationship');
require_source('header', qr/^pfadjust\s*=\s*0\b/im, 'the default pfadjust=0 relationship');
require_source('header', qr/^playfield\s*=\s*playfieldbase\b/im, 'the default playfield base relationship');
require_source('overscan', qr/^drawscreen\b/m, 'the drawscreen entry');
require_source('kernel', qr/^kernel\b/m, 'the non-reflected kernel entry');
require_source('kernel', qr/^\s*RETURN\s*$/m, 'the selected kernel return');
require_source('score', qr/^scoretable\b/m, 'the default score table');

sub source_rel {
   my ($path) = @_;
   my $rel = File::Spec->abs2rel($path, $vcs);
   $rel =~ s!\\!/!g;
   return $rel;
}

sub generated_header {
   my ($purpose) = @_;
   my @lines = (
      '; Generated by kernels/standard_4k_ntsc/normalize.pl.',
      '; Do not edit this file by hand; edit the normalizer or retained source.',
      ';',
      "; $purpose",
      '; Selected profile: NTSC, unbanked 4K, non-reflected standard kernel,',
      '; default asymmetric playfield, default decimal score, no optional hooks.',
      ';',
      '; Retained input SHA-256:',
   );
   for my $key (qw(macro header overscan kernel score)) {
      push @lines, sprintf(';   %s  %s', sha256_hex($text{$key}), source_rel($input{$key}));
   }
   push @lines, '';
   return join("\n", @lines);
}

sub macro_output {
   return generated_header('Deliberate vcsc-as ports of the five retained DASM macros.') . <<'ASM';
; SLEEP duration -- exact cycle delay, duration > 1.
; With --illegals, an odd delay begins with the exact three-cycle $04,$00
; zero-page NOP.  NO_ILLEGAL_OPCODES selects the retained BIT VSYNC fallback.
MACRO SLEEP duration
   .if duration < 2
      .error "MACRO ERROR: 'SLEEP': Duration must be > 1"
   .endif
   .if duration & 1
      .ifndef NO_ILLEGAL_OPCODES
         NOP.z $00
      .else
         BIT VSYNC
      .endif
      .repeat {duration - 3} / 2
         NOP
      .endrepeat
   .else
      .repeat duration / 2
         NOP
      .endrepeat
   .endif
ENDM

; VERTICAL_SYNC -- retained three-scanline vertical-sync sequence.
MACRO VERTICAL_SYNC
   LDA #$02
   STA WSYNC
   STA VSYNC
   STA WSYNC
   STA WSYNC
   LSR
   STA WSYNC
   STA VSYNC
ENDM

; CLEAN_START -- retained reset-time TIA/RAM/stack clearing sequence.
MACRO CLEAN_START
   SEI
   CLD
   LDX #0
   TXA
   TAY
@clear_stack:
   DEX
   TXS
   PHA
   BNE @clear_stack
ENDM

; SET_POINTER pointer,address -- load an absolute 16-bit address.
MACRO SET_POINTER pointer,address
   LDA #<{address}
   STA pointer
   LDA #>{address}
   STA pointer + 1
ENDM

; RETURN -- ordinary RTS in this deliberately unbanked profile.  The retained
; conditional remains explicit so accidentally defining bankswitch fails at
; assembly time rather than silently selecting an unsupported trampoline.
MACRO RETURN
   .ifdef bankswitch
      .error "standard_4k_ntsc RETURN does not support bankswitch"
   .else
      RTS
   .endif
ENDM
ASM
}

my %defined = (
   pfwidth  => 4,
   pfadjust => 0,
);

sub eval_selected_expr {
   my ($expr, $path, $line_no) = @_;
   my $work = $expr;
   $work =~ s/\$([0-9A-Fa-f]+)/0x$1/g;
   $work =~ s/(?<![<>=!])=(?!=)/==/g;
   $work =~ s/&&/ and /g;
   $work =~ s/\|\|/ or /g;
   my %names = map { $_ => 1 } ($work =~ /\b([A-Za-z_][A-Za-z0-9_]*)\b/g);
   for my $name (keys %names) {
      next if $name eq 'and' || $name eq 'or';
      exists($defined{$name})
         or die "$path:$line_no: cannot normalize selected conditional with unknown symbol '$name': $expr\n";
      $work =~ s/\b\Q$name\E\b/$defined{$name}/g;
   }
   $work =~ /\A[\s0-9xa-fA-F()+\-*\/&|!<>=.andor]+\z/
      or die "$path:$line_no: unsupported selected conditional expression: $expr\n";
   my $value = eval $work; ## no critic (BuiltinFunctions::ProhibitStringyEval)
   die "$path:$line_no: could not evaluate selected conditional '$expr': $@\n" if $@;
   return $value ? 1 : 0;
}

sub selected_lines {
   my ($path, $content) = @_;
   my @out;
   my @stack;
   my $active = 1;
   my @lines = split(/\n/, $content, -1);
   for (my $i = 0; $i < @lines; ++$i) {
      my $line = $lines[$i];
      my $line_no = $i + 1;
      my $trim = $line;
      $trim =~ s/^\s+//;
      $trim =~ s/\s+$//;

      if ($trim =~ /^ifconst\s+([A-Za-z_.\$][A-Za-z0-9_.\$]*)\b/i) {
         my $cond = exists($defined{$1}) ? 1 : 0;
         push @stack, { parent => $active, cond => $cond, dynamic => 0, else => 0 };
         $active = $active && $cond;
         next;
      }
      if ($trim =~ /^ifnconst\s+([A-Za-z_.\$][A-Za-z0-9_.\$]*)\b/i) {
         my $cond = exists($defined{$1}) ? 0 : 1;
         push @stack, { parent => $active, cond => $cond, dynamic => 0, else => 0 };
         $active = $active && $cond;
         next;
      }
      if ($trim =~ /^if\s+(.+)$/i) {
         my $expr = $1;
         if ($expr =~ /\*/) {
            push @stack, { parent => $active, cond => 1, dynamic => 1, else => 0 };
            push @out, [ $line_no, $line ] if $active;
         } else {
            my $cond = $active ? eval_selected_expr($expr, $path, $line_no) : 0;
            push @stack, { parent => $active, cond => $cond, dynamic => 0, else => 0 };
            $active = $active && $cond;
         }
         next;
      }
      if ($trim =~ /^else\b/i) {
         @stack or die "$path:$line_no: ELSE without IF\n";
         my $frame = $stack[-1];
         $frame->{else} and die "$path:$line_no: duplicate ELSE\n";
         $frame->{else} = 1;
         if ($frame->{dynamic}) {
            push @out, [ $line_no, $line ] if $frame->{parent};
            $active = $frame->{parent};
         } else {
            $active = $frame->{parent} && !$frame->{cond};
         }
         next;
      }
      if ($trim =~ /^endif\b/i) {
         @stack or die "$path:$line_no: ENDIF without IF\n";
         my $frame = pop @stack;
         push @out, [ $line_no, $line ] if $frame->{dynamic} && $frame->{parent};
         $active = $frame->{parent};
         next;
      }

      push @out, [ $line_no, $line ] if $active;
   }
   @stack and die "$path: unterminated retained conditional\n";
   return \@out;
}

my %symbol = (
   player0x       => 'vcs_standard_object_x + 0',
   player1x       => 'vcs_standard_object_x + 1',
   missile0x      => 'vcs_standard_object_x + 2',
   missile1x      => 'vcs_standard_object_x + 3',
   ballx          => 'vcs_standard_object_x + 4',
   player0y       => 'vcs_standard_player0_y',
   player1y       => 'vcs_standard_player1_y',
   missile1height => 'vcs_standard_missile1_height',
   missile1y      => 'vcs_standard_missile1_y',
   bally          => 'vcs_standard_ball_y',
   player0pointer => 'vcs_standard_player0_graphics',
   player1pointer => 'vcs_standard_player1_graphics',
   player0height  => 'vcs_standard_player0_height',
   player1height  => 'vcs_standard_player1_height',
   missile0height => 'vcs_standard_missile0_height',
   missile0y      => 'vcs_standard_missile0_y',
   ballheight     => 'vcs_standard_ball_height',
   score          => 'vcs_standard_score',
   scorepointers  => 'vcs_standard_pointer_workspace',
   temp1          => 'vcs_standard_pointer_workspace + 6',
   temp2          => 'vcs_standard_pointer_workspace + 7',
   temp3          => 'vcs_standard_pointer_workspace + 8',
   temp4          => 'vcs_standard_pointer_workspace + 9',
   temp5          => 'vcs_standard_pointer_workspace + 10',
   temp6          => 'vcs_standard_pointer_workspace + 11',
   scorecolor     => 'vcs_standard_score_color',
   playfield      => 'vcs_standard_playfield',
   playfieldpos   => 'vcs_standard_playfield_position',
   stack1         => 'vcs_standard_kernel_scratch + 0',
   stack2         => 'vcs_standard_kernel_scratch + 1',
   PF1L           => 'PF1',
   PF2L           => 'PF2',
   PF1R           => 'PF1',
   PF2R           => 'PF2',
   pfwidth        => '4',
   pfadjust       => '0',
   scoretable     => 'vcs_standard_score_table',
);

sub collect_labels {
   my (@sets) = @_;
   my %labels;
   for my $set (@sets) {
      for my $item (@$set) {
         my ($line_no, $line) = @$item;
         next if $line =~ /^\s/ || $line =~ /^\s*[;#]/ || $line =~ /^\s*$/;
         if ($line =~ /^([.]?[A-Za-z_][A-Za-z0-9_]*)\b/) {
            my $name = $1;
            next if lc($name) eq 'drawscreen';
            $labels{$name} = '@' . ($name =~ s/^\.//r);
         }
      }
   }
   return %labels;
}

sub translate_dynamic_control {
   my ($line) = @_;
   my $trim = $line;
   $trim =~ s/^\s+//;
   $trim =~ s/\s+$//;
   return '.if {<*} > $e9 && {<*} < $fa' if lc($trim) eq 'if ((<*)>$e9)&&((<*)<$fa)';
   return '.if {<*} > $d5' if lc($trim) eq 'if ((<*)>$d5)';
   return '.if {<*} > $d4' if lc($trim) eq 'if ((<*)>$d4)';
   return '.else' if lc($trim) eq 'else';
   return '.endif' if lc($trim) eq 'endif';
   return undef;
}

sub translate_line {
   my ($line, $labels) = @_;

   # Preserve retained comments byte-for-byte.  Normalization applies only to
   # active assembly text so prose cannot accidentally acquire renamed labels,
   # module symbols, or opcode spellings.
   my ($code, $comment) = $line =~ /\A([^;]*)(;.*)?\z/s;
   $comment = '' if !defined($comment);

   my $dynamic = translate_dynamic_control($code);
   return '   ' . $dynamic . $comment if defined($dynamic);

   $code =~ s/^\s*repeat\s+\(\$fa-\(<\*\)\)\s*$/   .repeat {\$fa - {<*}}/i;
   $code =~ s/^\s*repend\s*$/   .endrepeat/i;
   $code =~ s/^\s*align\s+(.+?)\s*$/'   .align ' . $1/ie;

   # DASM uses parentheses for arithmetic grouping; the selected source has one
   # such non-addressing expression after conditional reduction.
   $code =~ s/\(4-pfwidth\)/{4-pfwidth}/g;

   # Forced-wide DASM suffixes become the exact vcsc-as addressing family.
   while ($code =~ /\b([A-Za-z][A-Za-z0-9]*)\.w\b/) {
      my $mn = $1;
      my $suffix = $code =~ /,\s*[Xx]\b/ ? '.ax' :
                   $code =~ /,\s*[Yy]\b/ ? '.ay' : '.a';
      $code =~ s/\b\Q$mn\E\.w\b/$mn$suffix/;
   }

   # Macro identifiers are case-sensitive in vcsc-as; canonicalize the five
   # retained invocations without touching comments.
   for my $macro (qw(SLEEP VERTICAL_SYNC CLEAN_START SET_POINTER RETURN)) {
      $code =~ s/\b\Q$macro\E\b/$macro/ig;
   }

   # Preserve the retained SBX and ASR spellings.  vcsc-as names both aliases
   # directly in illegals.cfg, so normalization need not rewrite mnemonics.

   # Rename every retained internal label into the procedure-local namespace.
   for my $old (sort { length($b) <=> length($a) } keys %$labels) {
      my $new = $labels->{$old};
      $code =~ s/(?<![A-Za-z0-9_.\$@])\Q$old\E(?![A-Za-z0-9_.\$])/$new/g;
   }

   # Bind old fixed-map names directly to source-module symbols and offsets.
   for my $old (sort { length($b) <=> length($a) } keys %symbol) {
      my $new = $symbol{$old};
      $code =~ s/(?<![A-Za-z0-9_.\$@])\Q$old\E(?![A-Za-z0-9_.\$])/$new/g;
   }

   # DASM accepts a bare symbol in column zero as a label definition; vcsc-as
   # uses the conventional trailing colon.
   $code =~ s/^(@[A-Za-z_][A-Za-z0-9_]*)\s*$/$1:/;

   return $code . $comment;
}

sub translate_source_set {
   my ($set, $labels) = @_;
   my @translated;
   for (my $i = 0; $i < @$set; ++$i) {
      my ($line_no, $line) = @{$set->[$i]};
      if ($line =~ /^\s*repeat\s+\(\$fa-\(<\*\)\)\s*$/i) {
         $i + 2 < @$set
            or die "retained source:$line_no: incomplete page-tail repeat block\n";
         my ($nop_no, $nop) = @{$set->[$i + 1]};
         my ($end_no, $end) = @{$set->[$i + 2]};
         $nop =~ /^\s*nop\s*(?:;.*)?$/i
            or die "retained source:$nop_no: expected NOP inside page-tail repeat\n";
         $end =~ /^\s*repend\s*$/i
            or die "retained source:$end_no: expected REPEND after page-tail repeat\n";

         # vcsc-as expands .repeat before layout, so a repeat count based on the
         # current address cannot resolve there.  The retained range can require
         # at most 16 one-byte NOPs ($EA..$F9 -> $FA); spell those candidates out
         # as layout-time conditions without changing the resulting bytes.
         push @translated, '   ; Explicit layout-time equivalent of REPEAT ($fa-(<*)).';
         for (1 .. 16) {
            push @translated, '   .if {<*} < $fa';
            push @translated, '      NOP';
            push @translated, '   .endif';
         }
         $i += 2;
         next;
      }
      push @translated, translate_line($line, $labels);
   }
   return @translated;
}

sub extract_score_bytes {
   my @bytes;
   my $after = 0;
   for my $line (split(/\n/, $text{score})) {
      if (!$after) {
         $after = 1 if $line =~ /^scoretable\b/;
         next;
      }
      if ($line =~ /^\s*\.byte\s+(%[01]+)\s*(?:;.*)?$/i) {
         push @bytes, $1;
         last if @bytes == 88;
      }
   }
   @bytes == 88 or die "$input{score}: expected 88 default score-table bytes, found " . scalar(@bytes) . "\n";
   return @bytes;
}

sub kernel_output {
   my $overscan = selected_lines($input{overscan}, $text{overscan});
   my $kernel = selected_lines($input{kernel}, $text{kernel});
   my %labels = collect_labels($overscan, $kernel);

   my @out;
   push @out, split(/\n/, generated_header('Mechanically normalized source for the selected standard kernel.'));
   push @out, '.include "standard_4k_ntsc_macros.inc"';
   push @out, '';
   push @out, '; Module-owned state imported from standard_4k_ntsc.c26.';
   for my $name (qw(
      vcs_standard_object_x
      vcs_standard_player0_y
      vcs_standard_player1_y
      vcs_standard_missile1_height
      vcs_standard_missile1_y
      vcs_standard_ball_y
      vcs_standard_player0_graphics
      vcs_standard_player1_graphics
      vcs_standard_player0_height
      vcs_standard_player1_height
      vcs_standard_missile0_height
      vcs_standard_missile0_y
      vcs_standard_ball_height
      vcs_standard_score
      vcs_standard_score_color
      vcs_standard_pointer_workspace
      vcs_standard_playfield_position
      vcs_standard_kernel_scratch
   )) {
      push @out, ".importzp $name";
   }
   push @out, '.import vcs_standard_playfield';
   push @out, '';
   push @out, '; Canonical TIA and RIOT addresses used by the selected source.';
   my %hw = (
      VSYNC=>0x00, VBLANK=>0x01, WSYNC=>0x02, RSYNC=>0x03,
      NUSIZ0=>0x04, NUSIZ1=>0x05, COLUP0=>0x06, COLUP1=>0x07,
      COLUPF=>0x08, COLUBK=>0x09, CTRLPF=>0x0a, REFP0=>0x0b,
      REFP1=>0x0c, PF0=>0x0d, PF1=>0x0e, PF2=>0x0f,
      RESP0=>0x10, RESP1=>0x11, RESM0=>0x12, RESM1=>0x13,
      RESBL=>0x14, AUDC0=>0x15, AUDC1=>0x16, AUDF0=>0x17,
      AUDF1=>0x18, AUDV0=>0x19, AUDV1=>0x1a, GRP0=>0x1b,
      GRP1=>0x1c, ENAM0=>0x1d, ENAM1=>0x1e, ENABL=>0x1f,
      HMP0=>0x20, HMP1=>0x21, HMM0=>0x22, HMM1=>0x23,
      HMBL=>0x24, VDELP0=>0x25, VDELP1=>0x26, VDELBL=>0x27,
      RESMP0=>0x28, RESMP1=>0x29, HMOVE=>0x2a, HMCLR=>0x2b,
      CXCLR=>0x2c, INTIM=>0x0284, TIM64T=>0x0296,
   );
   for my $name (sort { $hw{$a} <=> $hw{$b} || $a cmp $b } keys %hw) {
      push @out, sprintf('%-7s = $%04X', $name, $hw{$name});
   }
   push @out, '';
   push @out, '.export vcs_standard_kernel_drawscreen';
   push @out, '.export __abimeta$V1$function$definition$vcs_standard_kernel_drawscreen$summary$paramsQ3D0$parametersQ3D0';
   push @out, '__abimeta$V1$function$definition$vcs_standard_kernel_drawscreen$summary$paramsQ3D0$parametersQ3D0 = 0';
   push @out, '.export __abimeta$V1$function$definition$vcs_standard_kernel_drawscreen$return$modeQ3Dreturn_voidQ3BvoidQ28szQ3D0Q29$return_voidQ20voidQ28sizeQ3D0Q29';
   push @out, '__abimeta$V1$function$definition$vcs_standard_kernel_drawscreen$return$modeQ3Dreturn_voidQ3BvoidQ28szQ3D0Q29$return_voidQ20voidQ28sizeQ3D0Q29 = 0';
   push @out, '.export __sbpmeta$F$vcs_standard_kernel_drawscreen';
   push @out, '__sbpmeta$F$vcs_standard_kernel_drawscreen = 0';
   push @out, '';
   push @out, '.segment "KERNEL_CODE"';
   push @out, '.proc vcs_standard_kernel_drawscreen';
   push @out, '; ---- normalized from standard/std_overscan.asm ----';
   my @overscan_body = grep { $_->[1] !~ /^drawscreen\b/ } @$overscan;
   push @out, translate_source_set(\@overscan_body, \%labels);
   push @out, '';
   push @out, '; ---- normalized from standard/std_kernel.asm ----';
   push @out, translate_source_set($kernel, \%labels);
   push @out, '.endproc';
   push @out, '.align 256';
   push @out, '';
   push @out, '.segment "KERNEL_RODATA"';
   push @out, '.export vcs_standard_score_table';
   push @out, 'vcs_standard_score_table:';
   my @score = extract_score_bytes();
   for my $glyph (0 .. 10) {
      push @out, $glyph == 10 ? '; blank glyph' : "; digit $glyph";
      for my $row (0 .. 7) {
         push @out, '   .byte ' . $score[$glyph * 8 + $row];
      }
      push @out, '';
   }

   my $result = join("\n", @out);

   # The retained BASIC score bytes and the VCSC bcd24_t representation use
   # opposite byte/digit placement conventions.  Keep the original timed
   # display pipeline, but seed its six low-byte slots in the order required
   # for little-endian packed BCD: slots ultimately displayed as
   # 0,4,3,2,1,5 must contain digits 1..6.
   my $old_score_setup = <<'ASM';
     lax vcs_standard_score+2
     jsr @scorepointerset
     sty vcs_standard_pointer_workspace+5
     stx vcs_standard_pointer_workspace+2
     lax vcs_standard_score+1
     jsr @scorepointerset
     sty vcs_standard_pointer_workspace+4
     stx vcs_standard_pointer_workspace+1
     lax vcs_standard_score
     jsr @scorepointerset
     sty vcs_standard_pointer_workspace+3
     stx vcs_standard_pointer_workspace
ASM
   my $new_score_setup = <<'ASM';
     lda vcs_standard_score+2
     tax
     jsr @scorepointerset
     stx vcs_standard_pointer_workspace
     sty vcs_standard_pointer_workspace+3
     lda vcs_standard_score+1
     tax
     jsr @scorepointerset
     stx vcs_standard_pointer_workspace+1
     sty vcs_standard_pointer_workspace+4
     lda vcs_standard_score
     tax
     jsr @scorepointerset
     stx vcs_standard_pointer_workspace+2
     sty vcs_standard_pointer_workspace+5
ASM
   index($result, $old_score_setup) >= 0
      or die "normalized score-pointer setup no longer matches the selected retained source\n";
   $result =~ s/\Q$old_score_setup\E/$new_score_setup/;

   # Legalize the two visible score-glyph LAX loads.  LDA (zp),Y has the same
   # five-cycle read timing; TAX adds two cycles at each site.  The following
   # retained nine cycles of explicit padding are reduced to five so the first
   # TIA graphics write after the pair remains at the identical cycle.  X and
   # the borrowed stack pointer still carry the same two glyph bytes.
   my $old_visible_lax = <<'ASM';
         lax (vcs_standard_pointer_workspace+$2),y ;+5 29 87
         txs
         lax (vcs_standard_pointer_workspace+$4),y ;+5 36 108
             SLEEP 3

                 SLEEP 6
ASM
   my $new_visible_lax = <<'ASM';
         lda (vcs_standard_pointer_workspace+$2),y ;+5 29 87
         tax
         txs
         lda (vcs_standard_pointer_workspace+$4),y ;+5 38 114
         tax
             SLEEP 5
ASM
   index($result, $old_visible_lax) >= 0
      or die "normalized visible score LAX path no longer matches retained source\n";
   $result =~ s/\Q$old_visible_lax\E/$new_visible_lax/;

   # The retained kernel biases X by $54 so its sign bit doubles as the row-loop
   # terminator, then subtracts $54 from every playfield operand.  Normalize this
   # profile to an ordinary zero-based byte offset.  Keep the retained two-cycle
   # SBX increment for now, add an explicit compare at offset 44, and consume the
   # two added compare cycles from existing padding on both exit paths.
   my $biased_index_count = ($result =~ s/ldx #128-44\+\{4-4\}\*12/ldx #0/g);
   $biased_index_count == 1
      or die "normalized biased playfield-index initialization count changed: $biased_index_count\n";

   my %playfield_operand = (
      'vcs_standard_playfield-48+4*12+44-128,x'   => 'vcs_standard_playfield,x',
      'vcs_standard_playfield-48+4*12+45-128-0,x' => 'vcs_standard_playfield+1,x',
      'vcs_standard_playfield-48+4*12+47-128,x'   => 'vcs_standard_playfield+3,x',
      'vcs_standard_playfield-48+4*12+46-128-0,x' => 'vcs_standard_playfield+2,x',
   );
   for my $old (sort keys %playfield_operand) {
      my $new = $playfield_operand{$old};
      my $count = ($result =~ s/\Q$old\E/$new/g);
      $count == 2
         or die "normalized biased playfield operand '$old' count changed: $count\n";
   }

   my $old_row_advance = <<'ASM';
     txa
         sbx #256-4

     bmi @lastkernelline
ASM
   my $new_row_advance = <<'ASM';
     txa
         sbx #256-4
     cpx #44

     bcs @lastkernelline
ASM
   index($result, $old_row_advance) >= 0
      or die "normalized biased playfield row advance no longer matches retained source\n";
   $result =~ s/\Q$old_row_advance\E/$new_row_advance/;

   my $nonlast_pad_count = ($result =~ s/SLEEP 10\n                             lda #8/SLEEP 8\n                             lda #8/);
   $nonlast_pad_count == 1
      or die "normalized non-last playfield padding count changed: $nonlast_pad_count\n";

   # The direct branch to the last-line path also arrives two cycles later after
   # CPX.  Reduce only the first SLEEP immediately under @lastkernelline.
   my $last_pad_count = ($result =~ s/(\@lastkernelline:\n)             SLEEP 10/$1             SLEEP 8/);
   $last_pad_count == 1
      or die "normalized last-line playfield padding count changed: $last_pad_count\n";

   # The retained skip paths are cycle-balanced at ten cycles, but their
   # original placement before the hot loop can put the BCC targets on the
   # previous page after linking. A taken cross-page branch adds one cycle and
   # makes the two-line playfield schedule drift, producing visible horizontal
   # tears. Align the hot loop to a page and move the unreachable skip stubs
   # after the unconditional @goback jump, where both BCC targets remain local
   # without changing either draw/skip path or the retained SLEEP 2 phase.
   my $old_skip_layout = <<'ASM';
@skipDrawP0:
     lda #0
     tay
     jmp @continueP0

@skipDrawP1:
     lda #0
     tay
     jmp @continueP1

@kerloop:; enter at cycle 59??
ASM
   my $new_skip_layout = <<'ASM';
.align 256
@kerloop:; enter at cycle 59??
ASM
   index($result, $old_skip_layout) >= 0
      or die "normalized player-skip layout no longer matches the selected retained source\n";
   $result =~ s/\Q$old_skip_layout\E/$new_skip_layout/;

   my $old_skip_destination = <<'ASM';
     jmp @goback


@lastkernelline:
ASM
   my $new_skip_destination = <<'ASM';
     jmp @goback

; Local cycle-balanced player skip paths. The unconditional jump above and
; direct BCS to @lastkernelline keep these stubs off every fall-through path.
@skipDrawP0:
     lda #0
     tay
     jmp @continueP0

@skipDrawP1:
     lda #0
     tay
     jmp @continueP1

@lastkernelline:
ASM
   index($result, $old_skip_destination) >= 0
      or die "normalized player-skip destination no longer matches the selected retained source\n";
   $result =~ s/\Q$old_skip_destination\E/$new_skip_destination/;

   # Legalize the two steady-state player counters.  The legal paths keep the
   # decremented row in Y, compare it against a precomputed exclusive height,
   # and use cycle-balanced draw/zero diamonds.  Player 1 grows by one cycle;
   # replace the main ball's four-cycle ROL/ROL encoding with the existing
   # three-cycle height+2 SBC encoding.  Player 0 deliberately uses a four-cycle
   # absolute TIA store and grows by two cycles; remove the following two-cycle
   # loop pad.  The one-time first entry saves one cycle through a direct zero-
   # page save, and the row-transition path consumes three fewer explicit delay
   # cycles, so every PF write remains at its original phase.
   my $old_prepare_call = <<'ASM';
     lda vcs_standard_player0_y
     ldx #0
     sta WSYNC
ASM
   my $new_prepare_call = <<'ASM';
     jsr @prepare_player_state
     lda vcs_standard_player0_y
     ldx #0
     sta WSYNC
ASM
   index($result, $old_prepare_call) >= 0
      or die "normalized player preparation call site no longer matches retained source\n";
   $result =~ s/\Q$old_prepare_call\E/$new_prepare_call/;

   my $initial_save_count = ($result =~ s/sta vcs_standard_pointer_workspace \+ 7,x/sta vcs_standard_pointer_workspace + 7/);
   $initial_save_count == 1
      or die "normalized initial player save count changed: $initial_save_count\n";

   my $steady_pad_count = ($result =~ s/(\@continuekernel:\n)     SLEEP 2\n/$1/);
   $steady_pad_count == 1
      or die "normalized steady player-loop padding count changed: $steady_pad_count\n";

   my $old_main_ball = <<'ASM';
     dcp vcs_standard_ball_y
     rol
     rol
     ; rol
     ; rol
@goback:
ASM
   my $new_main_ball = <<'ASM';
     dcp vcs_standard_ball_y
     sbc vcs_standard_pointer_workspace + 9
     ; rol
     ; rol
@goback:
ASM
   index($result, $old_main_ball) >= 0
      or die "normalized steady ball path no longer matches retained source\n";
   $result =~ s/\Q$old_main_ball\E/$new_main_ball/;

   my $old_player1 = <<'ASM';
@startkernel:
     lda vcs_standard_player1_height ;3
     dcp vcs_standard_player1_y ;5
     bcc @skipDrawP1 ;2
     ldy vcs_standard_player1_y ;3
     lda (vcs_standard_player1_graphics),y ;5; player0pointer must be selected carefully by the compiler
     ; so it doesn't cross a page boundary!

@continueP1:
     sta GRP1 ;3
ASM
   my $new_player1 = <<'ASM';
@startkernel:
     ldy vcs_standard_player1_y ;3
     dey ;2
     sty vcs_standard_player1_y ;3
     cpy vcs_standard_kernel_scratch + 3 ;3, exclusive height
     bcc @drawP1 ;3 when drawing, 2 when skipped
     lda vcs_standard_kernel_scratch + 4 ;3, permanent zero
     jmp @continueP1 ;3
@drawP1:
     lda (vcs_standard_player1_graphics),y ;5; graphics range must stay on one page
@continueP1:
     sta GRP1 ;3
ASM
   index($result, $old_player1) >= 0
      or die "normalized steady player-1 path no longer matches retained source\n";
   $result =~ s/\Q$old_player1\E/$new_player1/;

   my $old_player0 = <<'ASM';
     lda vcs_standard_player0_height
     dcp vcs_standard_player0_y
     bcc @skipDrawP0
     ldy vcs_standard_player0_y
     lda (vcs_standard_player0_graphics),y
@continueP0:
     sta GRP0
ASM
   my $new_player0 = <<'ASM';
     ldy vcs_standard_player0_y
     dey
     sty vcs_standard_player0_y
     cpy vcs_standard_kernel_scratch + 2 ; exclusive height
     bcc @drawP0
     lda vcs_standard_kernel_scratch + 4 ; permanent zero
     jmp @continueP0
@drawP0:
     lda (vcs_standard_player0_graphics),y
@continueP0:
     sta.a GRP0
ASM
   index($result, $old_player0) >= 0
      or die "normalized steady player-0 path no longer matches retained source\n";
   $result =~ s/\Q$old_player0\E/$new_player0/;

   my $row_transition_pad_count = ($result =~ s/SLEEP 8\n                             lda #8/SLEEP 5\n                             lda #8/);
   $row_transition_pad_count == 1
      or die "normalized player row-transition padding count changed: $row_transition_pad_count\n";

   my $old_main_skip_stubs = <<'ASM';
; Local cycle-balanced player skip paths. The unconditional jump above and
; direct BCS to @lastkernelline keep these stubs off every fall-through path.
@skipDrawP0:
     lda #0
     tay
     jmp @continueP0

@skipDrawP1:
     lda #0
     tay
     jmp @continueP1

ASM
   index($result, $old_main_skip_stubs) >= 0
      or die "normalized obsolete steady player skip stubs are missing\n";
   $result =~ s/\Q$old_main_skip_stubs\E//;

   my $old_player_helper_tail = <<'ASM';
 sta VBLANK
 RETURN


.endproc
ASM
   my $new_player_helper_tail = <<'ASM';
 sta VBLANK
 RETURN

@prepare_player_state:
     lda vcs_standard_player0_height
     clc
     adc #1
     sta vcs_standard_kernel_scratch + 2
     lda vcs_standard_player1_height
     clc
     adc #1
     sta vcs_standard_kernel_scratch + 3
     lda #0
     sta vcs_standard_kernel_scratch + 4
     rts

.endproc
ASM
   index($result, $old_player_helper_tail) >= 0
      or die "normalized player preparation helper insertion point changed\n";
   $result =~ s/\Q$old_player_helper_tail\E/$new_player_helper_tail/;

   $result =~ s/[ \t]+$//mg;
   $result =~ s/\n{4,}/\n\n\n/g;
   return $result . "\n";
}

my %generated = (
   'standard_4k_ntsc_macros.inc' => macro_output(),
   'standard_4k_ntsc_kernel.s'   => kernel_output(),
);

for my $name (sort keys %generated) {
   my $path = File::Spec->catfile($output_dir, $name);
   if ($check) {
      -f $path or die "$path is missing; run normalize.pl\n";
      my $actual = slurp($path);
      $actual eq $generated{$name}
         or die "$path is stale; run normalize.pl and review the generated diff\n";
   } else {
      open(my $fh, '>:raw', $path) or die "could not create $path: $!\n";
      print {$fh} $generated{$name};
      close($fh) or die "could not close $path: $!\n";
   }
}

print $check ? "standard_4k_ntsc normalization is current\n"
             : "wrote standard_4k_ntsc normalized sources to $output_dir\n";
