; Generated by kernels/standard_4k_ntsc/normalize.pl.
; Do not edit this file by hand; edit the normalizer or retained source.
;
; Mechanically normalized source for the selected standard kernel.
; Selected profile: NTSC, unbanked 4K, non-reflected standard kernel,
; default asymmetric playfield, default decimal score, no optional hooks.
;
; Retained input SHA-256:
;   ba1270e04db26dffe52242bea6022a8f150c1b8d9c5af706f04aff79a364d4e7  legacy-basic-kernels/common/macro.h
;   405e8eb26e7d952d8c70332ea39990a82bcc4876765c225e8c48744d00ed3588  legacy-basic-kernels/common/2600basic.h
;   089094a8ca34aa13a68f4453a3cb61955bf545b33f34c0096680ef00ca57caa8  legacy-basic-kernels/standard/std_overscan.asm
;   6608a6b3dcb80e79d58142bf25a484950957b697d97d6184eb09f4b50f970c2c  legacy-basic-kernels/standard/std_kernel.asm
;   96345e1a4bbe2a80f52d8b1962eaceaac3902206c9d2ebbf102c76bcc24ac734  legacy-basic-kernels/common/score_graphics.asm
.include "standard_4k_ntsc_macros.inc"

; Module-owned state imported from standard_4k_ntsc.c26.
.importzp vcs_standard_object_x
.importzp vcs_standard_player0_y
.importzp vcs_standard_player1_y
.importzp vcs_standard_missile1_height
.importzp vcs_standard_missile1_y
.importzp vcs_standard_ball_y
.importzp vcs_standard_player0_graphics
.importzp vcs_standard_player1_graphics
.importzp vcs_standard_player0_height
.importzp vcs_standard_player1_height
.importzp vcs_standard_missile0_height
.importzp vcs_standard_missile0_y
.importzp vcs_standard_ball_height
.importzp vcs_standard_score
.importzp vcs_standard_score_color
.importzp vcs_standard_pointer_workspace
.importzp vcs_standard_playfield_position
.importzp vcs_standard_kernel_scratch
.import vcs_standard_playfield

; Canonical TIA and RIOT addresses used by the selected source.
VSYNC   = $0000
VBLANK  = $0001
WSYNC   = $0002
RSYNC   = $0003
NUSIZ0  = $0004
NUSIZ1  = $0005
COLUP0  = $0006
COLUP1  = $0007
COLUPF  = $0008
COLUBK  = $0009
CTRLPF  = $000A
REFP0   = $000B
REFP1   = $000C
PF0     = $000D
PF1     = $000E
PF2     = $000F
RESP0   = $0010
RESP1   = $0011
RESM0   = $0012
RESM1   = $0013
RESBL   = $0014
AUDC0   = $0015
AUDC1   = $0016
AUDF0   = $0017
AUDF1   = $0018
AUDV0   = $0019
AUDV1   = $001A
GRP0    = $001B
GRP1    = $001C
ENAM0   = $001D
ENAM1   = $001E
ENABL   = $001F
HMP0    = $0020
HMP1    = $0021
HMM0    = $0022
HMM1    = $0023
HMBL    = $0024
VDELP0  = $0025
VDELP1  = $0026
VDELBL  = $0027
RESMP0  = $0028
RESMP1  = $0029
HMOVE   = $002A
HMCLR   = $002B
CXCLR   = $002C
INTIM   = $0284
TIM64T  = $0296

.export vcs_standard_kernel_drawscreen
.export __abimeta$V1$function$definition$vcs_standard_kernel_drawscreen$summary$paramsQ3D0$parametersQ3D0
__abimeta$V1$function$definition$vcs_standard_kernel_drawscreen$summary$paramsQ3D0$parametersQ3D0 = 0
.export __abimeta$V1$function$definition$vcs_standard_kernel_drawscreen$return$modeQ3Dreturn_voidQ3BvoidQ28szQ3D0Q29$return_voidQ20voidQ28sizeQ3D0Q29
__abimeta$V1$function$definition$vcs_standard_kernel_drawscreen$return$modeQ3Dreturn_voidQ3BvoidQ28szQ3D0Q29$return_voidQ20voidQ28sizeQ3D0Q29 = 0
.export __sbpmeta$F$vcs_standard_kernel_drawscreen
__sbpmeta$F$vcs_standard_kernel_drawscreen = 0

.segment "KERNEL_CODE"
.proc vcs_standard_kernel_drawscreen
; ---- normalized from standard/std_overscan.asm ----
; Provided under the CC0 license. See the included LICENSE.txt for details.


@overscan:

@overscanloop:
     lda INTIM ;wait for sync
     bmi @overscanloop
@doneoverscan:

     ;do VSYNC


     lda #2
     sta WSYNC
     sta VSYNC
     STA WSYNC
     STA WSYNC
     lsr
     STA WSYNC
     STA VSYNC
     sta VBLANK
         lda #37+128
     sta TIM64T


   .if {<*} > $e9 && {<*} < $fa
   ; Explicit layout-time equivalent of REPEAT ($fa-(<*)).
   .if {<*} < $fa
      NOP
   .endif
   .if {<*} < $fa
      NOP
   .endif
   .if {<*} < $fa
      NOP
   .endif
   .if {<*} < $fa
      NOP
   .endif
   .if {<*} < $fa
      NOP
   .endif
   .if {<*} < $fa
      NOP
   .endif
   .if {<*} < $fa
      NOP
   .endif
   .if {<*} < $fa
      NOP
   .endif
   .if {<*} < $fa
      NOP
   .endif
   .if {<*} < $fa
      NOP
   .endif
   .if {<*} < $fa
      NOP
   .endif
   .if {<*} < $fa
      NOP
   .endif
   .if {<*} < $fa
      NOP
   .endif
   .if {<*} < $fa
      NOP
   .endif
   .if {<*} < $fa
      NOP
   .endif
   .if {<*} < $fa
      NOP
   .endif
   .endif
     sta WSYNC
     ldx #4
     SLEEP 3
@HorPosLoop:; 5
     lda vcs_standard_object_x + 0,X ;+4 9
     sec ;+2 11
@DivideLoop:
     sbc #15
     bcs @DivideLoop;+4 15
     sta vcs_standard_pointer_workspace + 6,X ;+4 19
     sta RESP0,X ;+4 23
     sta WSYNC
     dex
     bpl @HorPosLoop;+5 5
     ; 4

     ldx #4
     ldy vcs_standard_pointer_workspace + 6,X
     lda @repostable-256,Y
     sta HMP0,X ;+14 18

     dex
     ldy vcs_standard_pointer_workspace + 6,X
     lda @repostable-256,Y
     sta HMP0,X ;+14 32

     dex
     ldy vcs_standard_pointer_workspace + 6,X
     lda @repostable-256,Y
     sta HMP0,X ;+14 46

     dex
     ldy vcs_standard_pointer_workspace + 6,X
     lda @repostable-256,Y
     sta HMP0,X ;+14 60

     dex
     ldy vcs_standard_pointer_workspace + 6,X
     lda @repostable-256,Y
     sta HMP0,X ;+14 74

     sta WSYNC

     sta HMOVE ;+3 3


     ;set score pointers
     lax vcs_standard_score+2
     jsr @scorepointerset
     stx vcs_standard_pointer_workspace
     sty vcs_standard_pointer_workspace+3
     lax vcs_standard_score+1
     jsr @scorepointerset
     stx vcs_standard_pointer_workspace+1
     sty vcs_standard_pointer_workspace+4
     lax vcs_standard_score
     jsr @scorepointerset
     stx vcs_standard_pointer_workspace+2
     sty vcs_standard_pointer_workspace+5

@vblk:
     ; run possible vblank bB code
@vblk2:
     LDA INTIM
     bmi @vblk2
     jmp @kernel


     .byte $80,$70,$60,$50,$40,$30,$20,$10,$00
     .byte $F0,$E0,$D0,$C0,$B0,$A0,$90
@repostable:

@scorepointerset:
     and #$0F
     asl
     asl
     asl
     adc #<vcs_standard_score_table
     tay
     txa
     ; and #$F0
     ; lsr
     asr #$F0
     adc #<vcs_standard_score_table
     tax
     rts


; ---- normalized from standard/std_kernel.asm ----
; Provided under the CC0 license. See the included LICENSE.txt for details.

     ; This is a 2-line kernel!
@kernel:
     sta WSYNC
     lda #255
     sta TIM64T

     lda #1
     sta VDELBL
     sta VDELP0
     ldx vcs_standard_ball_height
     inx
     inx
     stx vcs_standard_pointer_workspace + 9
     lda vcs_standard_player1_y
     sta vcs_standard_pointer_workspace + 8

         ldx vcs_standard_missile0_height
         inx

     inx
     stx vcs_standard_kernel_scratch + 0

     lda vcs_standard_ball_y
     sta vcs_standard_kernel_scratch + 1

     lda vcs_standard_player0_y
     ldx #0
     sta WSYNC
     stx GRP0
     stx GRP1
     stx PF1
     stx PF2
     stx CXCLR
         SLEEP 3

     sta vcs_standard_pointer_workspace + 7,x

     ;store these so they can be retrieved later
         ldx #128-44+{4-4}*12

     dec vcs_standard_player0_y

     lda vcs_standard_missile0_y
     sta vcs_standard_pointer_workspace + 10
     lda vcs_standard_missile1_y
     sta vcs_standard_pointer_workspace + 11

     lda vcs_standard_playfield_position
     sta vcs_standard_pointer_workspace + 6

             lda #10
     clc
     sbc vcs_standard_playfield_position
     sta vcs_standard_playfield_position
     jmp @startkernel

@skipDrawP0:
     lda #0
     tay
     jmp @continueP0

@skipDrawP1:
     lda #0
     tay
     jmp @continueP1

@kerloop:; enter at cycle 59??

@continuekernel:
     SLEEP 2
@continuekernel2:
     lda vcs_standard_ball_height

         ldy vcs_standard_playfield-48+4*12+44-128,x
         sty PF1 ;3
         ldy vcs_standard_playfield-48+4*12+45-128-0,x ;4
         sty PF2 ;3
         ldy vcs_standard_playfield-48+4*12+47-128,x ;4
         sty PF1 ; 3 too early?
         ldy vcs_standard_playfield-48+4*12+46-128-0,x;4
         sty PF2 ;3

     ; should be playfield+$38 for width=2

     dcp vcs_standard_ball_y
     rol
     rol
     ; rol
     ; rol
@goback:
     sta ENABL
@startkernel:
     lda vcs_standard_player1_height ;3
     dcp vcs_standard_player1_y ;5
     bcc @skipDrawP1 ;2
     ldy vcs_standard_player1_y ;3
     lda (vcs_standard_player1_graphics),y ;5; player0pointer must be selected carefully by the compiler
     ; so it doesn't cross a page boundary!

@continueP1:
     sta GRP1 ;3

         lda vcs_standard_missile1_height ;3
         dcp vcs_standard_missile1_y ;5
         rol;2
         rol;2
         sta ENAM1 ;3

         lda vcs_standard_playfield-48+4*12+44-128,x ;4
         sta PF1 ;3
         lda vcs_standard_playfield-48+4*12+45-128-0,x ;4
         sta PF2 ;3
         lda vcs_standard_playfield-48+4*12+47-128,x ;4
         sta PF1 ; 3 too early?
         lda vcs_standard_playfield-48+4*12+46-128-0,x;4
         sta PF2 ;3
     ; sleep 3

     lda vcs_standard_player0_height
     dcp vcs_standard_player0_y
     bcc @skipDrawP0
     ldy vcs_standard_player0_y
     lda (vcs_standard_player0_graphics),y
@continueP0:
     sta GRP0

             lda vcs_standard_missile0_height ;3
             dcp vcs_standard_missile0_y ;5
             sbc vcs_standard_kernel_scratch + 0
             sta ENAM0 ;3
         dec vcs_standard_pointer_workspace + 6
         bne @continuekernel

@altkernel:

         lda #0
     sta PF1
     sta PF2


     ;sleep 3

     ;28 cycles to fix things
     ;minus 11=17

     ; lax temp4
     ; clc
     txa
         sbx #256-4

     bmi @lastkernelline

                     ; read paddle 0
                     ; lo-res paddle read
                     ; bit INPT0
                     ; bmi paddleskipread
                     ; inc paddle0
                     ;donepaddleskip
                     SLEEP 10
                             lda #8
                     sta vcs_standard_pointer_workspace + 6


     lda vcs_standard_ball_height
     dcp vcs_standard_ball_y
     sbc vcs_standard_pointer_workspace + 9


     jmp @goback


@lastkernelline:
             SLEEP 10

             ldx vcs_standard_playfield_position
             ;sleep 3
             SLEEP 2 ; this was over 1 cycle

         jmp @enterlastkernel


   .if {<*} > $d5
   .align 256
   .endif
     ; this is a kludge to prevent page wrapping - fix!!!

@skipDrawlastP1:
     lda #0
     tay ; added so we don't cross a page
     jmp @continuelastP1

@endkerloop:; enter at cycle 59??

     nop

@enterfromNBL:
         ldy.a vcs_standard_playfield-48+4*12+44
         sty PF1 ;3
         ldy.a vcs_standard_playfield-48+4*12+45-0
         sty PF2 ;3
         ldy.a vcs_standard_playfield-48+4*12+47
         sty PF1 ; possibly too early?
         ldy.a vcs_standard_playfield-48+4*12+46-0
         sty PF2 ;3

@enterlastkernel:
     lda vcs_standard_ball_height

     ; tya
     dcp vcs_standard_ball_y
     ; sleep 4

     ; sbc stack3
     rol
     rol
     sta ENABL

     lda vcs_standard_player1_height ;3
     dcp vcs_standard_player1_y ;5
     bcc @skipDrawlastP1
     ldy vcs_standard_player1_y ;3
     lda (vcs_standard_player1_graphics),y ;5; player0pointer must be selected carefully by the compiler
     ; so it doesn't cross a page boundary!

@continuelastP1:
     sta GRP1 ;3

         lda vcs_standard_missile1_height ;3
         dcp vcs_standard_missile1_y ;5

     dex
     ;dec temp4 ; might try putting this above PF writes
     beq @endkernel


         ldy.a vcs_standard_playfield-48+4*12+44
         sty PF1 ;3
         ldy.a vcs_standard_playfield-48+4*12+45-0
         sty PF2 ;3
         ldy.a vcs_standard_playfield-48+4*12+47
         sty PF1 ; possibly too early?
         ldy.a vcs_standard_playfield-48+4*12+46-0
         sty PF2 ;3

         rol;2
         rol;2
         sta ENAM1 ;3

     lda.a vcs_standard_player0_height
     dcp vcs_standard_player0_y
     bcc @skipDrawlastP0
     ldy vcs_standard_player0_y
     lda (vcs_standard_player0_graphics),y
@continuelastP0:
     sta GRP0


         lda vcs_standard_missile0_height ;3
         dcp vcs_standard_missile0_y ;5
         sbc vcs_standard_kernel_scratch + 0
         sta ENAM0 ;3
         jmp @endkerloop


     ; ifconst donepaddleskip
         ;paddleskipread
         ; this is kind of lame, since it requires 4 cycles from a page boundary crossing
         ; plus we get a lo-res paddle read
         ; bmi donepaddleskip
     ; endif

@skipDrawlastP0:
     lda #0
     tay
     jmp @continuelastP0


@endkernel:
     ; 6 digit score routine
     stx PF1
     stx PF2
     stx PF0
     clc

             lda #10

     sbc vcs_standard_playfield_position
     sta vcs_standard_playfield_position
     txa


     sta WSYNC,x

     ; STA WSYNC ;first one, need one more
     sta REFP0
     sta REFP1
     STA GRP0
     STA GRP1
     ; STA PF1
     ; STA PF2
     sta HMCLR
     sta ENAM0
     sta ENAM1
     sta ENABL

     lda vcs_standard_pointer_workspace + 7 ;restore variables that were obliterated by kernel
     sta vcs_standard_player0_y
     lda vcs_standard_pointer_workspace + 8
     sta vcs_standard_player1_y
         lda vcs_standard_pointer_workspace + 11
         sta vcs_standard_missile1_y
             lda vcs_standard_pointer_workspace + 10
             sta vcs_standard_missile0_y
     lda vcs_standard_kernel_scratch + 1
     sta vcs_standard_ball_y

     ; strangely, this isn't required any more. might have
     ; resulted from the no_blank_lines score bounce fix
     ;ifconst no_blank_lines
         ;sta WSYNC
     ;endif

     lda INTIM
     clc
         adc #43+12+87
     ; sta WSYNC
     sta TIM64T


     ; now reassign temp vars for score pointers

     ; score pointers contain:
     ; score1-5: lo1,lo2,lo3,lo4,lo5,lo6
     ; swap lo2->temp1
     ; swap lo4->temp3
     ; swap lo6->temp5
         lda vcs_standard_pointer_workspace+1
         ; ldy temp1
         sta vcs_standard_pointer_workspace + 6
         ; sty scorepointers+1

         lda vcs_standard_pointer_workspace+3
         ; ldy temp3
         sta vcs_standard_pointer_workspace + 8
         ; sty scorepointers+3


         sta HMCLR
         tsx
         stx vcs_standard_kernel_scratch + 0
         ldx #$E0
         stx HMP0

         LDA vcs_standard_score_color
         STA COLUP0
         STA COLUP1
         sta WSYNC
         ldx #0
         STx GRP0
         STx GRP1 ; seems to be needed because of vdel

         lda vcs_standard_pointer_workspace+5
         ; ldy temp5
         sta vcs_standard_pointer_workspace + 10,x
         ; sty scorepointers+5
         lda #>vcs_standard_score_table
         sta vcs_standard_pointer_workspace+1
         sta vcs_standard_pointer_workspace+3
         sta vcs_standard_pointer_workspace+5
         sta vcs_standard_pointer_workspace + 7
         sta vcs_standard_pointer_workspace + 9
         sta vcs_standard_pointer_workspace + 11
         LDY #7
         STY VDELP0
         STA RESP0
         STA RESP1


         LDA #$03
         STA NUSIZ0
         STA NUSIZ1
         STA VDELP1
         LDA #$F0
         STA HMP1
         lda (vcs_standard_pointer_workspace),y
         sta GRP0
         STA HMOVE ; cycle 73 ?
         jmp @beginscore


   .if {<*} > $d4
   .align 256; kludge that potentially wastes space! should be fixed!
   .endif

@loop2:
         lda (vcs_standard_pointer_workspace),y ;+5 68 204
         sta GRP0 ;+3 71 213 D1 -- -- --
                 SLEEP 7
         ; cycle 0
@beginscore:
         lda (vcs_standard_pointer_workspace+$8),y ;+5 5 15
         sta GRP1 ;+3 8 24 D1 D1 D2 --
         lda (vcs_standard_pointer_workspace+$6),y ;+5 13 39
         sta GRP0 ;+3 16 48 D3 D1 D2 D2
         lax (vcs_standard_pointer_workspace+$2),y ;+5 29 87
         txs
         lax (vcs_standard_pointer_workspace+$4),y ;+5 36 108
             SLEEP 3

                 SLEEP 6

         lda (vcs_standard_pointer_workspace+$A),y ;+5 21 63
         stx GRP1 ;+3 44 132 D3 D3 D4 D2!
         tsx
         stx GRP0 ;+3 47 141 D5 D3! D4 D4
         sta GRP1 ;+3 50 150 D5 D5 D6 D4!
         sty GRP0 ;+3 53 159 D4* D5! D6 D6
         dey
         bpl @loop2 ;+2 60 180

         ldx vcs_standard_kernel_scratch + 0
         txs
         ; lda scorepointers+1
         ldy vcs_standard_pointer_workspace + 6
         ; sta temp1
         sty vcs_standard_pointer_workspace+1

         LDA #0
         sta PF1
         STA GRP0
         STA GRP1
         STA VDELP0
         STA VDELP1;do we need these
         STA NUSIZ0
         STA NUSIZ1

         ; lda scorepointers+3
         ldy vcs_standard_pointer_workspace + 8
         ; sta temp3
         sty vcs_standard_pointer_workspace+3

         ; lda scorepointers+5
         ldy vcs_standard_pointer_workspace + 10
         ; sta temp5
         sty vcs_standard_pointer_workspace+5
            lda #2
 sta WSYNC
 sta VBLANK
 RETURN


.endproc
.align 256

.segment "KERNEL_RODATA"
.export vcs_standard_score_table
vcs_standard_score_table:
; digit 0
   .byte %00111100
   .byte %01100110
   .byte %01100110
   .byte %01100110
   .byte %01100110
   .byte %01100110
   .byte %01100110
   .byte %00111100

; digit 1
   .byte %01111110
   .byte %00011000
   .byte %00011000
   .byte %00011000
   .byte %00011000
   .byte %00111000
   .byte %00011000
   .byte %00001000

; digit 2
   .byte %01111110
   .byte %01100000
   .byte %01100000
   .byte %00111100
   .byte %00000110
   .byte %00000110
   .byte %01000110
   .byte %00111100

; digit 3
   .byte %00111100
   .byte %01000110
   .byte %00000110
   .byte %00000110
   .byte %00011100
   .byte %00000110
   .byte %01000110
   .byte %00111100

; digit 4
   .byte %00001100
   .byte %00001100
   .byte %01111110
   .byte %01001100
   .byte %01001100
   .byte %00101100
   .byte %00011100
   .byte %00001100

; digit 5
   .byte %00111100
   .byte %01000110
   .byte %00000110
   .byte %00000110
   .byte %00111100
   .byte %01100000
   .byte %01100000
   .byte %01111110

; digit 6
   .byte %00111100
   .byte %01100110
   .byte %01100110
   .byte %01100110
   .byte %01111100
   .byte %01100000
   .byte %01100010
   .byte %00111100

; digit 7
   .byte %00110000
   .byte %00110000
   .byte %00110000
   .byte %00011000
   .byte %00001100
   .byte %00000110
   .byte %01000010
   .byte %00111110

; digit 8
   .byte %00111100
   .byte %01100110
   .byte %01100110
   .byte %01100110
   .byte %00111100
   .byte %01100110
   .byte %01100110
   .byte %00111100

; digit 9
   .byte %00111100
   .byte %01000110
   .byte %00000110
   .byte %00111110
   .byte %01100110
   .byte %01100110
   .byte %01100110
   .byte %00111100

; blank glyph
   .byte %00000000
   .byte %00000000
   .byte %00000000
   .byte %00000000
   .byte %00000000
   .byte %00000000
   .byte %00000000
   .byte %00000000

