; vcsc-runtime.inc

.importzp _vcsc_arg0
.importzp _vcsc_arg1
.importzp _vcsc_ptr0
.importzp _vcsc_ptr1
.importzp _vcsc_ptr2
.importzp _vcsc_ptr3
.importzp _vcsc_tmp0
.importzp _vcsc_tmp1
.importzp _vcsc_tmp2
.importzp _vcsc_tmp3
.importzp _vcsc_tmp4
.importzp _vcsc_tmp5

.def arg0 _vcsc_arg0
.def arg1 _vcsc_arg1
.def ptr0 _vcsc_ptr0
.def ptr1 _vcsc_ptr1
.def ptr2 _vcsc_ptr2
.def ptr3 _vcsc_ptr3
.def tmp0 _vcsc_tmp0
.def tmp1 _vcsc_tmp1
.def tmp2 _vcsc_tmp2
.def tmp3 _vcsc_tmp3
.def tmp4 _vcsc_tmp4
.def tmp5 _vcsc_tmp5
