#!/usr/bin/perl
# This file is covered under CC0-1.0. See libraries/LICENSE.txt.


use strict;
use warnings;
use Cwd qw(abs_path);
use File::Basename qw(dirname);
use File::Compare qw(compare);
use File::Path qw(make_path);
use File::Spec;
use Getopt::Long qw(GetOptions);

sub usage { die "usage: $0 [--check] [--output-dir DIR]\n"; }

my $check = 0;
my $output_dir;
GetOptions('check' => \$check, 'output-dir=s' => \$output_dir) or usage();
usage() if @ARGV;

my $script = abs_path($0) // die "could not resolve $0\n";
my $profile = dirname($script);
my $base_profile = abs_path(File::Spec->catdir($profile, '..', 'standard_4k_ntsc'))
   // die "could not resolve base profile\n";
my $vcs = abs_path(File::Spec->catdir($profile, '..', '..'))
   // die "could not resolve VCS library directory\n";
my $legacy_renderer = File::Spec->catfile($vcs, 'legacy-basic-renderers', 'standard', 'std_renderer.asm');
$output_dir = defined($output_dir) ? $output_dir : $profile;
make_path($output_dir) if !$check && !-d $output_dir;

sub slurp {
   my ($path) = @_;
   open(my $fh, '<:raw', $path) or die "could not open $path: $!\n";
   local $/;
   my $text = <$fh>;
   close($fh) or die "could not close $path: $!\n";
   $text = '' if !defined($text);
   $text =~ s/\r\n?/\n/g;
   return $text;
}

sub replace_once {
   my ($text_ref, $old, $new, $why) = @_;
   my $count = () = $$text_ref =~ /\Q$old\E/g;
   $count == 1 or die "normalizer expected exactly one $why, found $count\n";
   $$text_ref =~ s/\Q$old\E/$new/;
}

my $legacy = slurp($legacy_renderer);
for my $required (
   'ifnconst player1colors',
   'lda (player1color),y',
   'sta COLUP1',
   'ifnconst playercolors',
   'lda.w player0colorstore',
   'sta COLUP0',
   'lda (player0color),y',
   'sta player0colorstore',
) {
   index($legacy, $required) >= 0
      or die "$legacy_renderer: retained player-color branch lost '$required'\n";
}

my $base_renderer_path = File::Spec->catfile($base_profile, 'standard_4k_ntsc_renderer.s26');
my $base_macros_path = File::Spec->catfile($base_profile, 'standard_4k_ntsc_macros.inc');
my $renderer = slurp($base_renderer_path);
my $macros = slurp($base_macros_path);

$renderer =~ s/standard_4k_ntsc_macros\.inc/standard_4k_ntsc_playercolors_macros.inc/g;
$renderer =~ s/vcs_standard_/vcs_standard_color_/g;
replace_once(\$renderer,
   "; Generated by renderers/standard_4k_ntsc/normalize.pl.",
   "; Generated by renderers/standard_4k_ntsc_playercolors/normalize.pl.",
   'generated-renderer header');
replace_once(\$renderer,
   "; Selected profile: NTSC, unbanked 4K, non-reflected standard renderer,\n; default asymmetric playfield, default decimal score, one overscan hook.",
   "; Selected profile: NTSC, unbanked 4K, non-reflected player-color renderer,\n; default asymmetric playfield, default decimal score, P0/P1/BL only,\n; per-row P0/P1 color tables, one overscan hook.",
   'selected-profile header');
replace_once(\$renderer,
   '; Module-owned state imported from standard_4k_ntsc.c26.',
   '; Module-owned state imported from standard_4k_ntsc_playercolors.c26.',
   'module-state header');
replace_once(\$renderer, 'lda #37+128', 'lda #38+128', 'player-color VBLANK timer');

my $old_imports = <<'ASM';
.importzp vcs_standard_color_player0_y
.importzp vcs_standard_color_player1_y
.importzp vcs_standard_color_missile1_height
.importzp vcs_standard_color_missile1_y
.importzp vcs_standard_color_ball_y
.importzp vcs_standard_color_player0_graphics
.importzp vcs_standard_color_player1_graphics
.importzp vcs_standard_color_player0_height
.importzp vcs_standard_color_player1_height
.importzp vcs_standard_color_missile0_height
.importzp vcs_standard_color_missile0_y
.importzp vcs_standard_color_ball_height
ASM
my $new_imports = <<'ASM';
.importzp vcs_standard_color_player0_y
.importzp vcs_standard_color_player1_y
.importzp vcs_standard_color_ball_y
.importzp vcs_standard_color_player0_graphics
.importzp vcs_standard_color_player1_graphics
.import vcs_standard_color_player0_colors
.import vcs_standard_color_player1_colors
.importzp vcs_standard_color_player0_height
.importzp vcs_standard_color_player1_height
.importzp vcs_standard_color_ball_height
.importzp vcs_standard_color_player0_latch
ASM
replace_once(\$renderer, $old_imports, $new_imports, 'player/missile import block');

replace_once(\$renderer, <<'OLD', <<'NEW', 'missile-zero setup slot');
         ldx vcs_standard_color_missile0_height
         inx

     inx
     stx vcs_standard_color_object_masks + 3
OLD
         ; The legacy player-color profile spends the former missile-zero
         ; setup slot on color-table work. Preserve the selected two-line
         ; renderer's entry phase exactly.
         SLEEP 10
NEW

replace_once(\$renderer, <<'OLD', <<'NEW', 'missile-zero saved-Y slot');
     ; The horizontal-position loop has just reused pointer workspace +10.
     ; Reconstruct and preserve M0's application Y from its final-row bias
     ; without changing this twelve-cycle setup slot.
     lda vcs_standard_color_missile0_y
     clc
     adc #89
     sta vcs_standard_color_pointer_workspace + 10
     nop
OLD
     ; The legacy player-color path replaces missile-zero state with a
     ; color pointer and latch. Keep the former twelve-cycle slot as delay so
     ; the visible renderer starts on the same color clock.
     SLEEP 12
NEW

replace_once(\$renderer, <<'OLD', <<'NEW', 'P1 balanced graphics branch');
     cpy vcs_standard_color_object_masks + 15 ;3, exclusive height
     bcc.same @drawP1 ;3 when drawing, 2 when skipped
     lda vcs_standard_color_object_masks + 19 ;3, permanent zero
     jmp @continueP1 ;3
@drawP1:
     lda (vcs_standard_color_player1_graphics),y ;5; graphics range must stay on one page
@continueP1:
OLD
     cpy vcs_standard_color_object_masks + 15 ;3, exclusive height
     bcs.same @skipP1 ;3 when skipped, 2 when drawing
     lda (vcs_standard_color_player1_graphics),y ;5; graphics range must stay on one page
     jmp @continueP1 ;3
@skipP1:
     lda #0 ;2
     tay ;2, retained color-table skip convention
     bit vcs_standard_color_object_masks + 19 ;3, balance the active path
@continueP1:
NEW

replace_once(\$renderer, <<'OLD', <<'NEW', 'P1/M1 timing slot');
         lsr vcs_standard_color_object_masks + 1,x ;6
         lda #1 ;2, carry preserved
         adc #0 ;2, bit 1 becomes the enable result
         nop ;2
         sta ENAM1 ;3
OLD
         ; Faithful retained player1colors/playercolors behavior: M1 is
         ; absent, P1 receives the current logical-row color, and the delayed
         ; P0 color is committed in the exact former missile slot. Direct
         ; page-contained tables save the two cycles spent making Y safe.
         lda.ay vcs_standard_color_player1_colors,y ;4
         sta COLUP1 ;3
         lda vcs_standard_color_player0_latch ;3
         sta COLUP0 ;3
NEW

replace_once(\$renderer, <<'OLD', <<'NEW', 'P0 balanced graphics branch');
     cpy vcs_standard_color_object_masks + 11 ; exclusive height
     bcc.same @drawP0
     lda vcs_standard_color_object_masks + 19 ; permanent zero
     jmp @continueP0
@drawP0:
     lda (vcs_standard_color_player0_graphics),y
@continueP0:
OLD
     cpy vcs_standard_color_object_masks + 11 ; exclusive height
     bcs.same @skipP0
     lda (vcs_standard_color_player0_graphics),y
     jmp @continueP0
@skipP0:
     lda #0
     tay
     bit vcs_standard_color_object_masks + 19
@continueP0:
NEW

replace_once(\$renderer, <<'OLD', <<'NEW', 'P0/M0 timing slot');
             lsr vcs_standard_color_object_masks + 2,x ;6
             lda #1 ;2, carry preserved
             adc #0 ;2, bit 1 becomes the enable result
             sta.a ENAM0 ;4
OLD
             ; Faithful retained playercolors behavior: M0 is absent and
             ; the next delayed P0 row color is staged in the former missile
             ; timing slot.
             lda.ay vcs_standard_color_player0_colors,y ;4
             sta vcs_standard_color_player0_latch ;3
             clc ;2, preserve the legal row-advance carry contract
             SLEEP 3
NEW

replace_once(\$renderer, <<'OLD', <<'NEW', 'final P1 color slot');
         lda vcs_standard_color_object_masks + 35
         bit vcs_standard_color_object_masks + 19
         nop
OLD
         lda vcs_standard_color_object_masks + 35
         sta COLUP1
         nop
NEW
replace_once(\$renderer, <<'OLD', <<'NEW', 'final delayed P0 color commit');
         SLEEP 4
         sta ENAM1 ;3
OLD
         lda.a vcs_standard_color_player0_latch
         sta COLUP0
NEW
replace_once(\$renderer, <<'OLD', <<'NEW', 'final P0 color stage');
         lda vcs_standard_color_object_masks + 43
         bit vcs_standard_color_object_masks + 19
         bit vcs_standard_color_object_masks + 19
         nop
         sta ENAM0 ;3
OLD
         lda vcs_standard_color_object_masks + 43
         sta vcs_standard_color_player0_latch
         SLEEP 8
NEW

replace_once(\$renderer, <<'OLD', <<'NEW', 'missile-Y restoration block');
         lda vcs_standard_color_pointer_workspace + 11
         sta vcs_standard_color_missile1_y
             lda vcs_standard_color_pointer_workspace + 10
             sta vcs_standard_color_missile0_y
     lda vcs_standard_color_object_masks + 7
OLD
     lda vcs_standard_color_object_masks + 7
NEW

replace_once(\$renderer, <<'OLD', <<'NEW', 'VBLANK missile disable slot');
     sta HMOVE ;+3 3


     ;set score pointers
OLD
     sta HMOVE ;+3 3

     ; This profile deliberately has no missiles. Clear both enable registers
     ; during VBLANK even if application code touched them.
     lda #0
     sta ENAM0
     sta ENAM1

     ;set score pointers
NEW

my $proc_start = index($renderer, '.proc vcs_standard_color_prepare_object_masks');
$proc_start >= 0 or die "could not find color mask-preparation procedure\n";
my $proc_end = index($renderer, '.endproc', $proc_start);
$proc_end >= 0 or die "could not find color mask-preparation end\n";
$proc_end += length('.endproc');
my $new_proc = <<'ASM';
.proc vcs_standard_color_prepare_object_masks
.export vcs_standard_color_prepare_object_masks

     ; The retained five-strobe horizontal-position schedule still touches the
     ; absent missile slots. Keep both private coordinates bounded and stable.
     lda #0
     sta vcs_standard_color_object_x + 2
     sta vcs_standard_color_object_x + 3

; The sparse 44-byte layout preserves the visible loop's X=0,4,...,40 index
; and therefore its exact ball timing. Former missile slots now hold the two
; final-row colors; all other missile-mask bytes stay zero.

     ldy #0
     ldx #0
@clear:
     sty vcs_standard_color_object_masks,x
     sty vcs_standard_color_object_masks + 1,x
     sty vcs_standard_color_object_masks + 2,x
     txa
     clc
     adc #4
     tax
     cpx #44
     bcc @clear

     lda #87
     sta vcs_standard_color_object_masks + 31
     lda vcs_standard_color_ball_y
     ldy vcs_standard_color_ball_height
     ldx #0
     jsr @prepare_one

     lda vcs_standard_color_ball_y
     sta vcs_standard_color_object_masks + 7
     sec
     sbc #87
     sta vcs_standard_color_ball_y

     lda vcs_standard_color_player0_height
     clc
     adc #1
     sta vcs_standard_color_object_masks + 11
     lda vcs_standard_color_player1_height
     clc
     adc #1
     sta vcs_standard_color_object_masks + 15
     lda #0
     sta vcs_standard_color_object_masks + 19
     lda #1
     sta vcs_standard_color_object_masks + 23

     ; Precompute the five final-row values before visible drawing. Colors use
     ; the same storage-order index as their corresponding graphics row. When a
     ; player is absent, Y=0 reproduces the retained skip-path convention.
     lda vcs_standard_color_ball_height
     dec vcs_standard_color_ball_y
     cmp vcs_standard_color_ball_y
     rol
     rol
     sta vcs_standard_color_object_masks + 27

     lda vcs_standard_color_player1_y
     sec
     sbc #89
     tay
     cpy vcs_standard_color_object_masks + 15
     bcs @final_player1_zero
     lda (vcs_standard_color_player1_graphics),y
     sta vcs_standard_color_object_masks + 31
     lda.ay vcs_standard_color_player1_colors,y
     jmp @final_player1_color
@final_player1_zero:
     ldy #0
     lda #0
     sta vcs_standard_color_object_masks + 31
     lda.ay vcs_standard_color_player1_colors,y
@final_player1_color:
     sta vcs_standard_color_object_masks + 35

     lda vcs_standard_color_player0_y
     sec
     sbc #89
     tay
     cpy vcs_standard_color_object_masks + 11
     bcs @final_player0_zero
     lda (vcs_standard_color_player0_graphics),y
     sta vcs_standard_color_object_masks + 39
     lda.ay vcs_standard_color_player0_colors,y
     jmp @final_player0_color
@final_player0_zero:
     ldy #0
     lda #0
     sta vcs_standard_color_object_masks + 39
     lda.ay vcs_standard_color_player0_colors,y
@final_player0_color:
     sta vcs_standard_color_object_masks + 43
     rts

@prepare_one:
     sta vcs_standard_color_object_masks + 11
     stx vcs_standard_color_object_masks + 3
     sty vcs_standard_color_object_masks + 35
     sec
     sbc vcs_standard_color_object_masks + 35
     sta vcs_standard_color_object_masks + 7
     sta vcs_standard_color_object_masks + 39
     cmp vcs_standard_color_object_masks + 11
     bcc @no_wrap
     beq @no_wrap

     lda vcs_standard_color_object_masks + 11
     beq @wrapped_high
     cmp vcs_standard_color_object_masks + 31
     bcc @wrapped_low_ready
     beq @wrapped_low_ready
     lda vcs_standard_color_object_masks + 31
     sta vcs_standard_color_object_masks + 11
@wrapped_low_ready:
     lda #1
     sta vcs_standard_color_object_masks + 7
     jsr @set_range

@wrapped_high:
     lda vcs_standard_color_object_masks + 39
     cmp vcs_standard_color_object_masks + 31
     bcc @wrapped_high_ready
     beq @wrapped_high_ready
     rts
@wrapped_high_ready:
     sta vcs_standard_color_object_masks + 7
     lda vcs_standard_color_object_masks + 31
     sta vcs_standard_color_object_masks + 11
     jsr @set_range
     rts

@no_wrap:
     lda vcs_standard_color_object_masks + 7
     bne @no_wrap_first_ready
     lda #1
     sta vcs_standard_color_object_masks + 7
@no_wrap_first_ready:
     lda vcs_standard_color_object_masks + 11
     cmp vcs_standard_color_object_masks + 31
     bcc @no_wrap_last_ready
     beq @no_wrap_last_ready
     lda vcs_standard_color_object_masks + 31
     sta vcs_standard_color_object_masks + 11
@no_wrap_last_ready:
     lda vcs_standard_color_object_masks + 7
     cmp vcs_standard_color_object_masks + 11
     bcc @set_range
     beq @set_range
     rts

@set_range:
     lda vcs_standard_color_object_masks + 7
     sec
     sbc #1
     tay
     and #7
     tax
     lda @start_bits,x
     sta vcs_standard_color_object_masks + 23
     tya
     lsr
     lsr
     lsr
     sta vcs_standard_color_object_masks + 15

     lda vcs_standard_color_object_masks + 11
     sec
     sbc #1
     tay
     and #7
     tax
     lda @end_bits,x
     sta vcs_standard_color_object_masks + 27
     tya
     lsr
     lsr
     lsr
     sta vcs_standard_color_object_masks + 19

     lda vcs_standard_color_object_masks + 15
     asl
     asl
     clc
     adc vcs_standard_color_object_masks + 3
     tax
     lda vcs_standard_color_object_masks + 15
     cmp vcs_standard_color_object_masks + 19
     bne @range_many
     lda vcs_standard_color_object_masks + 23
     and vcs_standard_color_object_masks + 27
     ora vcs_standard_color_object_masks,x
     sta vcs_standard_color_object_masks,x
     rts

@range_many:
     lda vcs_standard_color_object_masks,x
     ora vcs_standard_color_object_masks + 23
     sta vcs_standard_color_object_masks,x
     inc vcs_standard_color_object_masks + 15
@range_middle:
     lda vcs_standard_color_object_masks + 15
     cmp vcs_standard_color_object_masks + 19
     bcs @range_last
     txa
     clc
     adc #4
     tax
     lda #$ff
     sta vcs_standard_color_object_masks,x
     inc vcs_standard_color_object_masks + 15
     jmp @range_middle
@range_last:
     txa
     clc
     adc #4
     tax
     lda vcs_standard_color_object_masks,x
     ora vcs_standard_color_object_masks + 27
     sta vcs_standard_color_object_masks,x
     rts

@start_bits:
     .byte $ff,$fe,$fc,$f8,$f0,$e0,$c0,$80
@end_bits:
     .byte $01,$03,$07,$0f,$1f,$3f,$7f,$ff
.endproc
ASM
substr($renderer, $proc_start, $proc_end - $proc_start, $new_proc);

$macros =~ s!standard_4k_ntsc/normalize\.pl!standard_4k_ntsc_playercolors/normalize.pl!g;
$macros =~ s/standard_4k_ntsc/standard_4k_ntsc_playercolors/g;

# Every retained conditional branch in this normalized renderer has been
# audited for the ordinary same-page taken-branch timing.  Stamp branches
# introduced by the player-color transforms too, so regeneration cannot
# silently reintroduce layout-dependent cycle counts.
$renderer =~ s/^(\s*b(?:cc|cs|eq|mi|ne|pl|vc|vs))(\s+)/$1.same$2/mg;

sub emit_or_check {
   my ($name, $content) = @_;
   my $path = File::Spec->catfile($output_dir, $name);
   if ($check) {
      -f $path or die "$path is missing\n";
      my $actual = slurp($path);
      $actual eq $content or die "$path is stale; run $0\n";
      return;
   }
   open(my $fh, '>:raw', $path) or die "could not write $path: $!\n";
   print {$fh} $content;
   close($fh) or die "could not close $path: $!\n";
}

emit_or_check('standard_4k_ntsc_playercolors_renderer.s26', $renderer);
emit_or_check('standard_4k_ntsc_playercolors_macros.inc', $macros);
print $check ? "standard_4k_ntsc_playercolors normalization current\n" :
               "standard_4k_ntsc_playercolors normalized\n";
