#!/usr/bin/env perl
# This file is covered under CC0-1.0. See libraries/LICENSE.txt.
use strict;
use warnings;
use Getopt::Long qw(GetOptions);
use File::Basename qw(basename);

my $bank;
my $page = 1;
my $license;
my $help = 0;

GetOptions(
    'bank=s' => \$bank,
    'page!'  => \$page,
    'license=s' => \$license,
    'help'   => \$help,
) or usage();

usage() if $help;
@ARGV == 4 or usage();

my ($font_file, $out_file, $array_name, $characters) = @ARGV;

$array_name =~ /^[A-Za-z_][A-Za-z0-9_]*$/
    or die "$0: invalid C26 array name '$array_name'\n";

if (defined $bank) {
    $bank =~ /^[A-Za-z_][A-Za-z0-9_]*$/
        or die "$0: invalid bank qualifier '$bank'\n";
}

open my $fh, '<', $font_file
    or die "$0: cannot open '$font_file': $!\n";

my %glyph;
my ($code, $font_width, $font_height);
my $license_line;

while (my $line = <$fh>) {
    if (!defined($license_line) && $line =~ /^\s*\/\/\s*This font is covered under\b/) {
        chomp($license_line = $line);
    }

    if ($line =~ m{//\s*0x([0-9A-Fa-f]{2})\b}) {
        $code = hex($1);
        next;
    }

    next unless defined $code;
    next unless $line =~ /\bVCS_FONT_GLYPH\s*\(/;

    my @rows;
    while (my $row = <$fh>) {
        last if $row =~ /^\s*\)/;
        push @rows, $1 if $row =~ /0b([.X01]+)/;
    }

    @rows
        or die sprintf("%s: glyph 0x%02X has no bitmap rows\n", $0, $code);

    my $width = length $rows[0];
    my $height = scalar @rows;
    for my $row (@rows) {
        length($row) == $width
            or die sprintf("%s: glyph 0x%02X has inconsistent row widths\n", $0, $code);
    }

    if (!defined $font_width) {
        ($font_width, $font_height) = ($width, $height);
    } else {
        $width == $font_width
            or die sprintf("%s: glyph 0x%02X width %d; expected %d\n",
                           $0, $code, $width, $font_width);
        $height == $font_height
            or die sprintf("%s: glyph 0x%02X height %d; expected %d\n",
                           $0, $code, $height, $font_height);
    }

    $glyph{$code} = \@rows;
    undef $code;
}
close $fh;

defined $font_height
    or die "$0: no VCS_FONT_GLYPH data found in '$font_file'\n";
$font_height <= 26
    or die "$0: source font is $font_height rows high; maximum supported is 26\n";

my @codes = unpack('C*', $characters);
@codes or die "$0: character subset may not be empty\n";
for my $c (@codes) {
    exists $glyph{$c}
        or die sprintf("%s: font is missing glyph 0x%02X (%s)\n",
                       $0, $c, printable($c));
}

my $alias = uc($array_name) . '_GLYPH';
$alias =~ s/[^A-Z0-9_]/_/g;
my @args = map { chr(ord('a') + $_) } 0 .. $font_height - 1;
my $bytes = scalar(@codes) * $font_height;
my @qualifiers;
push @qualifiers, $bank if defined $bank;
push @qualifiers, 'page' if $page;
push @qualifiers, 'const uint8_t';

my $tmp = "$out_file.tmp.$$";
open my $out, '>', $tmp
    or die "$0: cannot create '$tmp': $!\n";

print {$out} "// Generated by libraries/vcs/fonts/make_font_subset.pl; do not edit.\n";
print {$out} "// Source font: ", basename($font_file), "\n";
print {$out} "// Characters: ", comment_string($characters), "\n";
if (defined $license) {
    print {$out} "// This file is covered under CC0-1.0. See $license.\n\n";
} else {
    print {$out} ($license_line // '// This font is covered under CC0-1.0. See libraries/LICENSE.txt.'), "\n\n";
}
print {$out} "alias $alias(", join(',', @args), ") ", join(',', reverse @args), "\n\n";
print {$out} join(' ', @qualifiers), " $array_name\[$bytes\] := {\n";

for my $i (0 .. $#codes) {
    my $c = $codes[$i];
    my $rows = $glyph{$c};
    printf {$out} "   // 0x%02X %s\n", $c, glyph_name($c);
    print {$out} "   $alias(\n";
    for my $row (0 .. $font_height - 1) {
        my $comma = $row == $font_height - 1 ? '' : ',';
        print {$out} "      0b$rows->[$row]$comma\n";
    }
    my $comma = $i == $#codes ? '' : ',';
    print {$out} "   )$comma\n";
}
print {$out} "};\n";
close $out or die "$0: cannot close '$tmp': $!\n";
rename $tmp, $out_file
    or die "$0: cannot replace '$out_file': $!\n";

print "$out_file\n";
exit 0;

sub usage {
    die <<'USAGE';
usage: make_font_subset.pl [--bank NAME] [--[no-]page] [--license PATH] FONTFILE OUTPUT ARRAY CHARS

Extract CHARS, in exactly the supplied order, from a canonical C26 ASCII font.
The generated OUTPUT defines ARRAY and is intended to be checked into source
control.  `page` is emitted by default; use --no-page when placement must not be
page-constrained.  --bank adds a bank qualifier such as bank0 or bank3.
--license emits an example/file CC0 notice for generated files outside fonts/.
USAGE
}

sub printable {
    my ($c) = @_;
    return 'space' if $c == 0x20;
    return chr($c) if $c >= 0x21 && $c <= 0x7e;
    return sprintf('0x%02X', $c);
}

sub glyph_name {
    my ($c) = @_;
    return 'space' if $c == 0x20;
    return printable($c);
}

sub comment_string {
    my ($s) = @_;
    $s =~ s/\\/\\\\/g;
    $s =~ s/"/\\"/g;
    $s =~ s/([^\x20-\x7e])/sprintf('\\x%02X', ord($1))/ge;
    return qq{"$s"};
}
