#!/usr/bin/env perl
# This file is covered under CC0-1.0. See examples/LICENSE.txt.
use strict;
use warnings;
use FindBin qw($Bin);

my $lower_banks = 255;
my $banks_per_object = 32;  # 32 x 2K = one 16-bit O26 packed CODE namespace.
my $ram_banks = 256;        # Stella 7.0 3EX: 256 x 1K = 256K.
my $ram_group = 32;         # Keep each swapram backing/accessor TU <= 32K BSS.
my $lfsr_seed = 0xACE1;
my $lfsr_tap_mask = 0xB400; # x^16 + x^14 + x^13 + x^11 + 1.
my (@wait_font_bytes, @status_font_bytes, @cart_font_bytes);

sub lfsr_next_value {
   my ($v) = @_;
   return (($v >> 1) ^ (($v & 1) ? $lfsr_tap_mask : 0)) & 0xffff;
}

# Prove the recurrence is maximal, then prove all 256 generated 1K bank images
# are distinct.  The stored byte is LFSR-low XOR logical RAM-bank number; the
# LFSR itself remains one continuous stream across all 256K.
{
   my $l = $lfsr_seed;
   my $period = 0;
   do {
      $l = lfsr_next_value($l);
      ++$period;
      die "$0: LFSR failed to return to its seed within 65535 steps\n" if $period > 65535;
   } while ($l != $lfsr_seed);
   die "$0: LFSR period is $period, expected 65535\n" unless $period == 65535;

   $l = $lfsr_seed;
   my %seen;
   for my $bank (0 .. $ram_banks - 1) {
      my $image = '';
      for (1 .. 1024) {
         $image .= chr(($l & 0xff) ^ $bank);
         $l = lfsr_next_value($l);
      }
      die "$0: RAM bank $bank duplicates bank $seen{$image}\n" if exists $seen{$image};
      $seen{$image} = $bank;
   }
   die sprintf("%s: 256K LFSR endpoint is %04X, expected 1C4E\n", $0, $l)
      unless $l == 0x1c4e;
}

sub generated_header {
   my ($fh, $detail) = @_;
   print {$fh} "; Generated by make_torture.pl; do not edit.\n";
   print {$fh} "; This file is covered under CC0-1.0. See examples/LICENSE.txt.\n;\n";
   print {$fh} "; Maximum-size Tigervision 3EX torture payload. $detail\n";
   print {$fh} "; Cross-bank calls execute a tiny inline descriptor stub from RIOT RAM so\n";
   print {$fh} "; the full 255 x 255 ordered matrix fits in one 512K cartridge.\n\n";
}

sub read_subset_bytes {
   my ($path, $expected_bytes, $rows_per_glyph) = @_;
   $rows_per_glyph //= 16;
   open my $fh, '<', $path or die "$0: cannot read $path: $!\n";
   my @rows;
   while (my $line = <$fh>) { push @rows, $1 if $line =~ /0b([.X01]{8})/; }
   close $fh;
   @rows % $rows_per_glyph == 0 or die "$0: $path incomplete glyphs\n";
   my @bytes;
   while (@rows) {
      my @glyph = splice @rows, 0, $rows_per_glyph;
      for my $row (reverse @glyph) {
         $row =~ tr/.X/01/;
         push @bytes, oct("0b$row");
      }
   }
   @bytes == $expected_bytes
      or die "$0: $path contains " . scalar(@bytes) . " bytes; expected $expected_bytes\n";
   return @bytes;
}

sub emit_bytes {
   my ($fh, $bytes) = @_;
   for (my $i = 0; $i < @$bytes; $i += 16) {
      my $last = $i + 15; $last = $#$bytes if $last > $#$bytes;
      print {$fh} "    .byte ", join(', ', map { sprintf '$%02X', $_ } @$bytes[$i .. $last]), "\n";
   }
}

sub emit_lfsr_advance {
   my ($fh, $tag) = @_;
   print {$fh} "    lda ram_lfsr+1\n";
   print {$fh} "    lsr\n";
   print {$fh} "    sta ram_lfsr+1\n";
   print {$fh} "    lda ram_lfsr\n";
   print {$fh} "    ror\n";
   print {$fh} "    sta ram_lfsr\n";
   print {$fh} "    bcc.same ${tag}_lfsr_done\n";
   print {$fh} "    lda ram_lfsr+1\n";
   print {$fh} "    eor #\$b4\n";
   print {$fh} "    sta ram_lfsr+1\n";
   print {$fh} "${tag}_lfsr_done:\n";
}

sub emit_ram_advance {
   my ($fh, $logical, $tag, $write_phase) = @_;
   print {$fh} "    inc ram_index\n";
   print {$fh} "    bne.same ${tag}_index_low_ok\n";
   print {$fh} "    inc ram_index+1\n";
   print {$fh} "${tag}_index_low_ok:\n";
   print {$fh} "    lda ram_index+1\n";
   print {$fh} "    cmp #4\n";
   print {$fh} "    bne.same ${tag}_continue\n";
   print {$fh} "    lda #0\n";
   print {$fh} "    sta ram_index\n";
   print {$fh} "    sta ram_index+1\n";
   if ($logical < 255) {
      printf {$fh} "    lda #\$%02X\n", $logical + 1;
      print {$fh} "    sta ram_bank\n";
      print {$fh} "    rts\n";
   }
   elsif ($write_phase) {
      print {$fh} "    sta ram_bank\n";
      print {$fh} "    lda #2\n";
      print {$fh} "    sta ram_phase\n";
      print {$fh} "    lda #\$e1\n";
      print {$fh} "    sta ram_lfsr\n";
      print {$fh} "    lda #\$ac\n";
      print {$fh} "    sta ram_lfsr+1\n";
      print {$fh} "    rts\n";
   }
   else {
      print {$fh} "    sta ram_bank\n";
      print {$fh} "    lda #3\n";
      print {$fh} "    sta ram_phase\n";
      print {$fh} "    lda #1\n";
      print {$fh} "    sta torture_done\n";
      print {$fh} "    rts\n";
   }
   print {$fh} "${tag}_continue:\n";
}

sub emit_ram_wrapper {
   my ($fh, $logical, $label) = @_;
   my $hex = sprintf('%02d', $logical);
   my $tag = "ram${logical}_${label}";
   print {$fh} ".export $label\n$label:\n";
   print {$fh} "    lda ram_phase\n    cmp #1\n    beq.same ${tag}_write\n";
   print {$fh} "    lda torture_batch\n    sta step_remaining\n${tag}_verify:\n";
   printf {$fh} "    jsr ram_read_%03d\n", $logical;
   print {$fh} "    lda ram_lfsr\n";
   printf {$fh} "    eor #\$%02X\n", $logical;
   print {$fh} "    cmp ram_value\n    beq.same ${tag}_verify_ok\n";
   print {$fh} "    lda failure\n    bne.same ${tag}_verify_ok\n";
   print {$fh} "    lda #\$80\n    sta failure\n";
   printf {$fh} "    lda #\$%02X\n", $logical;
   print {$fh} "    sta ram_failure_bank\n${tag}_verify_ok:\n";
   emit_lfsr_advance($fh, "${tag}_v");
   emit_ram_advance($fh, $logical, "${tag}_v", 0);
   print {$fh} "    dec step_remaining\n    bne.same ${tag}_verify\n    rts\n";

   print {$fh} "${tag}_write:\n    lda torture_batch\n    sta step_remaining\n${tag}_write_loop:\n";
   print {$fh} "    lda ram_lfsr\n";
   printf {$fh} "    eor #\$%02X\n", $logical;
   print {$fh} "    sta ram_value\n";
   printf {$fh} "    jsr ram_write_%03d\n", $logical;
   emit_lfsr_advance($fh, "${tag}_w");
   emit_ram_advance($fh, $logical, "${tag}_w", 1);
   print {$fh} "    dec step_remaining\n    bne.same ${tag}_write_loop\n    rts\n\n";
}

sub emit_bank {
   my ($fh, $bank, $link_root) = @_;
   printf {$fh} ".segmentalign \"CODE.bank%d\", 256\n", $bank;
   printf {$fh} ".segment \"CODE.bank%d\"\n", $bank;
   printf {$fh} ".export bank%d_source, bank%d_target\n", $bank, $bank;
   printf {$fh} "bank%d_source:\n", $bank;
   print {$fh} "    tsx\n    stx source_sp\n";
   printf {$fh} "bank%d_dest_loop:\n", $bank;
   print {$fh} "    lda expected_dest\n";
   printf {$fh} "    cmp #\$%02X\n", $bank;
   printf {$fh} "    beq.same bank%d_same\n", $bank;
   print {$fh} "    sta bankcall_stub+5\n    jsr bankcall_stub\n";
   printf {$fh} "    jmp bank%d_after\n", $bank;
   printf {$fh} "bank%d_same:\n    jsr bank%d_target\n", $bank, $bank;
   printf {$fh} "bank%d_after:\n", $bank;
   printf {$fh} "    lda #\$%02X\n", $bank;
   print {$fh} "    cmp expected_source\n";
   printf {$fh} "    beq.same bank%d_restored\n", $bank;
   print {$fh} "    lda #\$02\n    sta failure\n";
   printf {$fh} "bank%d_restored:\n", $bank;
   print {$fh} "    inc expected_dest\n    lda expected_dest\n    cmp #\$FF\n";
   printf {$fh} "    beq.same bank%d_source_done\n", $bank;
   print {$fh} "    dec step_remaining\n";
   printf {$fh} "    bne.same bank%d_dest_loop\n    jmp bank%d_step_done\n", $bank, $bank;
   printf {$fh} "bank%d_source_done:\n", $bank;
   print {$fh} "    lda ram_lfsr\n    sta bankcall_stub+3\n    lda ram_lfsr+1\n    sta bankcall_stub+4\n";
   print {$fh} "    lda #\$ff\n    sta bankcall_stub+5\n    jsr bankcall_stub\n";
   print {$fh} "    lda #<\$1100\n    sta bankcall_stub+3\n    lda #>\$1100\n    sta bankcall_stub+4\n";
   printf {$fh} "    lda #\$%02X\n", $bank;
   print {$fh} "    cmp expected_source\n";
   printf {$fh} "    beq.same bank%d_fixed_restored\n", $bank;
   print {$fh} "    lda #\$03\n    sta failure\n";
   printf {$fh} "bank%d_fixed_restored:\n", $bank;
   printf {$fh} "bank%d_step_done:\n", $bank;
   print {$fh} "    tsx\n    cpx source_sp\n";
   printf {$fh} "    beq.same bank%d_source_stack_ok\n", $bank;
   print {$fh} "    lda #\$04\n    sta failure\n";
   printf {$fh} "bank%d_source_stack_ok:\n    rts\n", $bank;

   print {$fh} "    .align 256\n";
   printf {$fh} "bank%d_target:\n", $bank;
   print {$fh} "    lda expected_dest\n";
   printf {$fh} "    cmp #\$%02X\n", $bank;
   printf {$fh} "    beq.same bank%d_target_ok\n", $bank;
   print {$fh} "    lda #\$01\n    sta failure\n";
   printf {$fh} "bank%d_target_ok:\n", $bank;
   print {$fh} "    inc torture_count\n";
   printf {$fh} "    bne.same bank%d_target_count_ok\n", $bank;
   print {$fh} "    inc torture_count+1\n";
   printf {$fh} "bank%d_target_count_ok:\n    rts\n", $bank;

   if ($link_root) { printf {$fh} "bank%d_link_root:\n    rts\n", $bank; }

   # One common wrapper address ($1200) per selectable ROM bank.  RAM bank255
   # has no lower ROM bank255 (descriptor $FF means fixed ROM), so its wrapper
   # occupies a second page ($1300) in lower ROM bank250.
   print {$fh} "    .align 256\n";
   emit_ram_wrapper($fh, $bank, sprintf('bank%d_ram_entry', $bank));
   if ($bank == 250) {
      print {$fh} "    .align 256\n";
      emit_ram_wrapper($fh, 255, 'bank250_ram255_entry');
   }

   if ($bank == 31) {
      print {$fh} <<'RAM_DISPATCH';
; One cross-lower-bank call per bounded RAM batch.  Each destination wrapper
; performs 4 (VBLANK) or 3 (overscan) compiler-lowered swapram byte accesses
; before returning, instead of paying this dispatch cost for every byte.
step_3ex_max_ram:
    lda #<$1780
    sta bankcall_stub+1
    lda #>$1780
    sta bankcall_stub+2
    lda ram_bank
    cmp #$ff
    beq.same ram_dispatch_255
    sta bankcall_stub+5
    lda #<$1200
    sta bankcall_stub+3
    lda #>$1200
    sta bankcall_stub+4
    jsr bankcall_stub
    rts
ram_dispatch_255:
    lda #$fa
    sta bankcall_stub+5
    lda #<$1300
    sta bankcall_stub+3
    lda #>$1300
    sta bankcall_stub+4
    jsr bankcall_stub
    rts

ram_walk_reset:
    lda #0
    sta ram_bank
    sta ram_index
    sta ram_index+1
    sta ram_failure_bank
    lda #$e1
    sta ram_lfsr
    lda #$ac
    sta ram_lfsr+1
    rts
RAM_DISPATCH
   }

   if ($bank == 251) {
      print {$fh} "    .align 256\ncart_type_glyphs:\n";
      emit_bytes($fh, \@cart_font_bytes);
      print {$fh} <<'CART_LOADER';
load_mapper_type:
    lda #<{cart_type_glyphs + 0}
    sta cart_type_pointers+0
    lda #>{cart_type_glyphs + 0}
    sta cart_type_pointers+1
    lda #<{cart_type_glyphs + 8}
    sta cart_type_pointers+2
    lda #>{cart_type_glyphs + 8}
    sta cart_type_pointers+3
    lda #<{cart_type_glyphs + 16}
    sta cart_type_pointers+4
    lda #>{cart_type_glyphs + 16}
    sta cart_type_pointers+5
    lda #<{cart_type_glyphs + 24}
    sta cart_type_pointers+6
    lda #>{cart_type_glyphs + 24}
    sta cart_type_pointers+7
    lda #<{cart_type_glyphs + 32}
    sta cart_type_pointers+8
    lda #>{cart_type_glyphs + 32}
    sta cart_type_pointers+9
    lda #<{cart_type_glyphs + 40}
    sta cart_type_pointers+10
    lda #>{cart_type_glyphs + 40}
    sta cart_type_pointers+11
    rts
CART_LOADER
   }

   if ($bank == 252) {
      print {$fh} <<'INIT_LOADER';
init_3ex_max_torture:
    lda #0
    sta failure
    sta torture_count
    sta torture_count+1
    sta expected_source
    sta expected_dest
    sta torture_done
    sta ram_phase
    sta ram_failure_bank
    lda _vcsc_ptr0
    lda #$20
    sta bankcall_stub
    lda #<$1780
    sta bankcall_stub+1
    lda #>$1780
    sta bankcall_stub+2
    lda #<$1100
    sta bankcall_stub+3
    lda #>$1100
    sta bankcall_stub+4
    lda #0
    sta bankcall_stub+5
    lda #$60
    sta bankcall_stub+6
    rts

torture_object_roots:
    jsr bank0_link_root
    .banktarget bank0_link_root
    jsr bank32_link_root
    .banktarget bank32_link_root
    jsr bank64_link_root
    .banktarget bank64_link_root
    jsr bank96_link_root
    .banktarget bank96_link_root
    jsr bank128_link_root
    .banktarget bank128_link_root
    jsr bank160_link_root
    .banktarget bank160_link_root
    jsr bank192_link_root
    .banktarget bank192_link_root
    rts
INIT_LOADER
   }

   if ($bank == 253) {
      print {$fh} "    .align 256\nwait_glyphs:\n";
      emit_bytes($fh, \@wait_font_bytes);
      print {$fh} <<'WAIT_LOADER';
load_wait:
    lda #<{wait_glyphs + 16}
    sta status_result_pointers+0
    lda #>{wait_glyphs + 16}
    sta status_result_pointers+1
    lda #<{wait_glyphs + 32}
    sta status_result_pointers+2
    lda #>{wait_glyphs + 32}
    sta status_result_pointers+3
    lda #<{wait_glyphs + 48}
    sta status_result_pointers+4
    lda #>{wait_glyphs + 48}
    sta status_result_pointers+5
    lda #<{wait_glyphs + 64}
    sta status_result_pointers+6
    lda #>{wait_glyphs + 64}
    sta status_result_pointers+7
    lda #<wait_glyphs
    sta status_result_pointers+8
    lda #>wait_glyphs
    sta status_result_pointers+9
    lda spinner_index
    asl
    asl
    asl
    asl
    clc
    adc #<{wait_glyphs + 80}
    sta status_result_pointers+10
    lda #>{wait_glyphs + 80}
    adc #0
    sta status_result_pointers+11
    rts
WAIT_LOADER
   }
   elsif ($bank == 254) {
      print {$fh} "    .align 256\nstatus_glyphs:\n";
      emit_bytes($fh, \@status_font_bytes);
      print {$fh} <<'STATUS_LOADERS';
load_pass:
    lda #<status_glyphs
    sta status_result_pointers+0
    lda #>status_glyphs
    sta status_result_pointers+1
    lda #<{status_glyphs + 16}
    sta status_result_pointers+2
    lda #>{status_glyphs + 16}
    sta status_result_pointers+3
    lda #<{status_glyphs + 32}
    sta status_result_pointers+4
    lda #>{status_glyphs + 32}
    sta status_result_pointers+5
    lda #<{status_glyphs + 48}
    sta status_result_pointers+6
    lda #>{status_glyphs + 48}
    sta status_result_pointers+7
    lda #<{status_glyphs + 48}
    sta status_result_pointers+8
    lda #>{status_glyphs + 48}
    sta status_result_pointers+9
    lda #<status_glyphs
    sta status_result_pointers+10
    lda #>status_glyphs
    sta status_result_pointers+11
    rts

load_fail:
    lda #<status_glyphs
    sta status_result_pointers+0
    lda #>status_glyphs
    sta status_result_pointers+1
    lda #<{status_glyphs + 64}
    sta status_result_pointers+2
    lda #>{status_glyphs + 64}
    sta status_result_pointers+3
    lda #<{status_glyphs + 80}
    sta status_result_pointers+4
    lda #>{status_glyphs + 80}
    sta status_result_pointers+5
    lda #<{status_glyphs + 96}
    sta status_result_pointers+6
    lda #>{status_glyphs + 96}
    sta status_result_pointers+7
    lda #<{status_glyphs + 112}
    sta status_result_pointers+8
    lda #>{status_glyphs + 112}
    sta status_result_pointers+9
    lda #<status_glyphs
    sta status_result_pointers+10
    lda #>status_glyphs
    sta status_result_pointers+11
    rts
STATUS_LOADERS
   }
   print {$fh} "\n";
}

@wait_font_bytes = read_subset_bytes("$Bin/wait_font.c26", 144, 16);
@status_font_bytes = read_subset_bytes("$Bin/status_font.c26", 128, 16);
@cart_font_bytes = read_subset_bytes("$Bin/cart_type_font.c26", 48, 8);

# Generate eight compiler accessor TUs and eight 32K backing-storage objects.
for (my $group = 0; $group < 8; ++$group) {
   my $first = $group * $ram_group;
   my $last = $first + $ram_group - 1;
   my $cpath = sprintf "%s/3ex_max_swapram_%02d.c26", $Bin, $group;
   open my $cfh, '>', $cpath or die "$0: cannot write $cpath: $!\n";
   print {$cfh} "// Generated by make_torture.pl; do not edit.\n// This file is covered under CC0-1.0. See examples/LICENSE.txt.\n";
   print {$cfh} "instantiate \"3EX/mapper.c26\" as mapper (VCS_3EX_BANKS:=256)\n\n";
   print {$cfh} "extern uint16_t ram_index;\nextern uint8_t ram_value;\n\n";
   for my $bank ($first .. $last) { printf {$cfh} "extern swapram uint8_t ram_%03d[1024];\n", $bank; }
   print {$cfh} "\n";
   for my $bank ($first .. $last) {
      my $rombank = $bank == 255 ? 250 : $bank;
      printf {$cfh} "bank%d void ram_write_%03d(void) { ram_%03d[ram_index] := ram_value; }\n", $rombank, $bank, $bank;
      printf {$cfh} "bank%d void ram_read_%03d(void) { ram_value := ram_%03d[ram_index]; }\n\n", $rombank, $bank, $bank;
   }
   close $cfh or die "$0: close $cpath: $!\n";

   my $spath = sprintf "%s/3ex_max_swapram_storage_%02d.s26", $Bin, $group;
   open my $sfh, '>', $spath or die "$0: cannot write $spath: $!\n";
   print {$sfh} "; Generated by make_torture.pl; do not edit.\n; This file is covered under CC0-1.0. See examples/LICENSE.txt.\n";
   print {$sfh} "; Backing storage for RAM banks $first..$last.\n";
   for my $bank ($first .. $last) {
      printf {$sfh} ".export ram_%03d\n.segment \"BSS.swapram.__vcsc_object\$ram_%03d\"\nram_%03d:\n    .res 1024\n\n", $bank, $bank, $bank;
   }
   close $sfh or die "$0: close $spath: $!\n";
}

# Split lower ROM banks into 32-bank O26 chunks.
my $chunk = 0;
for (my $first = 0; $first < $lower_banks; $first += $banks_per_object) {
   my $last = $first + $banks_per_object - 1; $last = $lower_banks - 1 if $last >= $lower_banks;
   my $path = sprintf "%s/3ex_max_torture_%02d.s26", $Bin, $chunk++;
   open my $fh, '>', $path or die "$0: cannot write $path: $!\n";
   generated_header($fh, "This object contains lower banks $first through $last.");
   print {$fh} ".import failure, torture_count, expected_source, expected_dest, source_sp, step_remaining\n";
   print {$fh} ".import torture_done, torture_batch, ram_phase, ram_bank, ram_index, ram_value, ram_lfsr, ram_failure_bank\n";
   print {$fh} ".import bankcall_stub\n";
   for my $bank ($first .. $last) {
      printf {$fh} ".import ram_write_%03d, ram_read_%03d\n", $bank, $bank;
      if ($bank == 250) { print {$fh} ".import ram_write_255, ram_read_255\n"; }
   }
   if ($first <= 254 && $last >= 253) {
      print {$fh} ".import status_result_pointers, spinner_index\n.export load_wait, load_pass, load_fail\n";
   }
   if ($first <= 251 && $last >= 251) {
      print {$fh} ".import cart_type_pointers\n.export load_mapper_type\n";
   }
   if ($first <= 252 && $last >= 252) {
      for (my $root = 0; $root < 224; $root += $banks_per_object) { printf {$fh} ".import bank%d_link_root\n", $root; }
      print {$fh} ".importzp _vcsc_ptr0\n.export init_3ex_max_torture\n";
   }
   if ($first == 0) { print {$fh} ".export bank0_link_root\n"; }
   else { printf {$fh} ".export bank%d_link_root\n", $first; }
   if ($first <= 31 && $last >= 31) { print {$fh} ".export step_3ex_max_ram, ram_walk_reset\n"; }
   print {$fh} "\n";
   for my $bank ($first .. $last) { emit_bank($fh, $bank, $bank == $first); }
   close $fh or die "$0: close $path: $!\n";
}

my $fixed_path = "$Bin/3ex_max_torture_fixed.s26";
open my $fixed, '>', $fixed_path or die "$0: cannot write $fixed_path: $!\n";
generated_header($fixed, "This object contains the fixed-bank ROM scheduler.");
print {$fixed} ".import failure, torture_count, expected_source, expected_dest, fixed_sp\n";
print {$fixed} ".import torture_done, torture_batch, step_remaining, ram_phase, ram_lfsr, bankcall_stub\n";
print {$fixed} ".import step_3ex_max_ram, ram_walk_reset, init_3ex_max_torture\n";
print {$fixed} ".export fixed_probe, finish_3ex_max_init, step_3ex_max_torture, __vcsc_3ex_max_fast_entry, __vcsc_3ex_max_fast_done\n\n.segment \"CODE.bank255\"\n\n";
print {$fixed} <<'FIXED';
.segment "CODE.bank255.fixed_probe"
fixed_probe:
    inc torture_count
    bne.same fixed_probe_count_ok
    inc torture_count+1
fixed_probe_count_ok:
    rts

; Regression-only fast entry.  The visible diagnostic deliberately throttles
; torture work to VBLANK/overscan; tests can patch only the reset vector to
; enter here and execute the exact same ROM/RAM scheduler without frame pacing.
.segment "CODE.bank255.fast_test"
__vcsc_3ex_max_fast_entry:
    jsr init_3ex_max_torture
    .banktarget init_3ex_max_torture
    jsr finish_3ex_max_init
fast_test_loop:
    lda #$ff
    sta torture_batch
    jsr step_3ex_max_torture
    lda torture_done
    beq.same fast_test_loop
__vcsc_3ex_max_fast_done:
    jmp __vcsc_3ex_max_fast_done

.segment "CODE.bank255.finish_init"
finish_3ex_max_init:
    lda #<fixed_probe
    sta ram_lfsr
    lda #>fixed_probe
    sta ram_lfsr+1
    rts

.segment "CODE.bank255.rom_scheduler"
step_3ex_max_torture:
    lda torture_done
    bne.same step_return
    lda ram_phase
    beq.same rom_phase
    jsr step_3ex_max_ram
    .banktarget step_3ex_max_ram
step_return:
    rts

rom_phase:
    lda expected_source
    cmp #$ff
    beq.same fixed_phase
    lda torture_batch
    sta step_remaining
    lda expected_source
    sta $3f
    jsr $1000
    lda expected_dest
    cmp #$ff
    bne.same step_return
    lda #0
    sta expected_dest
    inc expected_source
    rts

fixed_phase:
    lda #<$1f80
    sta bankcall_stub+1
    lda #>$1f80
    sta bankcall_stub+2
    lda #<$1100
    sta bankcall_stub+3
    lda #>$1100
    sta bankcall_stub+4
    tsx
    stx fixed_sp
    lda torture_batch
    sta step_remaining
fixed_dest_loop:
    lda expected_dest
    cmp #$ff
    beq.same fixed_done
    sta bankcall_stub+5
    jsr bankcall_stub
    inc expected_dest
    lda expected_dest
    cmp #$ff
    beq.same fixed_done
    dec step_remaining
    bne.same fixed_dest_loop
fixed_step_return:
    tsx
    cpx fixed_sp
    beq.same step_return
    lda #$05
    sta failure
    rts

fixed_done:
    tsx
    cpx fixed_sp
    beq.same fixed_stack_ok
    lda #$05
    sta failure
fixed_stack_ok:
    lda torture_count
    cmp #$ff
    beq.same count_lo_ok
    lda #$06
    sta failure
count_lo_ok:
    lda torture_count+1
    cmp #$ff
    beq.same count_hi_ok
    lda #$07
    sta failure
count_hi_ok:
    lda #1
    sta ram_phase
    jsr ram_walk_reset
    .banktarget ram_walk_reset
    rts
FIXED
close $fixed or die "$0: close $fixed_path: $!\n";

# Remove obsolete generated chunk/accessor/storage files if grouping changes.
for my $path (glob "$Bin/3ex_max_torture_*.s26") {
   next if $path eq $fixed_path;
   next if $path =~ /_\d\d\.s26\z/ && substr($path, -6, 2) < $chunk;
   unlink $path or die "$0: cannot remove stale $path: $!\n";
}
