#!/usr/bin/perl
use strict;
use warnings;
use Cwd qw(abs_path);
use File::Path qw(make_path);
use File::Spec;
use FindBin;
use Math::BigInt;

sub usage {
   die "usage: $0 [--build DIR] <typename> <little|big> <size-bytes> <exp-bits>\n";
}

sub pow2s {
   my ($b) = @_;
   my $x = Math::BigInt->new(1);
   $x->blsft($b);
   return $x->bstr();
}

sub all1s {
   my ($b) = @_;
   my $x = Math::BigInt->new(1);
   $x->blsft($b);
   $x->bdec();
   return $x->bstr();
}

sub typed {
   my ($v, $t) = @_;
   return "$v`$t";
}

sub biass {
   my ($b) = @_;
   my $x = Math::BigInt->new(1);
   $x->blsft($b - 1);
   $x->bdec();
   return $x->bstr();
}

my $build_dir;
if (@ARGV >= 2 && $ARGV[0] eq '--build') {
   shift @ARGV;
   $build_dir = shift @ARGV;
   usage() if !defined $build_dir || $build_dir eq '';
}

my ($typename, $endian, $size, $expbits) = @ARGV;
usage() if @ARGV != 4;
usage() if $endian ne 'little' && $endian ne 'big';
usage() if $size !~ /^\d+$/ || $size <= 0;
usage() if $expbits !~ /^\d+$/ || $expbits <= 0;

my $total = $size * 8;
die "$0: invalid layout\n" if 1 + $expbits >= $total;

my $mbits = $total - 1 - $expbits;
my $last = $size - 1;
my $wide_bytes = $size * 2;
my $san = $typename;
$san =~ s/[^A-Za-z0-9_]/_/g;
$san = "t_$san" if $san !~ /^[A-Za-z]/;
my $u = "nlf_${san}_u";
my $wu = "nlf_${san}_wide_u";
my $bits = "nlf_${san}_bits";
my $ov = "nlf_${san}_overlay";
my $vov = "nlf_${san}_value_overlay";
my $uov = "nlf_${san}_u_overlay";
my ($matht, $math_bytes);
if ($size <= 2) {
   $matht = 'int';
   $math_bytes = 2;
}
elsif ($size <= 4) {
   $matht = 'long';
   $math_bytes = 4;
}
else {
   $matht = 'longlong';
   $math_bytes = 8;
}
my $mov = "nlf_${san}_math_overlay";
my $wov = "nlf_${san}_wide_overlay";

my $ga = "nlf_${san}_a";
my $gb = "nlf_${san}_b";
my $gr = "nlf_${san}_r";
my $gt = "nlf_${san}_t";
my $gmant_u = "nlf_${san}_mant_u";
my $gsig_u = "nlf_${san}_sig_u";
my $gtmp_u = "nlf_${san}_tmp_u";
my $gmant_ll = "nlf_${san}_mant_ll";
my $gsig_ll = "nlf_${san}_sig_ll";
my $gtmp_ll = "nlf_${san}_tmp_ll";
my $gamag = "nlf_${san}_amag";
my $gbmag = "nlf_${san}_bmag";
my $gwide_a = "nlf_${san}_wide_a";
my $gwide_b = "nlf_${san}_wide_b";
my $gwide_p = "nlf_${san}_wide_p";
my $gwide_t = "nlf_${san}_wide_t";
my $gexp_a = "nlf_${san}_exp_a";
my $gexp_b = "nlf_${san}_exp_b";
my $gsign_out = "nlf_${san}_sign_out";
my $gsig_a = "nlf_${san}_sig_a";
my $gsig_b = "nlf_${san}_sig_b";
my $gsig_out = "nlf_${san}_sig_out";
my $gcmp = "nlf_${san}_cmp";
my $gunordered = "nlf_${san}_unordered";
my $add_impl = "nlf_${san}_add_impl";
my $cmp_impl = "nlf_${san}_cmp_impl";
my $mul_impl = "nlf_${san}_mul_impl";
my $div_impl = "nlf_${san}_div_impl";

my $wide_math = ($size > 8) ? 1 : 0;
my $u8 = "nlf_${san}_u8";
my $sig = "nlf_${san}_sig";
my $wide = "nlf_${san}_wide";
my $sig_bytes = int(($mbits + 5 + 7) / 8);
my $sig_last = $sig_bytes - 1;
my $sig_bits = $sig_bytes * 8;
my $wide_sig_bytes = $sig_bytes * 2;
my $wide_sig_last = $wide_sig_bytes - 1;
my $ebits = $expbits + 2;
my $ebytes = int(($ebits + 7) / 8);
$ebytes = 2 if $ebytes < 2;
my ($et, $et_is_builtin);
if ($expbits <= 14) {
   $et = "int";
   $et_is_builtin = 1;
}
elsif ($expbits <= 30) {
   $et = "long";
   $et_is_builtin = 1;
}
elsif ($expbits <= 62) {
   $et = "longlong";
   $et_is_builtin = 1;
}
else {
   $et = "nlf_${san}_exp_t";
   $et_is_builtin = 0;
}
my $EXP_ZERO_E = typed(0, $et);
my $EXP_ONE_E = typed(1, $et);
my $EXP_MAX_E = typed(all1s($expbits), $et);
my $EXP_BIAS_E = typed(biass($expbits), $et);
my $sig_hidden_bit = $mbits;
my $sig_hidden_ext_bit = $mbits + 3;
my $sig_carry_bit = $mbits + 1;
my $mul_shift = $mbits - 3;

my $ZERO = typed(0, $u);
my $ONE = typed(1, $u);
my $W_ZERO = typed(0, $wu);
my $W_ONE = typed(1, $wu);
my $W_TWO = typed(2, $wu);
my $W_HIDDEN_EXT = typed(pow2s($mbits + 3), $wu);
my $EXP_MAX = typed(all1s($expbits), $u);
my $NAN_PAYLOAD = typed($mbits > 1 ? pow2s($mbits - 1) : 1, $u);
my $M_ZERO = typed(0, $matht);
my $M_ONE = typed(1, $matht);
my $M_TWO = typed(2, $matht);
my $M_EIGHT = typed(8, $matht);
my $M_EXP_MAX = typed(all1s($expbits), $matht);
my $M_BIAS = typed(biass($expbits), $matht);
my $FRACMASK = typed(all1s($mbits), $u);
my $M_HIDDEN = typed(pow2s($mbits), $matht);
my $M_HIDDEN_EXT = typed(pow2s($mbits + 3), $matht);
my $M_CARRY = typed(pow2s($mbits + 1), $matht);

my $CMP_EQ = 0;
my $CMP_LT = 1;
my $CMP_GT = 2;

sub comment_header {
   return <<"HDR";
// generated by libraries/float/n65_gen_float.pl
// typename: $typename
// endian: $endian
// size: $size
// expbits: $expbits
// implementation: manual SExMy arithmetic using bitfields and unions

HDR
}

sub load_code {
   my ($ovname, $valname, $iv) = @_;
   return "   $ovname.value := $valname;\n" if $endian eq 'little';
   return "   $vov $iv;\n   int ${ovname}_i;\n   $iv.value := $valname;\n   ${ovname}_i := 0;\n   while (${ovname}_i < $size) {\n      $ovname.bytes[${ovname}_i] := $iv.bytes[$last - ${ovname}_i];\n      ${ovname}_i++;\n   }\n";
}

sub store_code {
   my ($ovname, $vv) = @_;
   return "   return $ovname.value;\n" if $endian eq 'little';
   return "   $vov $vv;\n   int ${ovname}_o;\n   ${ovname}_o := 0;\n   while (${ovname}_o < $size) {\n      $vv.bytes[${ovname}_o] := $ovname.bytes[$last - ${ovname}_o];\n      ${ovname}_o++;\n   }\n   return $vv.value;\n";
}

sub to_ll_snippet {
   my ($dst, $src, $indent) = @_;
   $indent //= '      ';
   return "${indent}$dst := $src;
";
}

sub from_ll_snippet {
   my ($dst, $src, $indent) = @_;
   $indent //= '      ';
   return "${indent}$dst := $src;
";
}

sub ll_to_wide_snippet {
   my ($dstw, $src, $indent) = @_;
   $indent //= '      ';
   return "${indent}$dstw.v := $src;
";
}

sub wide_to_ll_snippet {
   my ($dst, $srcw, $indent) = @_;
   $indent //= '      ';
   return "${indent}$dst := $srcw.v;
";
}

sub mag_cmp_snippet {
   my ($dst, $lhs, $rhs, $indent) = @_;
   $indent //= '   ';
   my $s = "${indent}$dst := $CMP_EQ;\n";
   for (my $i = $last; $i >= 0; --$i) {
      my $l = "((((int)$lhs.bytes[$i]) & 255))";
      my $r = "((((int)$rhs.bytes[$i]) & 255))";
      if ($i == $last) {
         $l = "($l & 127)";
         $r = "($r & 127)";
      }
      $s .= "${indent}if ($dst == $CMP_EQ) {\n";
      $s .= "${indent}   if ($l < $r) { $dst := $CMP_LT; }\n";
      $s .= "${indent}   else { if ($l > $r) { $dst := $CMP_GT; } }\n";
      $s .= "${indent}}\n";
   }
   return $s;
}

sub pack_snippet {
   my ($sig, $exp, $sign, $out, $mant) = @_;
   return "      $out.raw := $ZERO;
"
      . "      if ($sig == $M_ZERO) {
"
      . "         $out.bits.sign := $sign;
"
      . "      }
"
      . "      else {
"
      . "         ${matht} low;
"
      . "         low := $sig & 7`$matht;
"
      . "         $mant := $sig / $M_EIGHT;
"
      . "         if ((low & 4`$matht) != $M_ZERO && (((low & 3`$matht) != $M_ZERO) || (($mant & $M_ONE) != $M_ZERO))) {
"
      . "            $mant++;
"
      . "         }
"
      . "         if ($mant >= $M_CARRY) {
"
      . "            $mant /= $M_TWO;
"
      . "            $exp++;
"
      . "         }
"
      . "         if ($exp >= $M_EXP_MAX) {
"
      . "            $out.bits.sign := $sign;
"
      . "            $out.bits.exponent := $EXP_MAX;
"
      . "            $out.bits.mantissa := $ZERO;
"
      . "         }
"
      . "         else {
"
      . "            $out.bits.sign := $sign;
"
      . "            if ($mant >= $M_HIDDEN) {
"
      . "               $out.bits.exponent := $exp;
"
      . "               $out.bits.mantissa := $mant & $FRACMASK;
"
      . "            }
"
      . "            else {
"
      . "               $out.bits.exponent := $ZERO;
"
      . "               $out.bits.mantissa := $mant;
"
      . "            }
"
      . "         }
"
      . "      }
";
}


sub wide_helper_text {
   my $s = "";
   $s .= "void nlf_${san}_sig_zero($sig *p) {\n";
   $s .= "   int i;\n   i := 0;\n   while (i < $sig_bytes) {\n      p->bytes[i] := 0;\n      i++;\n   }\n}\n\n";
   $s .= "void nlf_${san}_wide_zero($wide *p) {\n";
   $s .= "   int i;\n   i := 0;\n   while (i < $wide_sig_bytes) {\n      p->bytes[i] := 0;\n      i++;\n   }\n}\n\n";
   $s .= "bool nlf_${san}_sig_is_zero($sig *p) {\n";
   $s .= "   int i;\n   i := 0;\n   while (i < $sig_bytes) {\n      if (p->bytes[i] != 0) { return false; }\n      i++;\n   }\n   return true;\n}\n\n";
   $s .= "nlf_${san}_u8 nlf_${san}_mask8(int bitno) {
";
   $s .= "   if (bitno == 0) { return 1; }
   if (bitno == 1) { return 2; }
   if (bitno == 2) { return 4; }
   if (bitno == 3) { return 8; }
   if (bitno == 4) { return 16; }
   if (bitno == 5) { return 32; }
   if (bitno == 6) { return 64; }
   return 128;
}

";
   $s .= "nlf_${san}_u8 nlf_${san}_shr1_u8(nlf_${san}_u8 value) {
";
   $s .= "   nlf_${san}_u8 out;
   out := 0;
   if ((value & 2) != 0) { out := out | 1; }
   if ((value & 4) != 0) { out := out | 2; }
   if ((value & 8) != 0) { out := out | 4; }
   if ((value & 16) != 0) { out := out | 8; }
   if ((value & 32) != 0) { out := out | 16; }
   if ((value & 64) != 0) { out := out | 32; }
   if ((value & 128) != 0) { out := out | 64; }
   return out;
}

";
   $s .= "void nlf_${san}_sig_copy($sig *dst, $sig *src) {\n";
   $s .= "   int i;\n   i := 0;\n   while (i < $sig_bytes) {\n      dst->bytes[i] := src->bytes[i];\n      i++;\n   }\n}\n\n";
   $s .= "void nlf_${san}_wide_copy($wide *dst, $wide *src) {\n";
   $s .= "   int i;\n   i := 0;\n   while (i < $wide_sig_bytes) {\n      dst->bytes[i] := src->bytes[i];\n      i++;\n   }\n}\n\n";
   $s .= "int nlf_${san}_sig_cmp($sig *lhs, $sig *rhs) {\n";
   $s .= "   int i;\n   i := $sig_last;\n   while (i >= 0) {\n      if (lhs->bytes[i] < rhs->bytes[i]) { return $CMP_LT; }\n      if (lhs->bytes[i] > rhs->bytes[i]) { return $CMP_GT; }\n      i--;\n   }\n   return $CMP_EQ;\n}\n\n";
   $s .= "bool nlf_${san}_sig_get_bit($sig *p, int bitno) {\n";
   $s .= "   int bytei;\n   int biti;\n   bytei := bitno / 8;\n   biti := bitno & 7;\n   if (bytei < 0 || bytei >= $sig_bytes) { return false; }\n   return (p->bytes[bytei] & nlf_${san}_mask8(biti)) != 0;\n}\n\n";
   $s .= "void nlf_${san}_sig_set_bit($sig *p, int bitno) {\n";
   $s .= "   int bytei;\n   int biti;\n   bytei := bitno / 8;\n   biti := bitno & 7;\n   if (bytei < 0 || bytei >= $sig_bytes) { return; }\n   p->bytes[bytei] := p->bytes[bytei] | nlf_${san}_mask8(biti);\n}\n\n";
   $s .= "void nlf_${san}_sig_shl1($sig *p) {\n";
   $s .= "   int i;\n   int carry;\n   i := 0;\n   carry := 0;\n   while (i < $sig_bytes) {\n      int nextc;\n      nextc := 0;\n      if ((p->bytes[i] & 128) != 0) { nextc := 1; }\n      p->bytes[i] := p->bytes[i] + p->bytes[i];\n      if (carry != 0) { p->bytes[i] := p->bytes[i] | 1; }\n      carry := nextc;\n      i++;\n   }\n}\n\n";
   $s .= "void nlf_${san}_sig_shr1($sig *p) {\n";
   $s .= "   int i;\n   int carry;\n   i := $sig_bytes;\n   carry := 0;\n   while (i > 0) {\n      int nextc;\n      i--;\n      nextc := 0;\n      if ((p->bytes[i] & 1) != 0) { nextc := 1; }\n      p->bytes[i] := nlf_${san}_shr1_u8(p->bytes[i]);\n      if (carry != 0) { p->bytes[i] := p->bytes[i] | 128; }\n      carry := nextc;\n   }\n}\n\n";
   $s .= "void nlf_${san}_sig_shr1_sticky($sig *p) {\n";
   $s .= "   int lost;\n   lost := p->bytes[0] & 1;\n   nlf_${san}_sig_shr1(p);\n   if (lost != 0) { p->bytes[0] := p->bytes[0] | 1; }\n}\n\n";
   $s .= "void nlf_${san}_sig_shl_bits($sig *p, int count) {\n   while (count > 0) { nlf_${san}_sig_shl1(p); count--; }\n}\n\n";
   $s .= "void nlf_${san}_sig_shr_bits_sticky($sig *p, int count) {\n   while (count > 0) { nlf_${san}_sig_shr1_sticky(p); count--; }\n}\n\n";
   $s .= "void nlf_${san}_wide_shl1($wide *p) {\n";
   $s .= "   int i;\n   int carry;\n   i := 0;\n   carry := 0;\n   while (i < $wide_sig_bytes) {\n      int nextc;\n      nextc := 0;\n      if ((p->bytes[i] & 128) != 0) { nextc := 1; }\n      p->bytes[i] := p->bytes[i] + p->bytes[i];\n      if (carry != 0) { p->bytes[i] := p->bytes[i] | 1; }\n      carry := nextc;\n      i++;\n   }\n}\n\n";
   $s .= "void nlf_${san}_wide_shr1($wide *p) {\n";
   $s .= "   int i;\n   int carry;\n   i := $wide_sig_bytes;\n   carry := 0;\n   while (i > 0) {\n      int nextc;\n      i--;\n      nextc := 0;\n      if ((p->bytes[i] & 1) != 0) { nextc := 1; }\n      p->bytes[i] := nlf_${san}_shr1_u8(p->bytes[i]);\n      if (carry != 0) { p->bytes[i] := p->bytes[i] | 128; }\n      carry := nextc;\n   }\n}\n\n";
   $s .= "void nlf_${san}_wide_shr1_sticky($wide *p) {\n";
   $s .= "   int lost;\n   lost := p->bytes[0] & 1;\n   nlf_${san}_wide_shr1(p);\n   if (lost != 0) { p->bytes[0] := p->bytes[0] | 1; }\n}\n\n";
   $s .= "void nlf_${san}_wide_shl_bits($wide *p, int count) {\n   while (count > 0) { nlf_${san}_wide_shl1(p); count--; }\n}\n\n";
   $s .= "void nlf_${san}_wide_shr_bits_sticky($wide *p, int count) {\n   while (count > 0) { nlf_${san}_wide_shr1_sticky(p); count--; }\n}\n\n";
   $s .= "void nlf_${san}_sig_add_inplace($sig *dst, $sig *src) {\n";
   $s .= "   int i;\n   int carry;\n   i := 0;\n   carry := 0;\n   while (i < $sig_bytes) {\n      int t;\n      t := (int)dst->bytes[i] + (int)src->bytes[i] + carry;\n      if (t >= 256) { dst->bytes[i] := t - 256; carry := 1; }\n      else { dst->bytes[i] := t; carry := 0; }\n      i++;\n   }\n}\n\n";
   $s .= "void nlf_${san}_sig_inc1($sig *dst) {\n";
   $s .= "   int i;\n   i := 0;\n   while (i < $sig_bytes) {\n      if (dst->bytes[i] != 255) { dst->bytes[i]++; return; }\n      dst->bytes[i] := 0;\n      i++;\n   }\n}\n\n";
   $s .= "void nlf_${san}_sig_sub_inplace($sig *dst, $sig *src) {\n";
   $s .= "   int i;\n   int borrow;\n   i := 0;\n   borrow := 0;\n   while (i < $sig_bytes) {\n      int lhs;\n      int rhs;\n      lhs := (int)dst->bytes[i];\n      rhs := (int)src->bytes[i] + borrow;\n      if (lhs < rhs) { dst->bytes[i] := lhs + 256 - rhs; borrow := 1; }\n      else { dst->bytes[i] := lhs - rhs; borrow := 0; }\n      i++;\n   }\n}\n\n";
   $s .= "void nlf_${san}_sig_from_u($sig *dst, $u value) {\n";
   $s .= "   $uov tmp;\n   int i;\n   nlf_${san}_sig_zero(dst);\n   tmp.value := value;\n   i := 0;\n   while (i < $size && i < $sig_bytes) {\n      dst->bytes[i] := tmp.bytes[i];\n      i++;\n   }\n}\n\n";
   $s .= "void nlf_${san}_sig_to_u($sig *src, $uov *dst) {\n";
   $s .= "   int i;\n   dst->value := $ZERO;\n   i := 0;\n   while (i < $size && i < $sig_bytes) {\n      dst->bytes[i] := src->bytes[i];\n      i++;\n   }\n}\n\n";
   $s .= "void nlf_${san}_wide_from_sig($wide *dst, $sig *src) {\n";
   $s .= "   int i;\n   nlf_${san}_wide_zero(dst);\n   i := 0;\n   while (i < $sig_bytes) {\n      dst->bytes[i] := src->bytes[i];\n      i++;\n   }\n}\n\n";
   $s .= "void nlf_${san}_sig_from_wide_low($sig *dst, $wide *src) {\n";
   $s .= "   int i;\n   i := 0;\n   while (i < $sig_bytes) {\n      dst->bytes[i] := src->bytes[i];\n      i++;\n   }\n}\n\n";
   $s .= "void nlf_${san}_wide_mul($wide *dst, $sig *lhs, $sig *rhs) {\n";
   $s .= "   int i;\n   nlf_${san}_wide_zero(dst);\n   i := 0;\n   while (i < $sig_bytes) {\n      int j;\n      long carry;\n      j := 0;\n      carry := 0;\n      while (j < $sig_bytes) {\n         int idx;\n         long t;\n         idx := i + j;\n         t := (long)(int)dst->bytes[idx] + (long)(int)lhs->bytes[i] * (long)(int)rhs->bytes[j] + carry;\n         dst->bytes[idx] := t & 255;\n         carry := t / 256;\n         j++;\n      }\n      while (carry != 0 && j + i < $wide_sig_bytes) {\n         int idx2;\n         long t2;\n         idx2 := i + j;\n         t2 := (long)(int)dst->bytes[idx2] + carry;\n         dst->bytes[idx2] := t2 & 255;\n         carry := t2 / 256;\n         j++;\n      }\n      i++;\n   }\n}\n\n";
   $s .= "int nlf_${san}_sig_high_bit($sig *p) {\n";
   $s .= "   int i;\n   i := $sig_last;\n   while (i >= 0) {\n      if (p->bytes[i] != 0) {\n         int b;\n         b := 7;\n         while (b >= 0) {\n            if ((p->bytes[i] & nlf_${san}_mask8(b)) != 0) { return i * 8 + b; }\n            b--;\n         }\n      }\n      i--;\n   }\n   return 0;\n}\n\n";
   $s .= "void nlf_${san}_sig_div_shifted($sig *quot, $sig *num, $sig *den, int shift, bool *sticky) {\n";
   $s .= "   $sig rem;\n   int highest;\n   int bitno;\n   nlf_${san}_sig_zero(quot);\n   nlf_${san}_sig_zero(&rem);\n   if (nlf_${san}_sig_is_zero(num)) { *sticky := false; return; }\n   highest := nlf_${san}_sig_high_bit(num);\n   bitno := highest + shift;\n   while (bitno >= 0) {\n      int srcbit;\n      nlf_${san}_sig_shl1(&rem);\n      srcbit := bitno - shift;\n      if (srcbit >= 0 && nlf_${san}_sig_get_bit(num, srcbit)) { rem.bytes[0] := rem.bytes[0] | 1; }\n      nlf_${san}_sig_shl1(quot);\n      if (nlf_${san}_sig_cmp(&rem, den) != $CMP_LT) {\n         nlf_${san}_sig_sub_inplace(&rem, den);\n         quot->bytes[0] := quot->bytes[0] | 1;\n      }\n      bitno--;\n   }\n   *sticky := !nlf_${san}_sig_is_zero(&rem);\n}\n\n";
   $s .= "void nlf_${san}_ov_copy($ov *dst, $ov *src) {\n";
   $s .= "   int i;\n   i := 0;\n   while (i < $size) {\n      dst->bytes[i] := src->bytes[i];\n      i++;\n   }\n}\n\n";
   $s .= "int nlf_${san}_ov_sign($ov *src) {\n   return (src->bytes[$last] >> 7) & 1;\n}\n\n";
   $s .= "bool nlf_${san}_ov_exp_zero($ov *src) {\n   int i;\n   i := 0;\n   while (i < $expbits) {\n      if ((src->bytes[" . int($mbits / 8) . " + ((" . ($mbits % 8) . " + i) / 8)] & nlf_${san}_mask8((" . ($mbits % 8) . " + i) & 7)) != 0) { return false; }\n      i++;\n   }\n   return true;\n}\n\n";
   $s .= "bool nlf_${san}_ov_exp_max($ov *src) {\n   int i;\n   i := 0;\n   while (i < $expbits) {\n      if ((src->bytes[" . int($mbits / 8) . " + ((" . ($mbits % 8) . " + i) / 8)] & nlf_${san}_mask8((" . ($mbits % 8) . " + i) & 7)) == 0) { return false; }\n      i++;\n   }\n   return true;\n}\n\n";
   $s .= "bool nlf_${san}_ov_mant_zero($ov *src) {\n   int i;\n   i := 0;\n   while (i < " . int($mbits / 8) . ") {\n      if (src->bytes[i] != 0) { return false; }\n      i++;\n   }\n";
   if ($mbits % 8) {
      $s .= "   if ((src->bytes[" . int($mbits / 8) . "] & " . ((1 << ($mbits % 8)) - 1) . ") != 0) { return false; }\n";
   }
   $s .= "   return true;\n}\n\n";
   $s .= "void nlf_${san}_ov_mant_to_sig($sig *dst, $ov *src) {\n   int i;\n   nlf_${san}_sig_zero(dst);\n   i := 0;\n   while (i < " . int($mbits / 8) . ") {\n      dst->bytes[i] := src->bytes[i];\n      i++;\n   }\n";
   if ($mbits % 8) {
      $s .= "   dst->bytes[" . int($mbits / 8) . "] := src->bytes[" . int($mbits / 8) . "] & " . ((1 << ($mbits % 8)) - 1) . ";\n";
   }
   $s .= "}\n\n";
   if ($et_is_builtin) {
      $s .= "";
      $s .= "$et nlf_${san}_ov_exp($ov *src) {
   $et e;
   $et bit;
   int i;
   e := 0`$et;
   bit := 1`$et;
   i := 0;
   while (i < $expbits) {
      if ((src->bytes[" . int($mbits / 8) . " + ((" . ($mbits % 8) . " + i) / 8)] & nlf_${san}_mask8((" . ($mbits % 8) . " + i) & 7)) != 0) {
         e := e + bit;
      }
      bit := bit + bit;
      i++;
   }
   return e;
}

";
   }
   $s .= "void nlf_${san}_ov_set_zero($ov *dst, int sign) {\n   int i;\n   i := 0;\n   while (i < $size) {\n      dst->bytes[i] := 0;\n      i++;\n   }\n   if (sign != 0) { dst->bytes[$last] := 128; }\n}\n\n";
   $s .= "void nlf_${san}_ov_set_inf($ov *dst, int sign) {\n   int i;\n   nlf_${san}_ov_set_zero(dst, sign);\n   i := 0;\n   while (i < $expbits) {\n      dst->bytes[" . int($mbits / 8) . " + ((" . ($mbits % 8) . " + i) / 8)] := dst->bytes[" . int($mbits / 8) . " + ((" . ($mbits % 8) . " + i) / 8)] | nlf_${san}_mask8((" . ($mbits % 8) . " + i) & 7);\n      i++;\n   }\n}\n\n";
   $s .= "void nlf_${san}_ov_set_qnan($ov *dst) {\n   nlf_${san}_ov_set_inf(dst, 0);\n   dst->bytes[" . int(($mbits > 1 ? $mbits - 1 : 0) / 8) . "] := dst->bytes[" . int(($mbits > 1 ? $mbits - 1 : 0) / 8) . "] | nlf_${san}_mask8(" . (($mbits > 1 ? $mbits - 1 : 0) % 8) . ");\n}\n\n";
   $s .= "void nlf_${san}_pack_result(void) {\n";
   $s .= "   $sig mant;\n   int low;\n   $uov tmp;\n   $gr.raw := $ZERO;\n   if (nlf_${san}_sig_is_zero(&$gsig_out)) {\n      $gr.bits.sign := $gsign_out;\n      return;\n   }\n   low := $gsig_out.bytes[0] & 7;\n   nlf_${san}_sig_copy(&mant, &$gsig_out);\n   nlf_${san}_sig_shr_bits_sticky(&mant, 3);\n   if ((low & 4) != 0 && (((low & 3) != 0) || ((mant.bytes[0] & 1) != 0))) {\n      nlf_${san}_sig_inc1(&mant);\n   }\n   if (nlf_${san}_sig_get_bit(&mant, $sig_carry_bit)) {\n      nlf_${san}_sig_shr1(&mant);\n      $gexp_a++;\n   }\n   if ($gexp_a >= $EXP_MAX_E) {\n      $gr.bits.sign := $gsign_out;\n      $gr.bits.exponent := $EXP_MAX;\n      $gr.bits.mantissa := $ZERO;\n      return;\n   }\n   $gr.bits.sign := $gsign_out;\n   nlf_${san}_sig_to_u(&mant, &tmp);\n   if (nlf_${san}_sig_get_bit(&mant, $sig_hidden_bit)) {\n      $gr.bits.exponent := $gexp_a;\n      $gr.bits.mantissa := tmp.value;\n   }\n   else {\n      $gr.bits.exponent := $ZERO;\n      $gr.bits.mantissa := tmp.value;\n   }\n}\n\n";
   return $s;
}


sub wide_helper_proto_text {
   my (@names) = @_;
   my %proto = (
      "nlf_${san}_sig_zero" => "extern void nlf_${san}_sig_zero($sig *p);\n",
      "nlf_${san}_wide_zero" => "extern void nlf_${san}_wide_zero($wide *p);\n",
      "nlf_${san}_sig_is_zero" => "extern bool nlf_${san}_sig_is_zero($sig *p);\n",
      "nlf_${san}_mask8" => "extern nlf_${san}_u8 nlf_${san}_mask8(int bitno);\n",
      "nlf_${san}_shr1_u8" => "extern nlf_${san}_u8 nlf_${san}_shr1_u8(nlf_${san}_u8 value);\n",
      "nlf_${san}_sig_copy" => "extern void nlf_${san}_sig_copy($sig *dst, $sig *src);\n",
      "nlf_${san}_wide_copy" => "extern void nlf_${san}_wide_copy($wide *dst, $wide *src);\n",
      "nlf_${san}_sig_cmp" => "extern int nlf_${san}_sig_cmp($sig *lhs, $sig *rhs);\n",
      "nlf_${san}_sig_get_bit" => "extern bool nlf_${san}_sig_get_bit($sig *p, int bitno);\n",
      "nlf_${san}_sig_set_bit" => "extern void nlf_${san}_sig_set_bit($sig *p, int bitno);\n",
      "nlf_${san}_sig_shl1" => "extern void nlf_${san}_sig_shl1($sig *p);\n",
      "nlf_${san}_sig_shr1" => "extern void nlf_${san}_sig_shr1($sig *p);\n",
      "nlf_${san}_sig_shr1_sticky" => "extern void nlf_${san}_sig_shr1_sticky($sig *p);\n",
      "nlf_${san}_sig_shl_bits" => "extern void nlf_${san}_sig_shl_bits($sig *p, int count);\n",
      "nlf_${san}_sig_shr_bits_sticky" => "extern void nlf_${san}_sig_shr_bits_sticky($sig *p, int count);\n",
      "nlf_${san}_wide_shl1" => "extern void nlf_${san}_wide_shl1($wide *p);\n",
      "nlf_${san}_wide_shr1" => "extern void nlf_${san}_wide_shr1($wide *p);\n",
      "nlf_${san}_wide_shr1_sticky" => "extern void nlf_${san}_wide_shr1_sticky($wide *p);\n",
      "nlf_${san}_wide_shl_bits" => "extern void nlf_${san}_wide_shl_bits($wide *p, int count);\n",
      "nlf_${san}_wide_shr_bits_sticky" => "extern void nlf_${san}_wide_shr_bits_sticky($wide *p, int count);\n",
      "nlf_${san}_sig_add_inplace" => "extern void nlf_${san}_sig_add_inplace($sig *dst, $sig *src);\n",
      "nlf_${san}_sig_inc1" => "extern void nlf_${san}_sig_inc1($sig *dst);\n",
      "nlf_${san}_sig_sub_inplace" => "extern void nlf_${san}_sig_sub_inplace($sig *dst, $sig *src);\n",
      "nlf_${san}_sig_from_u" => "extern void nlf_${san}_sig_from_u($sig *dst, $u value);\n",
      "nlf_${san}_sig_to_u" => "extern void nlf_${san}_sig_to_u($sig *src, $uov *dst);\n",
      "nlf_${san}_wide_from_sig" => "extern void nlf_${san}_wide_from_sig($wide *dst, $sig *src);\n",
      "nlf_${san}_sig_from_wide_low" => "extern void nlf_${san}_sig_from_wide_low($sig *dst, $wide *src);\n",
      "nlf_${san}_wide_mul" => "extern void nlf_${san}_wide_mul($wide *dst, $sig *lhs, $sig *rhs);\n",
      "nlf_${san}_sig_high_bit" => "extern int nlf_${san}_sig_high_bit($sig *p);\n",
      "nlf_${san}_sig_div_shifted" => "extern void nlf_${san}_sig_div_shifted($sig *quot, $sig *num, $sig *den, int shift, bool *sticky);\n",
      "nlf_${san}_ov_copy" => "extern void nlf_${san}_ov_copy($ov *dst, $ov *src);
",
      "nlf_${san}_ov_sign" => "extern int nlf_${san}_ov_sign($ov *src);
",
      "nlf_${san}_ov_exp_zero" => "extern bool nlf_${san}_ov_exp_zero($ov *src);
",
      "nlf_${san}_ov_exp_max" => "extern bool nlf_${san}_ov_exp_max($ov *src);
",
      "nlf_${san}_ov_mant_zero" => "extern bool nlf_${san}_ov_mant_zero($ov *src);
",
      "nlf_${san}_ov_mant_to_sig" => "extern void nlf_${san}_ov_mant_to_sig($sig *dst, $ov *src);
",
      "nlf_${san}_ov_exp" => "extern $et nlf_${san}_ov_exp($ov *src);
",
      "nlf_${san}_ov_set_zero" => "extern void nlf_${san}_ov_set_zero($ov *dst, int sign);
",
      "nlf_${san}_ov_set_inf" => "extern void nlf_${san}_ov_set_inf($ov *dst, int sign);
",
      "nlf_${san}_ov_set_qnan" => "extern void nlf_${san}_ov_set_qnan($ov *dst);
",
      "nlf_${san}_pack_result" => "extern void nlf_${san}_pack_result(void);\n",
   );
   my $s = '';
   for my $name (@names) {
      $s .= $proto{$name} if exists $proto{$name};
   }
   return $s;
}

sub wide_runtime_block {
   my ($static_prefix, $vars, $with_helpers, $helper_names, $extra_decls) = @_;
   $vars //= {};
   my $s = '';
   $s .= "type $u8 { \$size:1 \$integer:unsigned };\n";
   $s .= "type $u { \$size:$size \$integer:unsigned \$endian:little };\n";
   $s .= "type $et { \$size:$ebytes \$integer:signed \$endian:little };\n" if !$et_is_builtin;
   $s .= "struct $sig {\n   $u8 bytes[$sig_bytes];\n};\n";
   $s .= "struct $wide {\n   $u8 bytes[$wide_sig_bytes];\n};\n";
   $s .= "struct $bits {\n";
   $s .= "   $u mantissa:$mbits;\n";
   $s .= "   $u exponent:$expbits;\n";
   $s .= "   $u sign:1;\n";
   $s .= "};\n";
   if ($endian eq 'little') {
      $s .= "union $ov {\n   $typename value;\n   $u raw;\n   $u8 bytes[$size];\n   $bits bits;\n};\n";
   }
   else {
      $s .= "union $vov {\n   $typename value;\n   $u8 bytes[$size];\n};\n\n";
      $s .= "union $ov {\n   $u raw;\n   $u8 bytes[$size];\n   $bits bits;\n};\n";
   }
   $s .= "union $uov {\n   $u value;\n   $u8 bytes[$size];\n};\n\n";
   my @decls;
   push @decls, "$ov $ga" if $vars->{ga};
   push @decls, "$ov $gb" if $vars->{gb};
   push @decls, "$ov $gr" if $vars->{gr};
   push @decls, "$wide $gwide_a" if $vars->{gwide_a};
   push @decls, "$wide $gwide_b" if $vars->{gwide_b};
   push @decls, "$wide $gwide_p" if $vars->{gwide_p};
   push @decls, "$wide $gwide_t" if $vars->{gwide_t};
   push @decls, "$et $gexp_a" if $vars->{gexp_a};
   push @decls, "$et $gexp_b" if $vars->{gexp_b};
   push @decls, "int $gsign_out" if $vars->{gsign_out};
   push @decls, "$sig $gsig_a" if $vars->{gsig_a};
   push @decls, "$sig $gsig_b" if $vars->{gsig_b};
   push @decls, "$sig $gsig_out" if $vars->{gsig_out};
   push @decls, "int $gcmp" if $vars->{gcmp};
   push @decls, "bool $gunordered" if $vars->{gunordered};
   for my $decl (@decls) {
      $s .= "$static_prefix$decl;\n";
   }
   $s .= "\n";
   $with_helpers = ($static_prefix eq '') if !defined $with_helpers;
   if ($with_helpers) {
      $s .= wide_helper_text();
   }
   elsif (defined $helper_names) {
      $s .= wide_helper_proto_text(@$helper_names);
      $s .= "
" if @$helper_names;
   }
   $s .= $extra_decls if defined $extra_decls;
   return $s;
}

sub base_runtime_block {
   my ($static_prefix, $vars) = @_;
   if ($wide_math) {
      return wide_runtime_block($static_prefix, $vars);
   }
   $vars //= {};

   my $need_ov = 0;
   for my $k (qw(ga gb gr)) {
      if ($vars->{$k}) { $need_ov = 1; last; }
   }
   my $need_wide = 0;
   for my $k (qw(gwide_a gwide_b gwide_p gwide_t)) {
      if ($vars->{$k}) { $need_wide = 1; last; }
   }

   my $s = '';
   $s .= "type $u { \$size:$size \$integer:unsigned \$endian:little };
";
   $s .= "type $wu { \$size:$wide_bytes \$integer:unsigned \$endian:little };

" if $need_wide;
   if ($need_ov) {
      $s .= "struct $bits {
";
      $s .= "   $u mantissa:$mbits;
";
      $s .= "   $u exponent:$expbits;
";
      $s .= "   $u sign:1;
";
      $s .= "};
";
      if ($endian eq 'little') {
         $s .= "union $ov {
";
         $s .= "   $typename value;
";
         $s .= "   $u raw;
";
         $s .= "   char bytes[$size];
";
         $s .= "   $bits bits;
";
         $s .= "};
";
      }
      else {
         $s .= "union $vov {
";
         $s .= "   $typename value;
";
         $s .= "   char bytes[$size];
";
         $s .= "};

";
         $s .= "union $ov {
";
         $s .= "   $u raw;
";
         $s .= "   char bytes[$size];
";
         $s .= "   $bits bits;
";
         $s .= "};
";
      }
   }
   if ($need_wide) {
      $s .= "union $wov {
";
      $s .= "   $wu v;
";
      $s .= "   char bytes[$wide_bytes];
";
      $s .= "};

";
   }

   my @decls;
   push @decls, "$ov $ga" if $vars->{ga};
   push @decls, "$ov $gb" if $vars->{gb};
   push @decls, "$ov $gr" if $vars->{gr};
   push @decls, "$wov $gwide_a" if $vars->{gwide_a};
   push @decls, "$wov $gwide_b" if $vars->{gwide_b};
   push @decls, "$wov $gwide_p" if $vars->{gwide_p};
   push @decls, "$wov $gwide_t" if $vars->{gwide_t};
   push @decls, "$matht $gmant_ll" if $vars->{gmant_ll};
   push @decls, "$matht $gexp_a" if $vars->{gexp_a};
   push @decls, "$matht $gexp_b" if $vars->{gexp_b};
   push @decls, "int $gsign_out" if $vars->{gsign_out};
   push @decls, "$matht $gsig_a" if $vars->{gsig_a};
   push @decls, "$matht $gsig_b" if $vars->{gsig_b};
   push @decls, "$matht $gsig_out" if $vars->{gsig_out};
   push @decls, "int $gcmp" if $vars->{gcmp};
   push @decls, "bool $gunordered" if $vars->{gunordered};

   for my $decl (@decls) {
      $s .= "$static_prefix$decl;
";
   }
   $s .= "
";
   return $s;
}

sub proc_decl_text {
   my ($name) = @_;
   return "extern void $name(void);

";
}

sub operator_binary_decl_text {
   my ($ret, $op) = @_;
   return "extern $ret $op($typename lhs, $typename rhs);

";
}

sub operator_unary_decl_text {
   my ($ret, $op) = @_;
   return "extern $ret $op($typename v);

";
}

sub operator_incdec_decl_text {
   my ($op) = @_;
   return "extern $typename $op(ref $typename v);

";
}

sub build_unit_text {
   my ($storage_prefix, $vars, $decls, $body) = @_;
   return comment_header()
      . standalone_prelude()
      . base_runtime_block($storage_prefix, $vars)
      . ($decls || '')
      . ($body || '');
}

sub add_impl_text {
   my ($static_prefix) = @_;
   if ($wide_math) {
      my $s = "${static_prefix}void $add_impl(void) {\n";
      $s .= "   if (nlf_${san}_ov_exp_max(&$ga) && !nlf_${san}_ov_mant_zero(&$ga)) {\n      nlf_${san}_ov_copy(&$gr, &$ga);\n      return;\n   }\n";
      $s .= "   if (nlf_${san}_ov_exp_max(&$gb) && !nlf_${san}_ov_mant_zero(&$gb)) {\n      nlf_${san}_ov_copy(&$gr, &$gb);\n      return;\n   }\n";
      $s .= "   if (nlf_${san}_ov_exp_max(&$ga) && nlf_${san}_ov_exp_max(&$gb) && nlf_${san}_ov_sign(&$ga) != nlf_${san}_ov_sign(&$gb)) {\n      nlf_${san}_ov_set_qnan(&$gr);\n      return;\n   }\n";
      $s .= "   if (nlf_${san}_ov_exp_max(&$ga) && nlf_${san}_ov_mant_zero(&$ga)) {\n      nlf_${san}_ov_copy(&$gr, &$ga);\n      return;\n   }\n";
      $s .= "   if (nlf_${san}_ov_exp_max(&$gb) && nlf_${san}_ov_mant_zero(&$gb)) {\n      nlf_${san}_ov_copy(&$gr, &$gb);\n      return;\n   }\n";
      $s .= "   if (nlf_${san}_ov_exp_zero(&$ga) && nlf_${san}_ov_mant_zero(&$ga) && nlf_${san}_ov_exp_zero(&$gb) && nlf_${san}_ov_mant_zero(&$gb)) {\n      if (nlf_${san}_ov_sign(&$ga) == nlf_${san}_ov_sign(&$gb)) { nlf_${san}_ov_set_zero(&$gr, nlf_${san}_ov_sign(&$ga)); } else { nlf_${san}_ov_set_zero(&$gr, 0); }\n      return;\n   }\n";
      $s .= "   if (nlf_${san}_ov_exp_zero(&$ga) && nlf_${san}_ov_mant_zero(&$ga)) {\n      nlf_${san}_ov_copy(&$gr, &$gb);\n      return;\n   }\n";
      $s .= "   if (nlf_${san}_ov_exp_zero(&$gb) && nlf_${san}_ov_mant_zero(&$gb)) {\n      nlf_${san}_ov_copy(&$gr, &$ga);\n      return;\n   }\n";
      $s .= "   nlf_${san}_ov_mant_to_sig(&$gsig_a, &$ga);\n   nlf_${san}_ov_mant_to_sig(&$gsig_b, &$gb);\n   $gexp_a := nlf_${san}_ov_exp(&$ga);\n   $gexp_b := nlf_${san}_ov_exp(&$gb);\n   if ($gexp_a == $EXP_ZERO_E) { $gexp_a := $EXP_ONE_E; }\n   if ($gexp_b == $EXP_ZERO_E) { $gexp_b := $EXP_ONE_E; }\n   if (!nlf_${san}_ov_exp_zero(&$ga)) { nlf_${san}_sig_set_bit(&$gsig_a, $sig_hidden_bit); }\n   if (!nlf_${san}_ov_exp_zero(&$gb)) { nlf_${san}_sig_set_bit(&$gsig_b, $sig_hidden_bit); }\n   nlf_${san}_sig_shl_bits(&$gsig_a, 3);\n   nlf_${san}_sig_shl_bits(&$gsig_b, 3);\n";
      $s .= "   if (nlf_${san}_ov_sign(&$ga) == nlf_${san}_ov_sign(&$gb)) {\n      while ($gexp_a < $gexp_b) { nlf_${san}_sig_shr1_sticky(&$gsig_a); $gexp_a++; }\n      while ($gexp_b < $gexp_a) { nlf_${san}_sig_shr1_sticky(&$gsig_b); $gexp_b++; }\n      nlf_${san}_sig_copy(&$gsig_out, &$gsig_a);\n      nlf_${san}_sig_add_inplace(&$gsig_out, &$gsig_b);\n      $gsign_out := nlf_${san}_ov_sign(&$ga);\n      nlf_${san}_pack_result();\n      return;\n   }\n";
      $s .= mag_cmp_snippet($gcmp, $ga, $gb, '   ');
      $s .= "   if ($gcmp == $CMP_EQ) { nlf_${san}_ov_set_zero(&$gr, 0); return; }\n";
      $s .= "   if ($gcmp == $CMP_LT) {\n      nlf_${san}_ov_copy(&$gr, &$ga);\n      nlf_${san}_ov_copy(&$ga, &$gb);\n      nlf_${san}_ov_copy(&$gb, &$gr);\n      nlf_${san}_ov_mant_to_sig(&$gsig_a, &$ga);\n      nlf_${san}_ov_mant_to_sig(&$gsig_b, &$gb);\n      $gexp_a := nlf_${san}_ov_exp(&$ga);\n      $gexp_b := nlf_${san}_ov_exp(&$gb);\n      if ($gexp_a == $EXP_ZERO_E) { $gexp_a := $EXP_ONE_E; }\n      if ($gexp_b == $EXP_ZERO_E) { $gexp_b := $EXP_ONE_E; }\n      if (!nlf_${san}_ov_exp_zero(&$ga)) { nlf_${san}_sig_set_bit(&$gsig_a, $sig_hidden_bit); }\n      if (!nlf_${san}_ov_exp_zero(&$gb)) { nlf_${san}_sig_set_bit(&$gsig_b, $sig_hidden_bit); }\n      nlf_${san}_sig_shl_bits(&$gsig_a, 3);\n      nlf_${san}_sig_shl_bits(&$gsig_b, 3);\n   }\n";
      $s .= "   while ($gexp_a < $gexp_b) { nlf_${san}_sig_shr1_sticky(&$gsig_a); $gexp_a++; }\n";
      $s .= "   while ($gexp_b < $gexp_a) { nlf_${san}_sig_shr1_sticky(&$gsig_b); $gexp_b++; }\n";
      $s .= "   nlf_${san}_sig_copy(&$gsig_out, &$gsig_a);\n   nlf_${san}_sig_sub_inplace(&$gsig_out, &$gsig_b);\n   $gsign_out := nlf_${san}_ov_sign(&$ga);\n";
      $s .= "   while (!nlf_${san}_sig_is_zero(&$gsig_out) && $gexp_a > $EXP_ONE_E && !nlf_${san}_sig_get_bit(&$gsig_out, $sig_hidden_ext_bit)) { nlf_${san}_sig_shl1(&$gsig_out); $gexp_a--; }\n";
      $s .= "   nlf_${san}_pack_result();\n}\n\n";
      return $s;
   }
   my $s = "${static_prefix}void $add_impl(void) {\n";
   $s .= "   if ($ga.bits.exponent == $EXP_MAX && $ga.bits.mantissa != $ZERO) {\n      $gr.raw := $ga.raw;\n      return;\n   }\n";
   $s .= "   if ($gb.bits.exponent == $EXP_MAX && $gb.bits.mantissa != $ZERO) {\n      $gr.raw := $gb.raw;\n      return;\n   }\n";
   $s .= "   if ($ga.bits.exponent == $EXP_MAX && $gb.bits.exponent == $EXP_MAX && $ga.bits.sign != $gb.bits.sign) {\n      $gr.raw := $ZERO;\n      $gr.bits.sign := $ZERO;\n      $gr.bits.exponent := $EXP_MAX;\n      $gr.bits.mantissa := $NAN_PAYLOAD;\n      return;\n   }\n";
   $s .= "   if ($ga.bits.exponent == $EXP_MAX && $ga.bits.mantissa == $ZERO) {\n      $gr.raw := $ga.raw;\n      return;\n   }\n";
   $s .= "   if ($gb.bits.exponent == $EXP_MAX && $gb.bits.mantissa == $ZERO) {\n      $gr.raw := $gb.raw;\n      return;\n   }\n";
   $s .= "   if ($ga.bits.exponent == $ZERO && $ga.bits.mantissa == $ZERO && $gb.bits.exponent == $ZERO && $gb.bits.mantissa == $ZERO) {\n      $gr.raw := $ZERO;\n      if ($ga.bits.sign == $gb.bits.sign) { $gr.bits.sign := $ga.bits.sign; } else { $gr.bits.sign := $ZERO; }\n      return;\n   }\n";
   $s .= "   if ($ga.bits.exponent == $ZERO && $ga.bits.mantissa == $ZERO) {\n      $gr.raw := $gb.raw;\n      return;\n   }\n";
   $s .= "   if ($gb.bits.exponent == $ZERO && $gb.bits.mantissa == $ZERO) {\n      $gr.raw := $ga.raw;\n      return;\n   }\n";
   $s .= "   $gsig_a := $ga.bits.mantissa;\n   $gsig_b := $gb.bits.mantissa;\n   $gexp_a := $ga.bits.exponent;\n   $gexp_b := $gb.bits.exponent;\n   if ($gexp_a == $M_ZERO) { $gexp_a := $M_ONE; }\n   if ($gexp_b == $M_ZERO) { $gexp_b := $M_ONE; }\n   if ($ga.bits.exponent != $ZERO) { $gsig_a |= $M_HIDDEN; }\n   if ($gb.bits.exponent != $ZERO) { $gsig_b |= $M_HIDDEN; }\n   $gsig_a *= $M_EIGHT;\n   $gsig_b *= $M_EIGHT;\n   if ($ga.bits.sign == $gb.bits.sign) {\n      while ($gexp_a < $gexp_b) { $matht lost; lost := $gsig_a & $M_ONE; $gsig_a /= $M_TWO; if (lost != $M_ZERO) { $gsig_a |= $M_ONE; } $gexp_a++; }\n      while ($gexp_b < $gexp_a) { $matht lost; lost := $gsig_b & $M_ONE; $gsig_b /= $M_TWO; if (lost != $M_ZERO) { $gsig_b |= $M_ONE; } $gexp_b++; }\n      $gsig_out := $gsig_a + $gsig_b;\n      $gsign_out := $ga.bits.sign;\n";
   $s .= pack_snippet($gsig_out, $gexp_a, $gsign_out, $gr, $gmant_ll);
   $s .= "      return;\n   }\n";
   $s .= mag_cmp_snippet($gcmp, $ga, $gb, '   ');
   $s .= "   if ($gcmp == $CMP_EQ) { $gr.raw := $ZERO; return; }\n   if ($gcmp == $CMP_LT) {\n      $gr.raw := $ga.raw;\n      $ga.raw := $gb.raw;\n      $gb.raw := $gr.raw;\n      $gsig_a := $ga.bits.mantissa;\n      $gsig_b := $gb.bits.mantissa;\n      $gexp_a := $ga.bits.exponent;\n      $gexp_b := $gb.bits.exponent;\n      if ($gexp_a == $M_ZERO) { $gexp_a := $M_ONE; }\n      if ($gexp_b == $M_ZERO) { $gexp_b := $M_ONE; }\n      if ($ga.bits.exponent != $ZERO) { $gsig_a |= $M_HIDDEN; }\n      if ($gb.bits.exponent != $ZERO) { $gsig_b |= $M_HIDDEN; }\n      $gsig_a *= $M_EIGHT;\n      $gsig_b *= $M_EIGHT;\n   }\n   while ($gexp_a < $gexp_b) { $matht lost; lost := $gsig_a & $M_ONE; $gsig_a /= $M_TWO; if (lost != $M_ZERO) { $gsig_a |= $M_ONE; } $gexp_a++; }\n   while ($gexp_b < $gexp_a) { $matht lost; lost := $gsig_b & $M_ONE; $gsig_b /= $M_TWO; if (lost != $M_ZERO) { $gsig_b |= $M_ONE; } $gexp_b++; }\n   $gsig_out := $gsig_a - $gsig_b;\n   $gsign_out := $ga.bits.sign;\n   while ($gsig_out != $M_ZERO && $gexp_a > $M_ONE && $gsig_out < $M_HIDDEN_EXT) { $gsig_out *= $M_TWO; $gexp_a--; }\n";
   $s .= pack_snippet($gsig_out, $gexp_a, $gsign_out, $gr, $gmant_ll);
   $s .= "}\n\n";
   return $s;
}

sub cmp_impl_text {
   my ($static_prefix) = @_;
   if ($wide_math) {
      return "${static_prefix}void $cmp_impl(void) {\n"
         . "   $gunordered := false;\n"
         . "   if (nlf_${san}_ov_exp_max(&$ga) && !nlf_${san}_ov_mant_zero(&$ga)) { $gunordered := true; $gcmp := 0; return; }\n"
         . "   if (nlf_${san}_ov_exp_max(&$gb) && !nlf_${san}_ov_mant_zero(&$gb)) { $gunordered := true; $gcmp := 0; return; }\n"
         . "   if (nlf_${san}_ov_exp_zero(&$ga) && nlf_${san}_ov_mant_zero(&$ga) && nlf_${san}_ov_exp_zero(&$gb) && nlf_${san}_ov_mant_zero(&$gb)) { $gcmp := 0; return; }\n"
         . "   if (nlf_${san}_ov_sign(&$ga) != nlf_${san}_ov_sign(&$gb)) { if (nlf_${san}_ov_sign(&$ga) != 0) { $gcmp := $CMP_LT; } else { $gcmp := $CMP_GT; } return; }\n"
         . mag_cmp_snippet($gcmp, $ga, $gb, '   ')
         . "   if (nlf_${san}_ov_sign(&$ga) != 0) { if ($gcmp == $CMP_LT) { $gcmp := $CMP_GT; } else { if ($gcmp == $CMP_GT) { $gcmp := $CMP_LT; } } }\n}\n\n";
   }
   return "${static_prefix}void $cmp_impl(void) {\n   $gunordered := false;\n   if ($ga.bits.exponent == $EXP_MAX && $ga.bits.mantissa != $ZERO) { $gunordered := true; $gcmp := 0; return; }\n   if ($gb.bits.exponent == $EXP_MAX && $gb.bits.mantissa != $ZERO) { $gunordered := true; $gcmp := 0; return; }\n   if ($ga.bits.exponent == $ZERO && $ga.bits.mantissa == $ZERO && $gb.bits.exponent == $ZERO && $gb.bits.mantissa == $ZERO) { $gcmp := 0; return; }\n   if ($ga.bits.sign != $gb.bits.sign) { if ($ga.bits.sign != $ZERO) { $gcmp := $CMP_LT; } else { $gcmp := $CMP_GT; } return; }\n"
      . mag_cmp_snippet($gcmp, $ga, $gb, '   ')
      . "   if ($ga.bits.sign != $ZERO) { if ($gcmp == $CMP_LT) { $gcmp := $CMP_GT; } else { if ($gcmp == $CMP_GT) { $gcmp := $CMP_LT; } } }\n}\n\n";
}

sub mul_impl_text {
   my ($static_prefix) = @_;
   if ($wide_math) {
      my $s = "${static_prefix}void $mul_impl(void) {
";
      $s .= "   if ($ga.bits.exponent == $EXP_MAX && $ga.bits.mantissa != $ZERO) {
      $gr.raw := $ga.raw;
      return;
   }
";
      $s .= "   if ($gb.bits.exponent == $EXP_MAX && $gb.bits.mantissa != $ZERO) {
      $gr.raw := $gb.raw;
      return;
   }
";
      $s .= "   $gsign_out := $ga.bits.sign ^ $gb.bits.sign;
";
      $s .= "   if (($ga.bits.exponent == $EXP_MAX && $ga.bits.mantissa == $ZERO && $gb.bits.exponent == $ZERO && $gb.bits.mantissa == $ZERO) || ($gb.bits.exponent == $EXP_MAX && $gb.bits.mantissa == $ZERO && $ga.bits.exponent == $ZERO && $ga.bits.mantissa == $ZERO)) {
      $gr.raw := $ZERO;
      $gr.bits.sign := $ZERO;
      $gr.bits.exponent := $EXP_MAX;
      $gr.bits.mantissa := $NAN_PAYLOAD;
      return;
   }
";
      $s .= "   if ($ga.bits.exponent == $EXP_MAX && $ga.bits.mantissa == $ZERO) {
      $gr.raw := $ZERO;
      $gr.bits.sign := $gsign_out;
      $gr.bits.exponent := $EXP_MAX;
      return;
   }
";
      $s .= "   if ($gb.bits.exponent == $EXP_MAX && $gb.bits.mantissa == $ZERO) {
      $gr.raw := $ZERO;
      $gr.bits.sign := $gsign_out;
      $gr.bits.exponent := $EXP_MAX;
      return;
   }
";
      $s .= "   if (($ga.bits.exponent == $ZERO && $ga.bits.mantissa == $ZERO) || ($gb.bits.exponent == $ZERO && $gb.bits.mantissa == $ZERO)) {
      $gr.raw := $ZERO;
      $gr.bits.sign := $gsign_out;
      return;
   }
";
      $s .= "   nlf_${san}_sig_from_u(&$gsig_a, $ga.bits.mantissa);
   nlf_${san}_sig_from_u(&$gsig_b, $gb.bits.mantissa);
";
      $s .= "   $gexp_a := $ga.bits.exponent;
   $gexp_b := $gb.bits.exponent;
";
      $s .= "   if ($gexp_a == $EXP_ZERO_E) { $gexp_a := $EXP_ONE_E; }
   if ($gexp_b == $EXP_ZERO_E) { $gexp_b := $EXP_ONE_E; }
";
      $s .= "   if ($ga.bits.exponent != $ZERO) { nlf_${san}_sig_set_bit(&$gsig_a, $sig_hidden_bit); }
";
      $s .= "   if ($gb.bits.exponent != $ZERO) { nlf_${san}_sig_set_bit(&$gsig_b, $sig_hidden_bit); }
";
      $s .= "   $gexp_a := $gexp_a + $gexp_b - $EXP_BIAS_E;
";
      $s .= "   nlf_${san}_wide_mul(&$gwide_p, &$gsig_a, &$gsig_b);
";
      if ($mul_shift > 0) {
         $s .= "   nlf_${san}_wide_shr_bits_sticky(&$gwide_p, $mul_shift);
";
      }
      elsif ($mul_shift < 0) {
         my $l = -$mul_shift;
         $s .= "   nlf_${san}_wide_shl_bits(&$gwide_p, $l);
";
      }
      $s .= "   nlf_${san}_sig_from_wide_low(&$gsig_out, &$gwide_p);
";
      $s .= "   while (!nlf_${san}_sig_is_zero(&$gsig_out) && $gexp_a > $EXP_ONE_E && !nlf_${san}_sig_get_bit(&$gsig_out, $sig_hidden_ext_bit)) { nlf_${san}_sig_shl1(&$gsig_out); $gexp_a--; }
";
      $s .= "   while (!nlf_${san}_sig_is_zero(&$gsig_out) && $gexp_a < $EXP_ONE_E) { nlf_${san}_sig_shr1_sticky(&$gsig_out); $gexp_a++; }
";
      $s .= "   nlf_${san}_pack_result();
}

";
      return $s;
   }
   my $s = "${static_prefix}void $mul_impl(void) {
";
   $s .= "   if ($ga.bits.exponent == $EXP_MAX && $ga.bits.mantissa != $ZERO) {
      $gr.raw := $ga.raw;
      return;
   }
";
   $s .= "   if ($gb.bits.exponent == $EXP_MAX && $gb.bits.mantissa != $ZERO) {
      $gr.raw := $gb.raw;
      return;
   }
";
   $s .= "   $gsign_out := $ga.bits.sign ^ $gb.bits.sign;
";
   $s .= "   if (($ga.bits.exponent == $EXP_MAX && $ga.bits.mantissa == $ZERO && $gb.bits.exponent == $ZERO && $gb.bits.mantissa == $ZERO) || ($gb.bits.exponent == $EXP_MAX && $gb.bits.mantissa == $ZERO && $ga.bits.exponent == $ZERO && $ga.bits.mantissa == $ZERO)) {
      $gr.raw := $ZERO;
      $gr.bits.sign := $ZERO;
      $gr.bits.exponent := $EXP_MAX;
      $gr.bits.mantissa := $NAN_PAYLOAD;
      return;
   }
";
   $s .= "   if ($ga.bits.exponent == $EXP_MAX && $ga.bits.mantissa == $ZERO) {
      $gr.raw := $ZERO;
      $gr.bits.sign := $gsign_out;
      $gr.bits.exponent := $EXP_MAX;
      return;
   }
";
   $s .= "   if ($gb.bits.exponent == $EXP_MAX && $gb.bits.mantissa == $ZERO) {
      $gr.raw := $ZERO;
      $gr.bits.sign := $gsign_out;
      $gr.bits.exponent := $EXP_MAX;
      return;
   }
";
   $s .= "   if (($ga.bits.exponent == $ZERO && $ga.bits.mantissa == $ZERO) || ($gb.bits.exponent == $ZERO && $gb.bits.mantissa == $ZERO)) {
      $gr.raw := $ZERO;
      $gr.bits.sign := $gsign_out;
      return;
   }
";
   $s .= "   $gsig_a := $ga.bits.mantissa;
   $gsig_b := $gb.bits.mantissa;
   $gexp_a := $ga.bits.exponent;
   $gexp_b := $gb.bits.exponent;
   if ($gexp_a == $M_ZERO) { $gexp_a := $M_ONE; }
   if ($gexp_b == $M_ZERO) { $gexp_b := $M_ONE; }
   if ($ga.bits.exponent != $ZERO) { $gsig_a |= $M_HIDDEN; }
   if ($gb.bits.exponent != $ZERO) { $gsig_b |= $M_HIDDEN; }
   $gexp_a := $gexp_a + $gexp_b - $M_BIAS;
   $gwide_a.v := $gsig_a;
   $gwide_b.v := $gsig_b;
   $gwide_p.v := $gwide_a.v * $gwide_b.v;
";
   if ($mbits > 3) {
      my $shift = $mbits - 3;
      $s .= "   $gwide_t.v := $gwide_p.v >> $shift;
";
      $s .= "   $gwide_a.v := $gwide_t.v << $shift;
";
      $s .= "   if ($gwide_a.v != $gwide_p.v) { $gwide_t.v |= $W_ONE; }
";
      $s .= "   $gwide_p.v := $gwide_t.v;
";
   }
   elsif ($mbits < 3) {
      my $shift = 3 - $mbits;
      $s .= "   $gwide_p.v := $gwide_p.v << $shift;
";
   }
   $s .= "   $gsig_out := $gwide_p.v;
";
   $s .= "   while ($gsig_out != $M_ZERO && $gexp_a > $M_ONE && $gsig_out < $M_HIDDEN_EXT) { $gsig_out *= $M_TWO; $gexp_a--; }
";
   $s .= "   while ($gsig_out != $M_ZERO && $gexp_a < $M_ONE) { $matht lost; lost := $gsig_out & $M_ONE; $gsig_out /= $M_TWO; if (lost != $M_ZERO) { $gsig_out |= $M_ONE; } $gexp_a++; }
";
   $s .= pack_snippet($gsig_out, $gexp_a, $gsign_out, $gr, $gmant_ll);
   $s .= "}

";
   return $s;
}

sub div_impl_text {
   my ($static_prefix) = @_;
   if ($wide_math) {
      my $s = "${static_prefix}void $div_impl(void) {
";
      $s .= "   bool rem_sticky;
";
      $s .= "   if ($ga.bits.exponent == $EXP_MAX && $ga.bits.mantissa != $ZERO) {
      $gr.raw := $ga.raw;
      return;
   }
";
      $s .= "   if ($gb.bits.exponent == $EXP_MAX && $gb.bits.mantissa != $ZERO) {
      $gr.raw := $gb.raw;
      return;
   }
";
      $s .= "   $gsign_out := $ga.bits.sign ^ $gb.bits.sign;
";
      $s .= "   if (($ga.bits.exponent == $EXP_MAX && $ga.bits.mantissa == $ZERO && $gb.bits.exponent == $EXP_MAX && $gb.bits.mantissa == $ZERO) || ($ga.bits.exponent == $ZERO && $ga.bits.mantissa == $ZERO && $gb.bits.exponent == $ZERO && $gb.bits.mantissa == $ZERO)) {
      $gr.raw := $ZERO;
      $gr.bits.sign := $ZERO;
      $gr.bits.exponent := $EXP_MAX;
      $gr.bits.mantissa := $NAN_PAYLOAD;
      return;
   }
";
      $s .= "   if ($ga.bits.exponent == $EXP_MAX && $ga.bits.mantissa == $ZERO) {
      $gr.raw := $ZERO;
      $gr.bits.sign := $gsign_out;
      $gr.bits.exponent := $EXP_MAX;
      return;
   }
";
      $s .= "   if ($gb.bits.exponent == $EXP_MAX && $gb.bits.mantissa == $ZERO) {
      $gr.raw := $ZERO;
      $gr.bits.sign := $gsign_out;
      return;
   }
";
      $s .= "   if ($gb.bits.exponent == $ZERO && $gb.bits.mantissa == $ZERO) {
      $gr.raw := $ZERO;
      $gr.bits.sign := $gsign_out;
      $gr.bits.exponent := $EXP_MAX;
      return;
   }
";
      $s .= "   if ($ga.bits.exponent == $ZERO && $ga.bits.mantissa == $ZERO) {
      $gr.raw := $ZERO;
      $gr.bits.sign := $gsign_out;
      return;
   }
";
      $s .= "   nlf_${san}_sig_from_u(&$gsig_a, $ga.bits.mantissa);
   nlf_${san}_sig_from_u(&$gsig_b, $gb.bits.mantissa);
";
      $s .= "   $gexp_a := $ga.bits.exponent;
   $gexp_b := $gb.bits.exponent;
";
      $s .= "   if ($gexp_a == $EXP_ZERO_E) { $gexp_a := $EXP_ONE_E; }
   if ($gexp_b == $EXP_ZERO_E) { $gexp_b := $EXP_ONE_E; }
";
      $s .= "   if ($ga.bits.exponent != $ZERO) { nlf_${san}_sig_set_bit(&$gsig_a, $sig_hidden_bit); }
";
      $s .= "   if ($gb.bits.exponent != $ZERO) { nlf_${san}_sig_set_bit(&$gsig_b, $sig_hidden_bit); }
";
      $s .= "   $gexp_a := $gexp_a - $gexp_b + $EXP_BIAS_E;
";
      $s .= "   nlf_${san}_sig_div_shifted(&$gsig_out, &$gsig_a, &$gsig_b, @{[$mbits + 3]}, &rem_sticky);
";
      $s .= "   if (rem_sticky) { $gsig_out.bytes[0] := $gsig_out.bytes[0] | 1; }
";
      $s .= "   while (!nlf_${san}_sig_is_zero(&$gsig_out) && $gexp_a > $EXP_ONE_E && !nlf_${san}_sig_get_bit(&$gsig_out, $sig_hidden_ext_bit)) { nlf_${san}_sig_shl1(&$gsig_out); $gexp_a--; }
";
      $s .= "   while (!nlf_${san}_sig_is_zero(&$gsig_out) && $gexp_a < $EXP_ONE_E) { nlf_${san}_sig_shr1_sticky(&$gsig_out); $gexp_a++; }
";
      $s .= "   nlf_${san}_pack_result();
}

";
      return $s;
   }
   my $s = "${static_prefix}void $div_impl(void) {
";
   $s .= "   if ($ga.bits.exponent == $EXP_MAX && $ga.bits.mantissa != $ZERO) {
      $gr.raw := $ga.raw;
      return;
   }
";
   $s .= "   if ($gb.bits.exponent == $EXP_MAX && $gb.bits.mantissa != $ZERO) {
      $gr.raw := $gb.raw;
      return;
   }
";
   $s .= "   $gsign_out := $ga.bits.sign ^ $gb.bits.sign;
";
   $s .= "   if (($ga.bits.exponent == $EXP_MAX && $ga.bits.mantissa == $ZERO && $gb.bits.exponent == $EXP_MAX && $gb.bits.mantissa == $ZERO) || ($ga.bits.exponent == $ZERO && $ga.bits.mantissa == $ZERO && $gb.bits.exponent == $ZERO && $gb.bits.mantissa == $ZERO)) {
      $gr.raw := $ZERO;
      $gr.bits.sign := $ZERO;
      $gr.bits.exponent := $EXP_MAX;
      $gr.bits.mantissa := $NAN_PAYLOAD;
      return;
   }
";
   $s .= "   if ($ga.bits.exponent == $EXP_MAX && $ga.bits.mantissa == $ZERO) {
      $gr.raw := $ZERO;
      $gr.bits.sign := $gsign_out;
      $gr.bits.exponent := $EXP_MAX;
      return;
   }
";
   $s .= "   if ($gb.bits.exponent == $EXP_MAX && $gb.bits.mantissa == $ZERO) {
      $gr.raw := $ZERO;
      $gr.bits.sign := $gsign_out;
      return;
   }
";
   $s .= "   if ($gb.bits.exponent == $ZERO && $gb.bits.mantissa == $ZERO) {
      $gr.raw := $ZERO;
      $gr.bits.sign := $gsign_out;
      $gr.bits.exponent := $EXP_MAX;
      return;
   }
";
   $s .= "   if ($ga.bits.exponent == $ZERO && $ga.bits.mantissa == $ZERO) {
      $gr.raw := $ZERO;
      $gr.bits.sign := $gsign_out;
      return;
   }
";
   $s .= "   $gsig_a := $ga.bits.mantissa;
   $gsig_b := $gb.bits.mantissa;
   $gexp_a := $ga.bits.exponent;
   $gexp_b := $gb.bits.exponent;
   if ($gexp_a == $M_ZERO) { $gexp_a := $M_ONE; }
   if ($gexp_b == $M_ZERO) { $gexp_b := $M_ONE; }
   if ($ga.bits.exponent != $ZERO) { $gsig_a |= $M_HIDDEN; }
   if ($gb.bits.exponent != $ZERO) { $gsig_b |= $M_HIDDEN; }
   $gexp_a := $gexp_a - $gexp_b + $M_BIAS;
   $gwide_a.v := $gsig_a;
   $gwide_a.v := $gwide_a.v << @{[$mbits + 3]};
   $gwide_b.v := $gsig_b;
   $gwide_p.v := $gwide_a.v / $gwide_b.v;
   $gwide_t.v := $gwide_p.v * $gwide_b.v;
   if ($gwide_t.v != $gwide_a.v) { $gwide_p.v |= $W_ONE; }
";
   $s .= "   while ($gwide_p.v != $W_ZERO && $gexp_a > $M_ONE && $gwide_p.v < $W_HIDDEN_EXT) { $gwide_p.v := $gwide_p.v << 1; $gexp_a--; }
";
   $s .= "   while ($gwide_p.v != $W_ZERO && $gexp_a < $M_ONE) { $gwide_t.v := $gwide_p.v & $W_ONE; $gwide_p.v := $gwide_p.v >> 1; if ($gwide_t.v != $W_ZERO) { $gwide_p.v |= $W_ONE; } $gexp_a++; }
";
   $s .= "   $gsig_out := $gwide_p.v;
";
   $s .= pack_snippet($gsig_out, $gexp_a, $gsign_out, $gr, $gmant_ll);
   $s .= "}

";
   return $s;
}

sub operator_add_text {
   my $s = "$typename operator+($typename lhs, $typename rhs) {
";
   $s .= load_code($ga, 'lhs', 'av');
   $s .= load_code($gb, 'rhs', 'bv');
   $s .= "   $add_impl();
";
   $s .= store_code($gr, 'rv');
   $s .= "}

";
   return $s;
}

sub operator_pos_text {
   my $s = "$typename operator+($typename v) {
";
   $s .= "   return v;
";
   $s .= "}

";
   return $s;
}

sub operator_neg_text {
   my $s = "$typename operator-($typename v) {
";
   $s .= load_code($ga, 'v', 'av');
   $s .= "   $ga.bits.sign ^= $ONE;
";
   $s .= store_code($ga, 'rv');
   $s .= "}

";
   return $s;
}

sub operator_sub_text {
   my $s = "$typename operator-($typename lhs, $typename rhs) {
";
   $s .= "   return lhs + (-rhs);
";
   $s .= "}

";
   return $s;
}

sub operator_mul_text {
   my $s = "$typename operator*($typename lhs, $typename rhs) {
";
   $s .= load_code($ga, 'lhs', 'av');
   $s .= load_code($gb, 'rhs', 'bv');
   $s .= "   $mul_impl();
";
   $s .= store_code($gr, 'rv');
   $s .= "}

";
   return $s;
}

sub operator_div_text {
   my $s = "$typename operator/($typename lhs, $typename rhs) {
";
   $s .= load_code($ga, 'lhs', 'av');
   $s .= load_code($gb, 'rhs', 'bv');
   $s .= "   $div_impl();
";
   $s .= store_code($gr, 'rv');
   $s .= "}

";
   return $s;
}

sub operator_eq_text {
   my $s = "bool operator==($typename lhs, $typename rhs) {
";
   $s .= load_code($ga, 'lhs', 'av');
   $s .= load_code($gb, 'rhs', 'bv');
   $s .= "   $cmp_impl();
   if ($gunordered) { return false; }
   if ($gcmp == $CMP_EQ) { return true; }
   return false;
}

";
   return $s;
}

sub operator_ne_text {
   my $s = "bool operator!=($typename lhs, $typename rhs) {
";
   $s .= "   return !(lhs == rhs);
";
   $s .= "}

";
   return $s;
}

sub operator_lt_text {
   my $s = "bool operator<($typename lhs, $typename rhs) {
";
   $s .= load_code($ga, 'lhs', 'av');
   $s .= load_code($gb, 'rhs', 'bv');
   $s .= "   $cmp_impl();
   if ($gunordered) { return false; }
   if ($gcmp == $CMP_LT) { return true; }
   return false;
}

";
   return $s;
}

sub operator_gt_text {
   my $s = "bool operator>($typename lhs, $typename rhs) {
";
   $s .= "   return rhs < lhs;
";
   $s .= "}

";
   return $s;
}

sub operator_le_text {
   my $s = "bool operator<=($typename lhs, $typename rhs) {
";
   $s .= "   if (lhs < rhs) { return true; }
";
   $s .= "   return lhs == rhs;
";
   $s .= "}

";
   return $s;
}

sub operator_ge_text {
   my $s = "bool operator>=($typename lhs, $typename rhs) {
";
   $s .= "   if (rhs < lhs) { return true; }
";
   $s .= "   return lhs == rhs;
";
   $s .= "}

";
   return $s;
}

sub operator_truth_text {
   my $s = "bool operator{}($typename v) {
";
   $s .= load_code($ga, 'v', 'av');
   $s .= "   if ($ga.bits.exponent != $ZERO) { return true; }
";
   $s .= "   if ($ga.bits.mantissa != $ZERO) { return true; }
";
   $s .= "   return false;
";
   $s .= "}

";
   return $s;
}

sub operator_inc_text {
   my $s = "$typename operator++(ref $typename v) {
";
   $s .= "   $typename one;
";
   $s .= "   one := 1.0;
";
   $s .= "   v := v + one;
";
   $s .= "   return v;
";
   $s .= "}

";
   return $s;
}

sub operator_dec_text {
   my $s = "$typename operator--(ref $typename v) {
";
   $s .= "   $typename one;
";
   $s .= "   one := 1.0;
";
   $s .= "   v := v - one;
";
   $s .= "   return v;
";
   $s .= "}

";
   return $s;
}

sub monolith_text {
   return comment_header()
      . base_runtime_block('', {
         ga => 1, gb => 1, gr => 1,
         gwide_a => 1, gwide_b => 1, gwide_p => 1, gwide_t => 1,
         gmant_ll => 1, gexp_a => 1, gexp_b => 1, gsign_out => 1,
         gsig_a => 1, gsig_b => 1, gsig_out => 1, gcmp => 1, gunordered => 1,
      })
      . add_impl_text('')
      . cmp_impl_text('')
      . mul_impl_text('')
      . div_impl_text('')
      . operator_add_text()
      . operator_pos_text()
      . operator_neg_text()
      . operator_sub_text()
      . operator_mul_text()
      . operator_div_text()
      . operator_eq_text()
      . operator_ne_text()
      . operator_lt_text()
      . operator_gt_text()
      . operator_le_text()
      . operator_ge_text()
      . operator_truth_text()
      . operator_inc_text()
      . operator_dec_text();
}

sub ieee754_expbits_for_size {
   my ($n) = @_;
   return 5 if $n == 2;
   return 8 if $n == 4;
   return 11 if $n == 8;
   return 0 - 1;
}

sub simple_expbits_for_size {
   my ($n) = @_;
   return -1 if $n <= 0;
   my $bits = $n * 8;
   my $raw = 3.0 * (log($n) / log(2.0)) + 2.0;
   my $eb = int($raw + 0.5);
   $eb = 1 if $eb < 1;
   $eb = $bits - 2 if 1 + $eb >= $bits;
   return $eb > 0 ? $eb : -1;
}

sub inferred_float_style {
   return 'ieee754' if $expbits == ieee754_expbits_for_size($size);
   return 'simple' if $expbits == simple_expbits_for_size($size);
   return undef;
}

sub decls_text {
   my $style = inferred_float_style();
   my $s = comment_header();
   if ($style) {
      $s .= "type $typename { \$size:$size \$endian:$endian \$float:$style \$exactops };\n\n";
   }
   else {
      $s .= "// note: could not infer a built-in \$float: style for expbits=$expbits; the generated declaration uses only size/endian\n";
      $s .= "type $typename { \$size:$size \$endian:$endian \$exactops };\n\n";
   }
   $s .= "extern $typename operator+($typename lhs, $typename rhs);\n";
   $s .= "extern $typename operator+($typename v);\n";
   $s .= "extern $typename operator-($typename lhs, $typename rhs);\n";
   $s .= "extern $typename operator-($typename v);\n";
   $s .= "extern $typename operator*($typename lhs, $typename rhs);\n";
   $s .= "extern $typename operator/($typename lhs, $typename rhs);\n";
   $s .= "extern bool operator==($typename lhs, $typename rhs);\n";
   $s .= "extern bool operator!=($typename lhs, $typename rhs);\n";
   $s .= "extern bool operator<($typename lhs, $typename rhs);\n";
   $s .= "extern bool operator>($typename lhs, $typename rhs);\n";
   $s .= "extern bool operator<=($typename lhs, $typename rhs);\n";
   $s .= "extern bool operator>=($typename lhs, $typename rhs);\n";
   $s .= "extern bool operator{}($typename v);\n";
   $s .= "extern $typename operator++(ref $typename v);\n";
   $s .= "extern $typename operator--(ref $typename v);\n";
   return $s;
}

sub standalone_prelude {
   my $style = inferred_float_style();
   my $s = <<"PRELUDE";
type void     { \$size:0 };
type char     { \$size:1 \$integer:signed };
type bool     { \$size:1 \$integer:unsigned };
type *        { \$size:2 \$integer:unsigned \$endian:little };
type int      { \$size:2 \$integer:signed \$endian:little };
type long     { \$size:4 \$integer:signed \$endian:little };
type longlong { \$size:8 \$integer:signed \$endian:little };
PRELUDE
   if ($style) {
      $s .= "type $typename { \$size:$size \$endian:$endian \$float:$style \$exactops };
";
   }
   else {
      $s .= "type $typename { \$size:$size \$endian:$endian \$exactops };
";
   }
   $s .= "
";
   return $s;
}

my %build_units = (
   core => {
      source_name => "${typename}_core.n",
      source_text => sub { return build_unit_text('', {
         ga => 1, gb => 1, gr => 1,
         gwide_a => 1, gwide_b => 1, gwide_p => 1, gwide_t => 1,
         gmant_ll => 1, gexp_a => 1, gexp_b => 1, gsign_out => 1,
         gsig_a => 1, gsig_b => 1, gsig_out => 1, gcmp => 1, gunordered => 1,
      }, '', ''); },
   },
   add_impl => {
      source_name => "${typename}_add_impl.n",
      source_text => sub { return build_unit_text('extern ', {
         ga => 1, gb => 1, gr => 1,
         gmant_ll => 1, gexp_a => 1, gexp_b => 1, gsign_out => 1,
         gsig_a => 1, gsig_b => 1, gsig_out => 1, gcmp => 1,
      }, '', add_impl_text('')); },
   },
   cmp_impl => {
      source_name => "${typename}_cmp_impl.n",
      source_text => sub { return build_unit_text('extern ', {
         ga => 1, gb => 1, gcmp => 1, gunordered => 1,
      }, '', cmp_impl_text('')); },
   },
   mul_impl => {
      source_name => "${typename}_mul_impl.n",
      source_text => sub { return build_unit_text('extern ', {
         ga => 1, gb => 1, gr => 1,
         gwide_a => 1, gwide_b => 1, gwide_p => 1, gwide_t => 1,
         gmant_ll => 1, gexp_a => 1, gexp_b => 1, gsign_out => 1,
         gsig_a => 1, gsig_b => 1, gsig_out => 1,
      }, '', mul_impl_text('')); },
   },
   div_impl => {
      source_name => "${typename}_div_impl.n",
      source_text => sub { return build_unit_text('extern ', {
         ga => 1, gb => 1, gr => 1,
         gwide_a => 1, gwide_b => 1, gwide_p => 1, gwide_t => 1,
         gmant_ll => 1, gexp_a => 1, gexp_b => 1, gsign_out => 1,
         gsig_a => 1, gsig_b => 1, gsig_out => 1,
      }, '', div_impl_text('')); },
   },
   add => {
      source_name => "${typename}_operator_add.n",
      source_text => sub { return build_unit_text('extern ', { ga => 1, gb => 1, gr => 1 }, proc_decl_text($add_impl), operator_add_text()); },
   },
   pos => {
      source_name => "${typename}_operator_pos.n",
      source_text => sub { return build_unit_text('extern ', {}, '', operator_pos_text()); },
   },
   neg => {
      source_name => "${typename}_operator_neg.n",
      source_text => sub { return build_unit_text('extern ', { ga => 1 }, '', operator_neg_text()); },
   },
   sub => {
      source_name => "${typename}_operator_sub.n",
      source_text => sub { return build_unit_text('extern ', {}, operator_binary_decl_text($typename, 'operator+') . operator_unary_decl_text($typename, 'operator-'), operator_sub_text()); },
   },
   mul => {
      source_name => "${typename}_operator_mul.n",
      source_text => sub { return build_unit_text('extern ', { ga => 1, gb => 1, gr => 1 }, proc_decl_text($mul_impl), operator_mul_text()); },
   },
   div => {
      source_name => "${typename}_operator_div.n",
      source_text => sub { return build_unit_text('extern ', { ga => 1, gb => 1, gr => 1 }, proc_decl_text($div_impl), operator_div_text()); },
   },
   eq => {
      source_name => "${typename}_operator_eq.n",
      source_text => sub { return build_unit_text('extern ', { ga => 1, gb => 1, gcmp => 1, gunordered => 1 }, proc_decl_text($cmp_impl), operator_eq_text()); },
   },
   ne => {
      source_name => "${typename}_operator_ne.n",
      source_text => sub { return build_unit_text('extern ', {}, operator_binary_decl_text('bool', 'operator=='), operator_ne_text()); },
   },
   lt => {
      source_name => "${typename}_operator_lt.n",
      source_text => sub { return build_unit_text('extern ', { ga => 1, gb => 1, gcmp => 1, gunordered => 1 }, proc_decl_text($cmp_impl), operator_lt_text()); },
   },
   gt => {
      source_name => "${typename}_operator_gt.n",
      source_text => sub { return build_unit_text('extern ', {}, operator_binary_decl_text('bool', 'operator<'), operator_gt_text()); },
   },
   le => {
      source_name => "${typename}_operator_le.n",
      source_text => sub { return build_unit_text('extern ', {}, operator_binary_decl_text('bool', 'operator<') . operator_binary_decl_text('bool', 'operator=='), operator_le_text()); },
   },
   ge => {
      source_name => "${typename}_operator_ge.n",
      source_text => sub { return build_unit_text('extern ', {}, operator_binary_decl_text('bool', 'operator<') . operator_binary_decl_text('bool', 'operator=='), operator_ge_text()); },
   },
   truth => {
      source_name => "${typename}_operator_truth.n",
      source_text => sub { return build_unit_text('extern ', { ga => 1 }, '', operator_truth_text()); },
   },
   inc => {
      source_name => "${typename}_operator_inc.n",
      source_text => sub { return build_unit_text('extern ', {}, operator_binary_decl_text($typename, 'operator+'), operator_inc_text()); },
   },
   dec => {
      source_name => "${typename}_operator_dec.n",
      source_text => sub { return build_unit_text('extern ', {}, operator_binary_decl_text($typename, 'operator-'), operator_dec_text()); },
   },
);

my @build_order = qw(
   add pos neg sub mul div eq ne lt gt le ge truth inc dec
   add_impl cmp_impl mul_impl div_impl
   core
);


sub split_generated_functions {
   my ($text) = @_;
   my @out;
   my $len = length($text);
   my $pos = 0;
   while ($pos < $len) {
      while ($pos < $len && substr($text, $pos, 1) =~ /\s/) { $pos++; }
      last if $pos >= $len;
      my $start = $pos;
      if (substr($text, $pos) !~ /\A(?:void|bool|int|long|longlong|[A-Za-z_][A-Za-z0-9_]*)\s+([A-Za-z0-9_]+)\s*\([^)]*\)\s*\{/s) {
         die "$0: could not split generated helper functions near: " . substr($text, $pos, 40) . "\n";
      }
      my $name = $1;
      my $brace = 0;
      while ($pos < $len) {
         my $c = substr($text, $pos, 1);
         $brace++ if $c eq '{';
         $brace-- if $c eq '}';
         $pos++;
         last if $brace == 0 && $c eq '}';
      }
      my $chunk = substr($text, $start, $pos - $start) . "\n\n";
      push @out, [$name, $chunk];
   }
   return @out;
}


sub helper_names_in_text {
   my ($text, @exclude) = @_;
   my %skip = map { $_ => 1 } @exclude;
   my %seen;
   while ($text =~ /\b(nlf_${san}_[A-Za-z0-9_]+)\s*\(/g) {
      my $name = $1;
      next if $skip{$name};
      next if $name eq $add_impl || $name eq $cmp_impl || $name eq $mul_impl || $name eq $div_impl;
      $seen{$name} = 1;
   }
   return sort keys %seen;
}

sub wide_build_unit_text {
   my ($vars, $helper_names, $decls, $body) = @_;
   return comment_header()
      . standalone_prelude()
      . wide_runtime_block('extern ', $vars, 0, $helper_names, $decls)
      . ($body || '');
}

sub run_checked {
   my (@cmd) = @_;
   system(@cmd);
   if ($? != 0) {
      my $ec = $? >> 8;
      my $sig = $? & 127;
      die "$0: command failed (exit=$ec signal=$sig): @cmd\n";
   }
}

sub path_is_exec {
   my ($path) = @_;
   return defined($path) && $path ne '' && -x $path;
}

sub find_executable {
   my ($env_name, @candidates) = @_;
   return $ENV{$env_name} if path_is_exec($ENV{$env_name});
   die "$0: $env_name is set but is not executable: $ENV{$env_name}
"
      if defined($ENV{$env_name}) && $ENV{$env_name} ne '';

   for my $candidate (@candidates) {
      return $candidate if path_is_exec($candidate);
   }

   for my $dir (File::Spec->path()) {
      my $candidate = File::Spec->catfile($dir, lc($env_name));
      return $candidate if path_is_exec($candidate);
   }

   die "$0: required tool not found: " . lc($env_name) . "
";
}

sub build_mode_paths {
   my $script_dir = abs_path($FindBin::RealBin);
   my $repo_root = abs_path(File::Spec->catdir($script_dir, '..', '..'));
   my $prefix = abs_path(File::Spec->catdir($script_dir, '..'));

   my $n65c = find_executable('N65C',
      File::Spec->catfile($repo_root, 'compiler', 'n65c'),
      File::Spec->catfile($script_dir, 'n65c'));
   my $n65asm = find_executable('N65ASM',
      File::Spec->catfile($repo_root, 'assembler', 'n65asm'),
      File::Spec->catfile($script_dir, 'n65asm'));
   my $n65ar = find_executable('N65AR',
      File::Spec->catfile($repo_root, 'archiver', 'n65ar'),
      File::Spec->catfile($script_dir, 'n65ar'));

   my @include_candidates = (
      $ENV{NLIB_INC},
      File::Spec->catdir($repo_root, 'libraries', 'nlib'),
      File::Spec->catdir($prefix, 'include'),
   );
   for my $candidate (@include_candidates) {
      return ($n65c, $n65asm, $n65ar, $candidate)
         if defined($candidate) && $candidate ne '' && -d $candidate;
   }
   die "$0: required nlib include dir not found; set NLIB_INC
";
}

sub build_mode {
   my $out_dir = File::Spec->rel2abs($build_dir);
   my ($n65c, $n65asm, $n65ar, $nlib_inc) = build_mode_paths();

   make_path($out_dir) if !-d $out_dir;

   my $decls_path = File::Spec->catfile($out_dir, "${typename}_decls.n");
   open(my $dfh, '>', $decls_path) or die "$0: could not write $decls_path: $!
";
   print $dfh decls_text();
   close($dfh);

   my @member_objects;
   if ($wide_math) {
      my %allvars = (
         ga => 1, gb => 1, gr => 1,
         gwide_a => 1, gwide_b => 1, gwide_p => 1, gwide_t => 1,
         gexp_a => 1, gexp_b => 1, gsign_out => 1,
         gsig_a => 1, gsig_b => 1, gsig_out => 1,
         gcmp => 1, gunordered => 1,
      );
      my %helper_vars = (
         "nlf_${san}_pack_result" => { gr => 1, gexp_a => 1, gsign_out => 1, gsig_out => 1 },
      );
      my %unit_vars = (
         add_impl => { ga => 1, gb => 1, gr => 1, gexp_a => 1, gexp_b => 1, gsign_out => 1, gsig_a => 1, gsig_b => 1, gsig_out => 1, gcmp => 1 },
         cmp_impl => { ga => 1, gb => 1, gcmp => 1, gunordered => 1 },
         mul_impl => { ga => 1, gb => 1, gr => 1, gwide_p => 1, gexp_a => 1, gexp_b => 1, gsign_out => 1, gsig_a => 1, gsig_b => 1, gsig_out => 1 },
         div_impl => { ga => 1, gb => 1, gr => 1, gexp_a => 1, gexp_b => 1, gsign_out => 1, gsig_a => 1, gsig_b => 1, gsig_out => 1 },
         add => { ga => 1, gb => 1, gr => 1 },
         pos => {},
         neg => { ga => 1 },
         sub => {},
         mul => { ga => 1, gb => 1, gr => 1 },
         div => { ga => 1, gb => 1, gr => 1 },
         eq => { ga => 1, gb => 1, gcmp => 1, gunordered => 1 },
         ne => {},
         lt => { ga => 1, gb => 1, gcmp => 1, gunordered => 1 },
         gt => {},
         le => {},
         ge => {},
         truth => { ga => 1 },
         inc => {},
         dec => {},
      );
      my %unit_decl = (
         add => proc_decl_text($add_impl),
         sub => operator_binary_decl_text($typename, 'operator+') . operator_unary_decl_text($typename, 'operator-'),
         mul => proc_decl_text($mul_impl),
         div => proc_decl_text($div_impl),
         eq => proc_decl_text($cmp_impl),
         ne => operator_binary_decl_text('bool', 'operator=='),
         lt => proc_decl_text($cmp_impl),
         gt => operator_binary_decl_text('bool', 'operator<'),
         le => operator_binary_decl_text('bool', 'operator<') . operator_binary_decl_text('bool', 'operator=='),
         ge => operator_binary_decl_text('bool', 'operator<') . operator_binary_decl_text('bool', 'operator=='),
         inc => operator_binary_decl_text($typename, 'operator+'),
         dec => operator_binary_decl_text($typename, 'operator-'),
      );
      my %unit_body = (
         add_impl => add_impl_text(''),
         cmp_impl => cmp_impl_text(''),
         mul_impl => mul_impl_text(''),
         div_impl => div_impl_text(''),
         add => operator_add_text(),
         pos => operator_pos_text(),
         neg => operator_neg_text(),
         sub => operator_sub_text(),
         mul => operator_mul_text(),
         div => operator_div_text(),
         eq => operator_eq_text(),
         ne => operator_ne_text(),
         lt => operator_lt_text(),
         gt => operator_gt_text(),
         le => operator_le_text(),
         ge => operator_ge_text(),
         truth => operator_truth_text(),
         inc => operator_inc_text(),
         dec => operator_dec_text(),
      );
      my @wide_units;
      push @wide_units, ["${typename}_core.n", comment_header() . standalone_prelude() . wide_runtime_block('', \%allvars, 0, [], undef)];
      for my $ent (split_generated_functions(wide_helper_text())) {
         my ($name, $chunk) = @$ent;
         my @deps = helper_names_in_text($chunk, $name);
         my $src_name = "${typename}_${name}.n";
         my $src_text = comment_header() . standalone_prelude() . wide_runtime_block('extern ', $helper_vars{$name} || {}, 0, \@deps, undef) . $chunk;
         push @wide_units, [$src_name, $src_text];
      }
      for my $key (@build_order) {
         next if $key eq "core";
         my @deps = helper_names_in_text($unit_body{$key});
         my $src_text = wide_build_unit_text($unit_vars{$key}, \@deps, $unit_decl{$key}, $unit_body{$key});
         push @wide_units, [$build_units{$key}->{source_name}, $src_text];
      }
      for my $ent (@wide_units) {
         my ($src_name, $src_text) = @$ent;
         my $src_path = File::Spec->catfile($out_dir, $src_name);
         my ($stem) = $src_name =~ /^(.*)\.n$/;
         my $s_path = File::Spec->catfile($out_dir, "$stem.s");
         my $o_path = File::Spec->catfile($out_dir, "$stem.o65");
         open(my $sfh, '>', $src_path) or die "$0: could not write $src_path: $!
";
         print $sfh $src_text;
         close($sfh);
         run_checked($n65c, '-quiet', $src_path, '-o', $s_path);
         run_checked($n65asm, '-I', $nlib_inc, '-o', $o_path, $s_path);
         push @member_objects, $o_path;
      }
   }
   else {
      for my $key (@build_order) {
         my $src_name = $build_units{$key}->{source_name};
         my $src_path = File::Spec->catfile($out_dir, $src_name);
         my ($stem) = $src_name =~ /^(.*)\.n$/;
         my $s_path = File::Spec->catfile($out_dir, "$stem.s");
         my $o_path = File::Spec->catfile($out_dir, "$stem.o65");

         open(my $sfh, '>', $src_path) or die "$0: could not write $src_path: $!
";
         print $sfh $build_units{$key}->{source_text}->();
         close($sfh);

         run_checked($n65c, '-quiet', $src_path, '-o', $s_path);
         run_checked($n65asm, '-I', $nlib_inc, '-o', $o_path, $s_path);
         push @member_objects, $o_path;
      }
   }

   my $archive_path = File::Spec->catfile($out_dir, "${typename}.a65");
   run_checked($n65ar, 'rcs', $archive_path, @member_objects);
}

if (defined $build_dir) {
   build_mode();
}
else {
   print monolith_text();
}
