#!/usr/bin/perl
use strict;
use warnings;

sub mangle_text {
   my ($text) = @_;
   my $out = '';
   foreach my $c (split //, $text) {
      if ($c =~ /[A-Za-z0-9]/) {
         $out .= $c;
      }
      else {
         $out .= sprintf('x%02X', ord($c));
      }
   }
   return $out;
}

sub operator_mangle_code {
   my ($op, $argc) = @_;
   return $argc == 1 ? 'pos' : 'add' if $op eq '+';
   return $argc == 1 ? 'neg' : 'sub' if $op eq '-';
   return 'mul' if $op eq '*';
   return 'div' if $op eq '/';
   return 'mod' if $op eq '%';
   return 'and' if $op eq '&';
   return 'or'  if $op eq '|';
   return 'xor' if $op eq '^';
   return 'inv' if $op eq '~';
   return 'eq'  if $op eq '==';
   return 'ne'  if $op eq '!=';
   return 'lt'  if $op eq '<';
   return 'le'  if $op eq '<=';
   return 'gt'  if $op eq '>';
   return 'ge'  if $op eq '>=';
   return 'lsh' if $op eq '<<';
   return 'rsh' if $op eq '>>';
   return 'inc' if $op eq '++';
   return 'dec' if $op eq '--';
   return 'tst' if $op eq '{}';
   die "no operator mangle for '$op'";
}

sub sym {
   my ($op, @types) = @_;
   my $s = '?@op_' . operator_mangle_code($op, scalar(@types));
   foreach my $t (@types) {
      $s .= '@' . mangle_text($t) . '_p0_a0';
   }
   return $s;
}

sub emit_prologue {
}

sub emit_byte_arg0 {
   my ($value) = @_;
   die "byte value out of range: $value" if $value < 0 || $value > 255;
   print "    lda #\$" . sprintf('%02x', $value) . "\n";
   print "    sta arg0\n";
}

sub emit_ptr {
   my ($ptrn, $off, $sp_bias) = @_;
   $sp_bias = 0 if !defined $sp_bias;
   my $delta = hex($off) + $sp_bias;
   emit_byte_arg0($delta);
   print "    jsr _sp2ptr${ptrn}m\n";
}

sub emit_ptrp {
   my ($ptrn, $off, $sp_bias) = @_;
   $sp_bias = 0 if !defined $sp_bias;
   my $delta = hex($off) - $sp_bias;
   if ($delta >= 0) {
      emit_byte_arg0($delta);
      print "    jsr _sp2ptr${ptrn}p\n";
   }
   else {
      emit_byte_arg0(-$delta);
      print "    jsr _sp2ptr${ptrn}m\n";
   }
}

sub emit_rts { print "    rts\n"; }

sub emit_zero_ret {
   my ($ret_off, $size, $ptrn) = @_;
   emit_ptr($ptrn, sprintf('%02x', $ret_off));
   print "    ldy #0\n";
   print "\@zero_loop:\n";
   print "    lda #0\n";
   print "    sta (ptr$ptrn),y\n";
   print "    iny\n";
   print "    cpy #\$$size\n";
   print "    bne \@zero_loop\n";
}

my @types;
push @types, ['int', 2, 1], ['long', 4, 1], ['longlong', 8, 1], ['char', 1, 0], ['bool', 1, 0];
for my $n (1..16) {
   push @types, ["s$n", $n, 1], ["u$n", $n, 0];
}
my @floats = (['half',2], ['float',4], ['double',8]);

open my $fh, '>', 'asm/weakops.asm' or die $!;
select $fh;
print ";;; generated by libraries/nlib/gen_weakops.pl\n";
print ".include \"nlib.inc\"\n\n";

for my $t (@types) {
   my ($name, $size, $signed) = @$t;
   my $arg1 = $size;
   my $arg2 = $size * 2;
   my $ret  = $size * 3;
   my $uarg = $size;
   my $uret = $size * 2;
   my $cmp_ret = $size * 2 + 1;
   my $cmp_lhs = $size;
   my $cmp_rhs = $size * 2;
   my @bin_same = (
      ['+', 'addNle'], ['-', 'subNle'], ['&', 'bit_andN'], ['|', 'bit_orN'], ['^', 'bit_xorN']
   );
   for my $pair (@bin_same) {
      my ($op, $helper) = @$pair;
      my $sym = sym($op, $name, $name);
      print ".weak $sym\n.proc $sym\n";
      emit_prologue();
      emit_ptr(0, sprintf('%02x', $arg1));
      emit_ptr(1, sprintf('%02x', $arg2));
      emit_ptr(2, sprintf('%02x', $ret));
      print "    lda #\$" . sprintf('%02x', $size) . "\n";
      print "    sta arg0\n";
      print "    jsr _$helper\n";
      emit_rts();
      print ".endproc\n\n";
   }
   {
      my $sym = sym('*', $name, $name);
      my $scratch = $size * 2;
      print ".weak $sym\n.proc $sym\n";
      emit_prologue();
      print "    lda #\$" . sprintf('%02x', $scratch) . "\n";
      print "    sta arg0\n";
      print "    jsr _pushN\n";
      emit_ptr(0, sprintf('%02x', $arg1), $scratch);
      emit_ptr(1, sprintf('%02x', $arg2), $scratch);
      emit_ptrp(2, sprintf('%02x', 0), $scratch);
      print "    lda #\$" . sprintf('%02x', $size) . "\n";
      print "    sta arg0\n";
      print "    jsr _mulNle\n";
      emit_ptrp(0, sprintf('%02x', 0), $scratch);
      emit_ptr(1, sprintf('%02x', $ret), $scratch);
      print "    lda #\$" . sprintf('%02x', $size) . "\n";
      print "    sta arg0\n";
      print "    jsr _cpyN\n";
      print "    lda #\$" . sprintf('%02x', $scratch) . "\n";
      print "    sta arg0\n";
      print "    jsr _popN\n";
      emit_rts();
      print ".endproc\n\n";
   }
   for my $pair (['/', 0], ['%', 1]) {
      my ($op, $want_rem) = @$pair;
      my $sym = sym($op, $name, $name);
      my $scratch = $size * 2;
      my $quo = 0;
      my $rem = $size;
      print ".weak $sym\n.proc $sym\n";
      emit_prologue();
      print "    lda #\$" . sprintf('%02x', $scratch) . "\n";
      print "    sta arg0\n";
      print "    jsr _pushN\n";
      emit_ptr(0, sprintf('%02x', $arg1), $scratch);
      emit_ptr(1, sprintf('%02x', $arg2), $scratch);
      emit_ptrp(2, sprintf('%02x', $quo), $scratch);
      emit_ptrp(3, sprintf('%02x', $rem), $scratch);
      print "    lda #\$" . sprintf('%02x', $size) . "\n";
      print "    sta arg0\n";
      print "    jsr _divNle\n";
      emit_ptrp(0, sprintf('%02x', $want_rem ? $rem : $quo), $scratch);
      emit_ptr(1, sprintf('%02x', $ret), $scratch);
      print "    lda #\$" . sprintf('%02x', $size) . "\n";
      print "    sta arg0\n";
      print "    jsr _cpyN\n";
      print "    lda #\$" . sprintf('%02x', $scratch) . "\n";
      print "    sta arg0\n";
      print "    jsr _popN\n";
      emit_rts();
      print ".endproc\n\n";
   }
   for my $pair (['<<', 'lslNle'], ['>>', $signed ? 'asrNle' : 'lsrNle']) {
      my ($op, $helper) = @$pair;
      my $sym = sym($op, $name, $name);
      print ".weak $sym\n.proc $sym\n";
      emit_prologue();
      emit_ptr(0, sprintf('%02x', $arg1));
      emit_ptr(1, sprintf('%02x', $ret));
      emit_ptr(2, sprintf('%02x', $arg2));
      print "    ldy #0\n";
      print "    lda (ptr2),y\n";
      print "    sta arg1\n";
      print "    lda #\$" . sprintf('%02x', $size) . "\n";
      print "    sta arg0\n";
      print "    jsr _$helper\n";
      emit_rts();
      print ".endproc\n\n";
   }
   for my $pair (
      ['==', 'eqN', 0], ['!=', 'eqN', 1],
      ['<',  $signed ? 'ltNsle' : 'ltNule', 0],
      ['<=', $signed ? 'leNsle' : 'leNule', 0],
      ['>',  $signed ? 'ltNsle' : 'ltNule', 2],
      ['>=', $signed ? 'leNsle' : 'leNule', 2]
   ) {
      my ($op, $helper, $mode) = @$pair;
      my $sym = sym($op, $name, $name);
      print ".weak $sym\n.proc $sym\n";
      emit_prologue();
      if ($mode && $mode == 2) {
         emit_ptr(0, sprintf('%02x', $cmp_rhs));
         emit_ptr(1, sprintf('%02x', $cmp_lhs));
      }
      else {
         emit_ptr(0, sprintf('%02x', $cmp_lhs));
         emit_ptr(1, sprintf('%02x', $cmp_rhs));
      }
      print "    lda #\$" . sprintf('%02x', $size) . "\n";
      print "    sta arg0\n";
      print "    jsr _$helper\n";
      if ($mode && $mode == 1) {
         print "    lda arg1\n";
         print "    eor #1\n";
         print "    sta arg1\n";
      }
      emit_ptr(2, sprintf('%02x', $cmp_ret));
      print "    ldy #0\n";
      print "    lda arg1\n";
      print "    sta (ptr2),y\n";
      emit_rts();
      print ".endproc\n\n";
   }
   my $usym = sym('-', $name);
   print ".weak $usym\n.proc $usym\n";
   emit_prologue();
   emit_ptr(0, sprintf('%02x', $uarg));
   emit_ptr(1, sprintf('%02x', $uret));
   print "    lda #\$" . sprintf('%02x', $size) . "\n";
   print "    sta arg0\n";
   print "    jsr _comp2Nle\n";
   emit_rts();
   print ".endproc\n\n";

   my $tsym = sym('~', $name);
   print ".weak $tsym\n.proc $tsym\n";
   emit_prologue();
   emit_ptr(0, sprintf('%02x', $uarg));
   emit_ptr(2, sprintf('%02x', $uret));
   print "    lda #\$" . sprintf('%02x', $size) . "\n";
   print "    sta arg0\n";
   print "    jsr _bit_notN\n";
   emit_rts();
   print ".endproc\n\n";
}

for my $t (@floats) {
   my ($name, $size) = @$t;
   my $uarg = $size;
   my $uret = $size * 2;

   # Builtin half/float/double arithmetic and comparison operators live in
   # libraries/float/float.a65.  Keep nlib independent of the float runtime
   # archive; only the sign-bit unary negation helper stays here.

   my $usym = sym('-', $name);
   print ".weak $usym\n.proc $usym\n";
   emit_prologue();
   emit_ptr(0, sprintf('%02x', $uarg));
   emit_ptr(1, sprintf('%02x', $uret));
   print "    ldy #0\n";
   print "\@copy_loop:\n";
   print "    lda (ptr0),y\n";
   print "    sta (ptr1),y\n";
   print "    iny\n";
   print "    cpy #\$" . sprintf('%02x', $size) . "\n";
   print "    bne \@copy_loop\n";
   print "    ldy #\$" . sprintf('%02x', $size - 1) . "\n";
   print "    lda (ptr1),y\n";
   print "    eor #\$80\n";
   print "    sta (ptr1),y\n";
   emit_rts();
   print ".endproc\n\n";
}
