; nlib.inc

.importzp _nl_sp
.importzp _nl_fp
.importzp _nl_arg0
.importzp _nl_arg1
.importzp _nl_ptr0
.importzp _nl_ptr1
.importzp _nl_ptr2
.importzp _nl_ptr3
.importzp _nl_tmp0
.importzp _nl_tmp1
.importzp _nl_tmp2
.importzp _nl_tmp3
.importzp _nl_tmp4
.importzp _nl_tmp5

.def sp _nl_sp
.def fp _nl_fp
.def arg0 _nl_arg0
.def arg1 _nl_arg1
.def ptr0 _nl_ptr0
.def ptr1 _nl_ptr1
.def ptr2 _nl_ptr2
.def ptr3 _nl_ptr3
.def tmp0 _nl_tmp0
.def tmp1 _nl_tmp1
.def tmp2 _nl_tmp2
.def tmp3 _nl_tmp3
.def tmp4 _nl_tmp4
.def tmp5 _nl_tmp5
